Table "pokemon"."abilities" {
  "abil_id" int [pk, not null]
  "abil_name" varchar(500) [not null]
}

Table "pokemon"."pokemon_abilities" {
  "pok_id" int [not null, ref: < "pokemon"."pokemon"."pok_id"]
  "abil_id" int [not null, ref: < "pokemon"."abilities"."abil_id"]
  "is_hidden" int [not null]
  "slot" int [not null]
  "music" bigint

  Indexes {
    (pok_id, slot) [pk]
    is_hidden [name: "pokemon_abilities_pokemon_ix_pokemon_abilities_is_hidden"]
    abil_id [name: "pokemon_abilities_pokemon_abil_id"]
  }
}

Table "pokemon"."pokemon" {
  "pok_id" int [pk, not null]
  "pok_name" varchar(500) [not null]
  "pok_height" int
  "pok_weight" int
  "pok_base_experience" int
}
