import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/airbnb.png';
import imageDark from '@/assets/templates/airbnb-dark.png';

const now = Date.now();

export const airbnbDb: Template = {
    slug: 'airbnb-database',
    name: 'Airbnb',
    shortDescription: 'Short-term Vacation Rentals',
    description: 'Example database schema diagram for Airbnb',
    image,
    imageDark,
    tags: ['Postgres', 'Example Apps'],
    featured: true,
    diagram: {
        id: 'airbnb_db',
        name: 'airbnb-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '67g91swpcp83lktj2nb28a7dg',
                name: 'reviews',
                schema: 'public',
                x: 811.7949896917703,
                y: 74.30499945746158,
                fields: [
                    {
                        id: 'e5n46eojbyxpg65pb1sesysi2',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7nbmg2bt6dzltr8rfouxctdlc',
                        name: 'reservation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f9kcpflp010xe5ad3rmexla63',
                        name: 'rating',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3znekob0pqusyvdoq14nhlvgo',
                        name: 'comment',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'we00zhlwl1bgaluyvtr4a5184',
                        name: 'reviews_pkey',
                        unique: true,
                        fieldIds: ['e5n46eojbyxpg65pb1sesysi2'],
                        createdAt: now,
                    },
                    {
                        id: 'qkusdk6ftro9q4fax6cm3cpyd',
                        name: 'idx_reviews_reservation_id',
                        unique: false,
                        fieldIds: ['7nbmg2bt6dzltr8rfouxctdlc'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ahasamd4o8ch10i9x5zdwhxlq',
                name: 'user_notifications',
                schema: 'public',
                x: -93.45301553630316,
                y: 877.8699254420417,
                fields: [
                    {
                        id: 'j8g76n6nnmadt6vjoh3wpbvxm',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'atn5gn9aupbavukkaononvmeu',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x45cb34zxmz3erbxc9aq345nd',
                        name: 'notification_text',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'iz2c7dwok2j0f2ffqjx53ebam',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qqq4fa7t03u2ctysxy8m8856p',
                        name: 'read_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'd7y80iw8ndczkivh2ft5215qp',
                        name: 'user_notifications_pkey',
                        unique: true,
                        fieldIds: ['j8g76n6nnmadt6vjoh3wpbvxm'],
                        createdAt: now,
                    },
                    {
                        id: 'awd6ygyvrmbc4xhjot2wew22x',
                        name: 'idx_notifications_user_id',
                        unique: false,
                        fieldIds: ['atn5gn9aupbavukkaononvmeu'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'crnc0wl77gvcbr192m1z5zmxn',
                name: 'users',
                schema: 'public',
                x: 405.24931892542395,
                y: 717.7318639895848,
                fields: [
                    {
                        id: '2fshssi5y6qw26qpeicj5el1i',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'cudvpgbguuaj5otuam7b21os0',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yhw2kyx17wro0hhfrs4ahy1ng',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4xa565norgh1plcishufqkpco',
                        name: 'email_verified_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'whv9xbsxx6oo3qjfthg004x5j',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4o9kgibsu7ydqvdq8smo13qhh',
                        name: 'remember_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'l5790vw2k6q8adzrrtbnw78t7',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6beqartxg38jsv3gbtfbxk4ek',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'adivkq2cmsai0gni3418sld72',
                        name: 'phone_number',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rgqqw4tgfwip7tpjv9w85s6k4',
                        name: 'description',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'p7siokxtxvutpvabcekt4r4p3',
                        name: 'profile_image',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 't34tf6kck2zljg612wizx9qsc',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['2fshssi5y6qw26qpeicj5el1i'],
                        createdAt: now,
                    },
                    {
                        id: 'nzgu4xvd5rr4d8pk5tqfcetgy',
                        name: 'users_email_key',
                        unique: true,
                        fieldIds: ['yhw2kyx17wro0hhfrs4ahy1ng'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'eaddot6l81wm3oh55ryq2nd59',
                name: 'messages',
                schema: 'public',
                x: 883.4278525700333,
                y: 929.4498531199547,
                fields: [
                    {
                        id: '66xp15vzkxg562063guelcbbs',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xrpddzx3w6uzmd5rbo2hgj2yq',
                        name: 'sender_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'r7jycyzy9k4umg9ip1srtphsi',
                        name: 'receiver_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qb2hbsk4gcs3u5gzc3yvgpa7q',
                        name: 'reservation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w4xetghpdnneoakz4usldmngp',
                        name: 'message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jmcwhx29zgjdg25zoeb2crmml',
                        name: 'sent_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dsvq507l38wm5lk2v3hbbura4',
                        name: 'read_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '3ls7hu5r260u7p6vnmupjv7la',
                        name: 'idx_messages_receiver_id',
                        unique: false,
                        fieldIds: ['r7jycyzy9k4umg9ip1srtphsi'],
                        createdAt: now,
                    },
                    {
                        id: '9ovz1rlutpjthw88x259gukj6',
                        name: 'idx_messages_sender_id',
                        unique: false,
                        fieldIds: ['xrpddzx3w6uzmd5rbo2hgj2yq'],
                        createdAt: now,
                    },
                    {
                        id: 'iil51lkygdfj3gv2f6unu70ms',
                        name: 'messages_pkey',
                        unique: true,
                        fieldIds: ['66xp15vzkxg562063guelcbbs'],
                        createdAt: now,
                    },
                    {
                        id: 'i5d1huydjycinio3zh7f1ixus',
                        name: 'idx_messages_reservation_id',
                        unique: false,
                        fieldIds: ['qb2hbsk4gcs3u5gzc3yvgpa7q'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'hp371gd02tc2benhh4nm6uwlr',
                name: 'reviews_media',
                schema: 'public',
                x: 1153.0635598802542,
                y: 74.30499945746163,
                fields: [
                    {
                        id: 'g05hpzkhjhahjmlf6w5wqt82l',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'a25jhoff5sz1ezxvrwfuaf6il',
                        name: 'review_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0uri7e23f6tdh2ygxanb6z9b9',
                        name: 'file_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vt3q0me215r7vz12i2giw935z',
                        name: 'mime_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5otexxit6vrts6mkr5werhfek',
                        name: 'uploaded_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'fm9lj371ash4jkp8xbtto7gch',
                        name: 'reviews_media_pkey',
                        unique: true,
                        fieldIds: ['g05hpzkhjhahjmlf6w5wqt82l'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jfuv0ljqraq4c4k8pyuswymgq',
                name: 'amenities',
                schema: 'public',
                x: -135.70606436478852,
                y: -66.78506629217512,
                fields: [
                    {
                        id: 'w65hsh2k6rwx9x7v19cyihcef',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9kjtmi8flh7q5j6s5k3rf62ox',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'pep6aoj6rpmdthq7nzdjxa08c',
                        name: 'amenities_name_key',
                        unique: true,
                        fieldIds: ['9kjtmi8flh7q5j6s5k3rf62ox'],
                        createdAt: now,
                    },
                    {
                        id: '1v49809bpgwseu9g317zcm82g',
                        name: 'amenities_pkey',
                        unique: true,
                        fieldIds: ['w65hsh2k6rwx9x7v19cyihcef'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'kxsm6yzh6t7yqutakcvn25oq5',
                name: 'room_amenities',
                schema: 'public',
                x: -51.17176841977857,
                y: 120.55039490052002,
                fields: [
                    {
                        id: '85j7g8das058m5zieg8yneuyi',
                        name: 'room_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'l53yf0dqvy0diee0ll9btzrh0',
                        name: 'amenity_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'npp7q6al95d3poayd0cxuwp4q',
                        name: 'room_amenities_pkey',
                        unique: true,
                        fieldIds: [
                            '85j7g8das058m5zieg8yneuyi',
                            'l53yf0dqvy0diee0ll9btzrh0',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'lmf2eeh7dzh4f2bzgnf0imtbk',
                name: 'reservation_promotions',
                schema: 'public',
                x: 386.2078547401868,
                y: -129.75713820681358,
                fields: [
                    {
                        id: 'wkp0f16z64mhavjq2spe63ovd',
                        name: 'reservation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'fbti53ihxwnt4wrvezqppmmh1',
                        name: 'promotion_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hxl2pg8n2iktk90i4w6yzphlb',
                        name: 'discount_amount',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bjelvkz1i4awhheeydlpbbadi',
                        name: 'reservation_promotions_pkey',
                        unique: true,
                        fieldIds: [
                            'wkp0f16z64mhavjq2spe63ovd',
                            'fbti53ihxwnt4wrvezqppmmh1',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'n3zioykgb15g45cmglwakom0i',
                name: 'wishlists',
                schema: 'public',
                x: -97.32786342080158,
                y: -269.2442840091649,
                fields: [
                    {
                        id: 'd4z058k8kq9c21q3imqzux9yk',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'padpzvv08ri8kbeb3ula5oljg',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fex1ui72svwdaatktnxsijwka',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lcud94939nvjpbj4ve7jezlln',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'zjk68zidl3v973mvjdze7eg06',
                        name: 'wishlists_pkey',
                        unique: true,
                        fieldIds: ['d4z058k8kq9c21q3imqzux9yk'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rtt7co0gmshixyhctg7k6mu1z',
                name: 'reservations',
                schema: 'public',
                x: 407.5900410758163,
                y: 258.93479207933024,
                fields: [
                    {
                        id: '4xa8k1sryximotaph1kgze7ei',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'w4lyxvfq8ty1xv6wdzp8fkk8n',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zgvc08lngra0es5p8fgddg9m8',
                        name: 'room_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0hp2kqe40orxloc7mvv4ojobs',
                        name: 'start_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'j7raobudpb68fqlatw6lcx91u',
                        name: 'end_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ucyr78xlv8dtv9ifdxy6xmt38',
                        name: 'price',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'u3dku91igmfbd03lq40ckufy0',
                        name: 'total',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'v202ktxelhoourpuhtmpb3ksa',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'c8nlwg9yv2mheom1c9pnmmczq',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'hkhbmcpl57owxxihvbqxjv55x',
                        name: 'idx_reservations_room_id',
                        unique: false,
                        fieldIds: ['zgvc08lngra0es5p8fgddg9m8'],
                        createdAt: now,
                    },
                    {
                        id: '9iyv79gniabe72x96muex8e7m',
                        name: 'idx_reservations_user_id',
                        unique: false,
                        fieldIds: ['w4lyxvfq8ty1xv6wdzp8fkk8n'],
                        createdAt: now,
                    },
                    {
                        id: 'i6qgpyzdxcmfldfzjr2afgy1u',
                        name: 'reservations_pkey',
                        unique: true,
                        fieldIds: ['4xa8k1sryximotaph1kgze7ei'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'skl03ewy1aw23f2qej81g8rck',
                name: 'promotions',
                schema: 'public',
                x: 771.524997287308,
                y: -195.82999674476952,
                fields: [
                    {
                        id: '8b7a5w9dh1kfisayodrloycyf',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'eqtr81lmtsoyzmq7xu7tq5a7v',
                        name: 'code',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9qpnrgme6eu2syogrbdbd2j55',
                        name: 'discount_percentage',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vmdsyce3oegf6ev4msq8dbvwy',
                        name: 'start_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9d5qshp6clcss26f2rdh2wqhu',
                        name: 'end_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'dl1xpdmy2w9e3vwrvsx177rfh',
                        name: 'promotions_pkey',
                        unique: true,
                        fieldIds: ['8b7a5w9dh1kfisayodrloycyf'],
                        createdAt: now,
                    },
                    {
                        id: '1k2zxpvfwy4481ftpw4scm8dn',
                        name: 'promotions_code_key',
                        unique: true,
                        fieldIds: ['eqtr81lmtsoyzmq7xu7tq5a7v'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'u71uxicd1np31gu1xp6b10da3',
                name: 'media',
                schema: 'public',
                x: -448.15074908567783,
                y: 692.5507056826053,
                fields: [
                    {
                        id: 'o1ap9swacb6gsdrrsukuhh6sg',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8hr6ni5g99p2joy73fq6v09nq',
                        name: 'model_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vcu3vx4hr9zkgq1fuw1p1ct0x',
                        name: 'model_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '71qz2djm7575i62sgnvllz8jg',
                        name: 'file_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ul9bc4mrl3c3kp9ts6jvow0a2',
                        name: 'mime_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sp6f7ib5rj5yeckmmwr8rfnur',
                        name: 'media_pkey',
                        unique: true,
                        fieldIds: ['o1ap9swacb6gsdrrsukuhh6sg'],
                        createdAt: now,
                    },
                    {
                        id: 'r0ltqqzq4eo0vb5ljjyerjs3l',
                        name: 'idx_media_model_type',
                        unique: false,
                        fieldIds: ['vcu3vx4hr9zkgq1fuw1p1ct0x'],
                        createdAt: now,
                    },
                    {
                        id: '2286m9uzl6og2od1tm78r0du5',
                        name: 'idx_media_model_id',
                        unique: false,
                        fieldIds: ['8hr6ni5g99p2joy73fq6v09nq'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vmghhfn9e5pbmp1a7ix418qnk',
                name: 'payments',
                schema: 'public',
                x: 1125.8028661334938,
                y: 529.3419875289997,
                fields: [
                    {
                        id: 'p8moj019diilnb5e6sr6bhead',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pa1ygwlro7ni85jdega7bf0bv',
                        name: 'reservation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jw5bqq0de3tnlrj3elinoirdf',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4jew9bdob4922ri812801osw7',
                        name: 'amount',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qo5k3gjdfpqu326mkp1qcefol',
                        name: 'payment_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lqcmrg01mi52m2gmdgbzergua',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'pp42g9j50w2e0tqlj1lp6bacg',
                        name: 'idx_payments_reservation_id',
                        unique: false,
                        fieldIds: ['pa1ygwlro7ni85jdega7bf0bv'],
                        createdAt: now,
                    },
                    {
                        id: 'a12jvlio20vxh7ygyn0uxb88c',
                        name: 'idx_payments_user_id',
                        unique: false,
                        fieldIds: ['jw5bqq0de3tnlrj3elinoirdf'],
                        createdAt: now,
                    },
                    {
                        id: 'tlv6lciuzyiacd2wi3gciqkgy',
                        name: 'payments_pkey',
                        unique: true,
                        fieldIds: ['p8moj019diilnb5e6sr6bhead'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'yeomzzyhn5plp2ff1fiev73t7',
                name: 'wishlist_rooms',
                schema: 'public',
                x: -522.7131550559509,
                y: -124.38823280250799,
                fields: [
                    {
                        id: 'e1lwuxhf7hzbp275iuh4yqen9',
                        name: 'wishlist_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7o54mgdpg760yz2eijchnz12z',
                        name: 'room_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tz5ubxcfuduky7wygy71m68q7',
                        name: 'wishlist_rooms_pkey',
                        unique: true,
                        fieldIds: [
                            'e1lwuxhf7hzbp275iuh4yqen9',
                            '7o54mgdpg760yz2eijchnz12z',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'yi575aeajymrznf6exkco3z7i',
                name: 'rooms',
                schema: 'public',
                x: -446.61002220467367,
                y: 237.70127294235544,
                fields: [
                    {
                        id: '5fe7d46w9aj0wkm0f7d1i66gm',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'fj8fwxegh151tq4n86itfqsmw',
                        name: 'home_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vx982w22ocqlt25jh69px5hw7',
                        name: 'room_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ssdh5ytq5apnqu765sc8g9vaw',
                        name: 'total_occupancy',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fvrrqk6n9qw2w7sket0nnpstb',
                        name: 'total_bedrooms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8krt1j1qd9mze9yz4hchll1bw',
                        name: 'total_bathrooms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fhboycacgdxw1d1xvcs1gehtd',
                        name: 'summary',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'psj79td4g8gqhbjf7ye14ynig',
                        name: 'address',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3r6f1uqnktqp4exc08yoagg35',
                        name: 'has_tv',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xi2yfcjkw8edhh0rr7dlcs5gm',
                        name: 'has_kitchen',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pmv0d8uznxglzm6mljn385e24',
                        name: 'has_air_con',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'bzqexknzhcuibenbsneykdenx',
                        name: 'has_heating',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'r070rrruloggrbzj987j21hy6',
                        name: 'has_internet',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o3tnxoqebi6l5up56lq287wwq',
                        name: 'price',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kykrcfb32ahw9nb0igg0df3mw',
                        name: 'published_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mid5g38o3eek6q4iktst81wgn',
                        name: 'owner_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6dsi2zg0mr8v7lo9uz8b49da1',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7im40jmlmr6pgkzsdct7zk0vu',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bnpmlpqa97oy92ajvheys2x9o',
                        name: 'latitude',
                        type: {
                            id: 'double_precision',
                            name: 'double precision',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ajrco7hetczchp3dk6sotdgcq',
                        name: 'longitude',
                        type: {
                            id: 'double_precision',
                            name: 'double precision',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ilhw4xqtp8yz4iwrg0g4zyqzz',
                        name: 'idx_rooms_owner_id',
                        unique: false,
                        fieldIds: ['mid5g38o3eek6q4iktst81wgn'],
                        createdAt: now,
                    },
                    {
                        id: 'ciqtmelumvtz72opbluexz2hl',
                        name: 'rooms_pkey',
                        unique: true,
                        fieldIds: ['5fe7d46w9aj0wkm0f7d1i66gm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '1awmiqzisfutul4xcydk5wfuc',
                name: 'reviews_media_review_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hp371gd02tc2benhh4nm6uwlr',
                targetTableId: '67g91swpcp83lktj2nb28a7dg',
                sourceFieldId: 'a25jhoff5sz1ezxvrwfuaf6il',
                targetFieldId: 'e5n46eojbyxpg65pb1sesysi2',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2snky4779xdqqh8jkcat52ndk',
                name: 'reservation_promotions_promotion_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'lmf2eeh7dzh4f2bzgnf0imtbk',
                targetTableId: 'skl03ewy1aw23f2qej81g8rck',
                sourceFieldId: 'fbti53ihxwnt4wrvezqppmmh1',
                targetFieldId: '8b7a5w9dh1kfisayodrloycyf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6uww2cpjlmjltwxtbsi23kzdy',
                name: 'reservation_promotions_reservation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'lmf2eeh7dzh4f2bzgnf0imtbk',
                targetTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                sourceFieldId: 'wkp0f16z64mhavjq2spe63ovd',
                targetFieldId: '4xa8k1sryximotaph1kgze7ei',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '7vr7zvem9eypnhh634pxifl1d',
                name: 'payments_reservation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vmghhfn9e5pbmp1a7ix418qnk',
                targetTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                sourceFieldId: 'pa1ygwlro7ni85jdega7bf0bv',
                targetFieldId: '4xa8k1sryximotaph1kgze7ei',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '8h390eo8hmi8j88odd30xj9cy',
                name: 'rooms_owner_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'yi575aeajymrznf6exkco3z7i',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'mid5g38o3eek6q4iktst81wgn',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'aiwac7rz9wg6eytv4g5420cs7',
                name: 'reservations_room_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                targetTableId: 'yi575aeajymrznf6exkco3z7i',
                sourceFieldId: 'zgvc08lngra0es5p8fgddg9m8',
                targetFieldId: '5fe7d46w9aj0wkm0f7d1i66gm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'bp8tt2rqerap863wdca11zu0g',
                name: 'wishlist_rooms_wishlist_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'yeomzzyhn5plp2ff1fiev73t7',
                targetTableId: 'n3zioykgb15g45cmglwakom0i',
                sourceFieldId: 'e1lwuxhf7hzbp275iuh4yqen9',
                targetFieldId: 'd4z058k8kq9c21q3imqzux9yk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'c162y8pjwsobspf3lx3wo0tl9',
                name: 'reservations_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'w4lyxvfq8ty1xv6wdzp8fkk8n',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'cjqrfdf1q4szco001t7upicoq',
                name: 'messages_reservation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'eaddot6l81wm3oh55ryq2nd59',
                targetTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                sourceFieldId: 'qb2hbsk4gcs3u5gzc3yvgpa7q',
                targetFieldId: '4xa8k1sryximotaph1kgze7ei',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'epe7q1qn1bbnq79lnlvo0cd5v',
                name: 'wishlists_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'n3zioykgb15g45cmglwakom0i',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'padpzvv08ri8kbeb3ula5oljg',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'f98l4vujzmdoscbl19nd0mj99',
                name: 'room_amenities_room_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kxsm6yzh6t7yqutakcvn25oq5',
                targetTableId: 'yi575aeajymrznf6exkco3z7i',
                sourceFieldId: '85j7g8das058m5zieg8yneuyi',
                targetFieldId: '5fe7d46w9aj0wkm0f7d1i66gm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'irxqkp2yhskf1dn8tqlj4njnk',
                name: 'user_notifications_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ahasamd4o8ch10i9x5zdwhxlq',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'atn5gn9aupbavukkaononvmeu',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'k2ojuhsd22w14d1y7k2907xji',
                name: 'payments_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vmghhfn9e5pbmp1a7ix418qnk',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'jw5bqq0de3tnlrj3elinoirdf',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ljlsu897gohocl8wf0ilma0a2',
                name: 'reviews_reservation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '67g91swpcp83lktj2nb28a7dg',
                targetTableId: 'rtt7co0gmshixyhctg7k6mu1z',
                sourceFieldId: '7nbmg2bt6dzltr8rfouxctdlc',
                targetFieldId: '4xa8k1sryximotaph1kgze7ei',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'njmedosc67xgbe8wf2quolyte',
                name: 'room_amenities_amenity_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kxsm6yzh6t7yqutakcvn25oq5',
                targetTableId: 'jfuv0ljqraq4c4k8pyuswymgq',
                sourceFieldId: 'l53yf0dqvy0diee0ll9btzrh0',
                targetFieldId: 'w65hsh2k6rwx9x7v19cyihcef',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'qa6lzs07ns0wzyymobvyybacc',
                name: 'messages_sender_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'eaddot6l81wm3oh55ryq2nd59',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'xrpddzx3w6uzmd5rbo2hgj2yq',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tk4t3ubrq246xkv9inio8dx4b',
                name: 'messages_receiver_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'eaddot6l81wm3oh55ryq2nd59',
                targetTableId: 'crnc0wl77gvcbr192m1z5zmxn',
                sourceFieldId: 'r7jycyzy9k4umg9ip1srtphsi',
                targetFieldId: '2fshssi5y6qw26qpeicj5el1i',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'uwmv3a4zoblbushox66gr27q0',
                name: 'wishlist_rooms_room_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'yeomzzyhn5plp2ff1fiev73t7',
                targetTableId: 'yi575aeajymrznf6exkco3z7i',
                sourceFieldId: '7o54mgdpg760yz2eijchnz12z',
                targetFieldId: '5fe7d46w9aj0wkm0f7d1i66gm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
