import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/canvas-db.png';
import imageDark from '@/assets/templates/canvas-db-dark.png';

const now = Date.now();

export const canvasDb: Template = {
    slug: 'canvas-database',
    name: 'Canvas',
    shortDescription: 'Publishing on your own terms',
    description:
        'A simple, open source extend your existing Laravel application and get you up-and-running with a blog in just a few minutes.',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://github.com/austintoddj/canvas',
    diagram: {
        id: 'canvas_db',
        name: 'canvas-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '1036n2uhrd3e9vydlf26z9g7q',
                name: 'canvas_posts_topics',
                schema: 'public',
                x: 781.0231299278557,
                y: 669.6825280193192,
                fields: [
                    {
                        id: 'fhwlpd8w33hobomelorttw9tj',
                        name: 'post_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tsd8jzjwcmfw6mx5jer3whbph',
                        name: 'topic_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '25mjdadwkpffg0e9590f4y16w',
                        name: 'canvas_posts_topics_post_id_topic_id_unique',
                        unique: true,
                        fieldIds: [
                            'fhwlpd8w33hobomelorttw9tj',
                            'tsd8jzjwcmfw6mx5jer3whbph',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5xwa6smxaoukrdo6g2e19nskt',
                name: 'users',
                schema: 'public',
                x: 730.7548246927765,
                y: 231.3642712247439,
                fields: [
                    {
                        id: '1nv304nagqmk8a01qgm8ghdmm',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ciza8eyl53g1goacncp93e8vy',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qzpmc3xjhw23d73cadadb1ozn',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rqq5qwf4p9d3x3mtvydimloei',
                        name: 'email_verified_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'offrjkr13nazmlgh9elxzae39',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nys8tpb5w0th3ur2a9wj9bv59',
                        name: 'remember_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'z2xzqa6lurpwoeiqkean8rdfa',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dvac9q5ctgq3kmebn2o8a13g2',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'nqp42b8s3wo0zu7so4joyb98x',
                        name: 'users_email_unique',
                        unique: true,
                        fieldIds: ['qzpmc3xjhw23d73cadadb1ozn'],
                        createdAt: now,
                    },
                    {
                        id: 'nph7qdsk1091nhvo7fclbc1ls',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['1nv304nagqmk8a01qgm8ghdmm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'gpzadn5qm3mx6jotmjgpu8htc',
                name: 'canvas_posts',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'x0y13niv8biq1ak1zoglm6fvi',
                        name: 'id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '1zmnya1d85gksdyt8742t3lbs',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9nxqq9vkbtv7l889tl87d0bpf',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lv36rainmlib6eqk8ap4wfo9t',
                        name: 'summary',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o3vcqg4uebkluvhcjy6cnmuv5',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sjnm2biaejyxnoy1bcbcv03xh',
                        name: 'published_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7kisl6d3lygky70d0fbovq9lc',
                        name: 'featured_image',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zzdd3opqp6co2a17zr49g5ppg',
                        name: 'featured_image_caption',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6hmnwaur8d0s2wpgdo6sccok3',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'e6lyhjoudpy4188gagz2dsd04',
                        name: 'meta',
                        type: {
                            id: 'json',
                            name: 'json',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uqoms2dp83n25kpt74izuwqv3',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zqhyvmdl3u9yifta5ix8du66v',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'seo6rh5chhw21ialsfvqrgfzw',
                        name: 'deleted_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4vpvvjftxyk9jhbozgws557rv',
                        name: 'canvas_posts_slug_user_id_unique',
                        unique: true,
                        fieldIds: [
                            '1zmnya1d85gksdyt8742t3lbs',
                            '6hmnwaur8d0s2wpgdo6sccok3',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'mmvgnwdm8uavgw4u0cvbpnbif',
                        name: 'canvas_posts_user_id_index',
                        unique: false,
                        fieldIds: ['6hmnwaur8d0s2wpgdo6sccok3'],
                        createdAt: now,
                    },
                    {
                        id: 'zvws6jn6245yw352tuc0utdpa',
                        name: 'canvas_posts_pkey',
                        unique: true,
                        fieldIds: ['x0y13niv8biq1ak1zoglm6fvi'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'iide3o2zr3cbfno06ybiepksi',
                name: 'canvas_views',
                schema: 'public',
                x: 512.6081944444154,
                y: -376.8627082318162,
                fields: [
                    {
                        id: 'uxyx4dl5s6z110zpg8i8x7r6o',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'oamdcg0otmd1ay9u5s9gjsxq3',
                        name: 'post_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7001koh5z398wvhl9r9fs0ofx',
                        name: 'ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '95x1eme6vkztws5at4y5wrkmu',
                        name: 'agent',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'usqep9g1eg7r3uzeya23o7ylv',
                        name: 'referer',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zrz0uwma9wgh8i01olfct6qzy',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lah5uz5ow7n2pvadpy5xfeeh0',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'p59iuhmlbt757r83hw41383x1',
                        name: 'canvas_views_created_at_index',
                        unique: false,
                        fieldIds: ['zrz0uwma9wgh8i01olfct6qzy'],
                        createdAt: now,
                    },
                    {
                        id: 'ava38h63ynadth3y2o2y28l4t',
                        name: 'canvas_views_post_id_index',
                        unique: false,
                        fieldIds: ['oamdcg0otmd1ay9u5s9gjsxq3'],
                        createdAt: now,
                    },
                    {
                        id: 'rk3e3cvk1ogo7518766qktphc',
                        name: 'canvas_views_pkey',
                        unique: true,
                        fieldIds: ['uxyx4dl5s6z110zpg8i8x7r6o'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ncirb4xdc32o0mwjwzytcp416',
                name: 'canvas_posts_tags',
                schema: 'public',
                x: 520,
                y: -60,
                fields: [
                    {
                        id: 'dfuimnqjpwl68zflelvzwmgxf',
                        name: 'tag_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'diauddisg9mnphj140hw5k5ym',
                        name: 'post_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'e625fqpc0zmmxdmzerwe0bzfl',
                        name: 'canvas_posts_tags_post_id_tag_id_unique',
                        unique: true,
                        fieldIds: [
                            'diauddisg9mnphj140hw5k5ym',
                            'dfuimnqjpwl68zflelvzwmgxf',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ovevnjzoigctv3dutsxan190o',
                name: 'canvas_visits',
                schema: 'public',
                x: 91.66745318940627,
                y: -282.63337066119425,
                fields: [
                    {
                        id: '6vvv572e003po9n7ie13y23bf',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4mrfv6tuaztwcryj17132ix6r',
                        name: 'post_id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lk15xv28nncv6ctaf202umv3s',
                        name: 'ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zaamgq75pfe4d3q03c2lghdfj',
                        name: 'agent',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8hfj04tk2f5zgl06i83klq4o5',
                        name: 'referer',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8s0iop4ybulq1w7zwufbz4r7y',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w81rnyabax7b5sibu5amo8em0',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xvlbhfyx0my40ajun6szt2tzg',
                        name: 'canvas_visits_pkey',
                        unique: true,
                        fieldIds: ['6vvv572e003po9n7ie13y23bf'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'uwehb077txcxeqkhv97hujbex',
                name: 'canvas_topics',
                schema: 'public',
                x: 1188.3403694589679,
                y: 448.93108809154444,
                fields: [
                    {
                        id: 'e9f661z3ajm6vc2hx6mamcors',
                        name: 'id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kesn93ygn92k45dx11tvhbh9d',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kl0ro5wchfewz6liz7oh2th6w',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sth033xoe10qffjcc73gfov17',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'okdes9su8kfo9yrrcmsdemeii',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'n5a10udc9b8vqew1u82i20gas',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9hpf0v45z9k6d81qnckkwpkux',
                        name: 'deleted_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'e8cwi9lq7qfirbw9i5lpl4yuf',
                        name: 'canvas_topics_user_id_index',
                        unique: false,
                        fieldIds: ['sth033xoe10qffjcc73gfov17'],
                        createdAt: now,
                    },
                    {
                        id: '5dd0rh0a64hkl5hkmyi3kbc8a',
                        name: 'canvas_topics_slug_user_id_unique',
                        unique: true,
                        fieldIds: [
                            'kesn93ygn92k45dx11tvhbh9d',
                            'sth033xoe10qffjcc73gfov17',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'iimiysue67n6ecwcznbuwbb42',
                        name: 'canvas_topics_created_at_index',
                        unique: false,
                        fieldIds: ['okdes9su8kfo9yrrcmsdemeii'],
                        createdAt: now,
                    },
                    {
                        id: '8yi15kli2hw55cl64zjcu46y7',
                        name: 'canvas_topics_pkey',
                        unique: true,
                        fieldIds: ['e9f661z3ajm6vc2hx6mamcors'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xyf5m4fnsxoincpi4awmkmxd1',
                name: 'canvas_tags',
                schema: 'public',
                x: 928.4622587653612,
                y: -261.2517458680456,
                fields: [
                    {
                        id: 'qrhlkoa6d2hg7d0mevn3aras3',
                        name: 'id',
                        type: {
                            id: 'character',
                            name: 'character',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '24e272fkgpkwyphbopj7ysbvg',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gr39zqf3qfm9hq9r2tbfgw7uz',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rxcacuumalld6p0jy60by1fpa',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'son9xgckjjm0g0qizsronu3jd',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zfmt1zw89cwh4qw647w8l71w1',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j8ydw0maa3qlxed3i5sarf8br',
                        name: 'deleted_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5deaydgkhsmc5e8ozwn6bqafh',
                        name: 'canvas_tags_slug_user_id_unique',
                        unique: true,
                        fieldIds: [
                            '24e272fkgpkwyphbopj7ysbvg',
                            'rxcacuumalld6p0jy60by1fpa',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '27ba2dh6ou8ed0dzzi4ufw08x',
                        name: 'canvas_tags_user_id_index',
                        unique: false,
                        fieldIds: ['rxcacuumalld6p0jy60by1fpa'],
                        createdAt: now,
                    },
                    {
                        id: 'l3ddstoogmu6eo6ky5qm2o7p0',
                        name: 'canvas_tags_created_at_index',
                        unique: false,
                        fieldIds: ['son9xgckjjm0g0qizsronu3jd'],
                        createdAt: now,
                    },
                    {
                        id: 'i2bxvfqhq7zi9dzqvu988edn0',
                        name: 'canvas_tags_pkey',
                        unique: true,
                        fieldIds: ['qrhlkoa6d2hg7d0mevn3aras3'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'y1p8d5ws68urgi9ph9cklc2m1',
                name: 'canvas_user_meta',
                schema: 'public',
                x: 1325.6118270094798,
                y: -59.82652999010497,
                fields: [
                    {
                        id: 'mp5l57l8614xq7iy1f129dpgu',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'cypru4jaldrqgnnxg1cny9vii',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3rvybnhy2vuqibcfpoktpcaf9',
                        name: 'username',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i6k8y025obgy7sizsxis02fkm',
                        name: 'summary',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '91vu6mey8jj25zutewzftbtwy',
                        name: 'avatar',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jzhd12j45j4iehxtbr9tkvmhz',
                        name: 'dark_mode',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w6oi9cyi0el5n711kr98nw2kh',
                        name: 'digest',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'it3fnf1j4z8hjaixr57304c6n',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'p9eg12tl3vh7u9kyuebbnwcp6',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g15xjuuij9wreoga2c06ywar0',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '8xkj8h1ughb9lp3h5x8ujyk2j',
                        name: 'canvas_user_meta_user_id_unique',
                        unique: true,
                        fieldIds: ['cypru4jaldrqgnnxg1cny9vii'],
                        createdAt: now,
                    },
                    {
                        id: 'gs3wkqexghdui0bi6gvbnjyc6',
                        name: 'canvas_user_meta_username_unique',
                        unique: true,
                        fieldIds: ['3rvybnhy2vuqibcfpoktpcaf9'],
                        createdAt: now,
                    },
                    {
                        id: 'zjxh74zdiibeam0h94rm6jg86',
                        name: 'canvas_user_meta_pkey',
                        unique: true,
                        fieldIds: ['mp5l57l8614xq7iy1f129dpgu'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '0oeah7mzasi23thsx3xn0ed81',
                name: 'canvas_posts_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'gpzadn5qm3mx6jotmjgpu8htc',
                targetTableId: '5xwa6smxaoukrdo6g2e19nskt',
                sourceFieldId: '6hmnwaur8d0s2wpgdo6sccok3',
                targetFieldId: '1nv304nagqmk8a01qgm8ghdmm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2p2sb1ssqjvsbq812m7h0vf97',
                name: 'canvas_user_meta_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'y1p8d5ws68urgi9ph9cklc2m1',
                targetTableId: '5xwa6smxaoukrdo6g2e19nskt',
                sourceFieldId: 'cypru4jaldrqgnnxg1cny9vii',
                targetFieldId: '1nv304nagqmk8a01qgm8ghdmm',
                sourceCardinality: 'one',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5utm4qfn4x8qohn5ykwum5eu7',
                name: 'canvas_tags_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xyf5m4fnsxoincpi4awmkmxd1',
                targetTableId: '5xwa6smxaoukrdo6g2e19nskt',
                sourceFieldId: 'rxcacuumalld6p0jy60by1fpa',
                targetFieldId: '1nv304nagqmk8a01qgm8ghdmm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '66qirqfe18tjg2qmxbxht4jhm',
                name: 'canvas_visits_post_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ovevnjzoigctv3dutsxan190o',
                targetTableId: 'gpzadn5qm3mx6jotmjgpu8htc',
                sourceFieldId: '4mrfv6tuaztwcryj17132ix6r',
                targetFieldId: 'x0y13niv8biq1ak1zoglm6fvi',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'aws5a2liece7gkr5ju64vvpei',
                name: 'canvas_posts_tags_tag_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ncirb4xdc32o0mwjwzytcp416',
                targetTableId: 'xyf5m4fnsxoincpi4awmkmxd1',
                sourceFieldId: 'dfuimnqjpwl68zflelvzwmgxf',
                targetFieldId: 'qrhlkoa6d2hg7d0mevn3aras3',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'g8l06m7u2tcc6vo5950zhkxf1',
                name: 'canvas_views_post_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'iide3o2zr3cbfno06ybiepksi',
                targetTableId: 'gpzadn5qm3mx6jotmjgpu8htc',
                sourceFieldId: 'oamdcg0otmd1ay9u5s9gjsxq3',
                targetFieldId: 'x0y13niv8biq1ak1zoglm6fvi',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hvhh9uoagz4arkdvkr93tgns5',
                name: 'canvas_topics_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'uwehb077txcxeqkhv97hujbex',
                targetTableId: '5xwa6smxaoukrdo6g2e19nskt',
                sourceFieldId: 'sth033xoe10qffjcc73gfov17',
                targetFieldId: '1nv304nagqmk8a01qgm8ghdmm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'k9kdmrlb7me0qf44rev7gpuy5',
                name: 'canvas_posts_tags_post_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ncirb4xdc32o0mwjwzytcp416',
                targetTableId: 'gpzadn5qm3mx6jotmjgpu8htc',
                sourceFieldId: 'diauddisg9mnphj140hw5k5ym',
                targetFieldId: 'x0y13niv8biq1ak1zoglm6fvi',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'l1sendu65brach1zzwoz3jw3l',
                name: 'canvas_posts_topics_topic_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '1036n2uhrd3e9vydlf26z9g7q',
                targetTableId: 'uwehb077txcxeqkhv97hujbex',
                sourceFieldId: 'tsd8jzjwcmfw6mx5jer3whbph',
                targetFieldId: 'e9f661z3ajm6vc2hx6mamcors',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'y3fcflr0szdgg1cui3yrlxwxn',
                name: 'canvas_posts_topics_post_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '1036n2uhrd3e9vydlf26z9g7q',
                targetTableId: 'gpzadn5qm3mx6jotmjgpu8htc',
                sourceFieldId: 'fhwlpd8w33hobomelorttw9tj',
                targetFieldId: 'x0y13niv8biq1ak1zoglm6fvi',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
