import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/comfortable-mexican-sofa-db.png';
import imageDark from '@/assets/templates/comfortable-mexican-sofa-db-dark.png';

const now = Date.now();

export const comfortableMexicanSofaDb: Template = {
    slug: 'comfortable-mexican-sofa-database',
    name: 'Comfortable Mexican Sofa',
    shortDescription: 'Rails CMS - ComfortableMexicanSofa',
    description:
        'A powerful Ruby on Rails 5.2+ CMS (Content Management System) Engine',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Rails', 'CMS'],
    featured: false,
    url: 'https://github.com/comfy/comfortable-mexican-sofa',
    diagram: {
        id: 'comfortable_mexican_sofa_db',
        name: 'comfortable-mexican-sofa-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '1i1n19xwucw76ftnnid8z7t2o',
                name: 'comfy_cms_sites',
                schema: 'public',
                x: 607.203068634559,
                y: 205.91655420936638,
                fields: [
                    {
                        id: 'a2hyi3q08x3a1hp394ebbb66h',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('comfy_cms_sites_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '8bxj4xa6rywvosk8ekofzaz35',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nbtc2wglf8xkl7znqie3at6h7',
                        name: 'identifier',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7nk84w17fgjfcn84qyp4vqhj4',
                        name: 'hostname',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xvubpmmhixw5cs46zgakqr36r',
                        name: 'path',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mqpx5e62hvz8m2plgyyhp6a2t',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0h85xog67px24oqmzhib6yfbz',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9xilgpouep3ilbgvcqsz6i8xt',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vugnpzdi7bf2cfrt7113l2n4v',
                        name: 'comfy_cms_sites_identifier_key',
                        unique: true,
                        fieldIds: ['nbtc2wglf8xkl7znqie3at6h7'],
                        createdAt: now,
                    },
                    {
                        id: '8vh92c3er6lelsm0j1pgbrje3',
                        name: 'comfy_cms_sites_pkey',
                        unique: true,
                        fieldIds: ['a2hyi3q08x3a1hp394ebbb66h'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '4gz554fu1is9nn8kokdv8k8lw',
                name: 'comfy_cms_files',
                schema: 'public',
                x: 1020.2260896719633,
                y: -330.5225130514104,
                fields: [
                    {
                        id: 'hsm3jnswoloro6813a5p5uuex',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('comfy_cms_files_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'kemt4iwpzt3qf6gtfaf8zr3av',
                        name: 'site_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'e2nr7ks3slw8yztccnh06f1m7',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'w7c6tok6nwealgzyk6khrfq0y',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'l3htahdq7e4gssdxnplb884de',
                        name: 'position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's9nl9d8uwtjrdihqzvqhj6qm6',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g4yoyg2v5zraqq81ukwx0u8xa',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ys5r9nrnwa8vff42mw0ftuo8l',
                        name: 'comfy_cms_files_pkey',
                        unique: true,
                        fieldIds: ['hsm3jnswoloro6813a5p5uuex'],
                        createdAt: now,
                    },
                    {
                        id: '8h1j1qttxran6h04gfvkpqzh7',
                        name: 'idx_comfy_cms_files',
                        unique: false,
                        fieldIds: [
                            'kemt4iwpzt3qf6gtfaf8zr3av',
                            'l3htahdq7e4gssdxnplb884de',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'rtz0dwod40zqc4agv0semgyyj',
                        name: 'comfy_cms_files_site_id_position_key',
                        unique: true,
                        fieldIds: [
                            'kemt4iwpzt3qf6gtfaf8zr3av',
                            'l3htahdq7e4gssdxnplb884de',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6m12iicr5bmvmjh7vc4nnxwx4',
                name: 'comfy_cms_snippets',
                schema: 'public',
                x: 555.1477368632752,
                y: -228.3031264459148,
                fields: [
                    {
                        id: 'uvy743vegv4khu0lorjnvbyiw',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_snippets_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '5ma4bqfgltiom4f52uy265ahr',
                        name: 'site_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'n8nqm3k04418heznsuiw62ckd',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'k8m4pz4gn8cjgn3fgso3yybc6',
                        name: 'identifier',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ktpth3ljnbjjhmveit45v6q4j',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'e6gzbg1dwy39n3uvgxdkvjwsd',
                        name: 'position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'b7uxypx2zgdkz87j1bucw56dy',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dpfauggf6mb8v97qft1cp84g7',
                        name: 'updated_at',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ugtajh55einv0w1as32k8ri0p',
                        name: 'idx_comfy_cms_snippets',
                        unique: false,
                        fieldIds: [
                            '5ma4bqfgltiom4f52uy265ahr',
                            'k8m4pz4gn8cjgn3fgso3yybc6',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'k1z087zzwq0ku42plzsahvgkn',
                        name: 'comfy_cms_snippets_site_id_identifier_key',
                        unique: true,
                        fieldIds: [
                            '5ma4bqfgltiom4f52uy265ahr',
                            'k8m4pz4gn8cjgn3fgso3yybc6',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'r8rriohbeqg3fco25fcl3vfjb',
                        name: 'comfy_cms_snippets_pkey',
                        unique: true,
                        fieldIds: ['uvy743vegv4khu0lorjnvbyiw'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bpeqtu17nlds7fk9qt6ouax09',
                name: 'comfy_cms_revisions',
                schema: 'public',
                x: -41.43747739370838,
                y: -418.7551568493834,
                fields: [
                    {
                        id: 'vwjv1tpj9swhqpl0sp4yku2xa',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_revisions_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '53owojbphqee657dnec46qj4n',
                        name: 'record_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'iflix9rs1nr0vwdxer4pl15bv',
                        name: 'record_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jom8gfntmivq3rdqjxthm02e7',
                        name: 'data',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qxgj8m7fqil2r4hee3cdxhpym',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'f2rts3fagxrer5s08cvxvbab7',
                        name: 'comfy_cms_revisions_record_type_record_id_created_at_key',
                        unique: true,
                        fieldIds: [
                            '53owojbphqee657dnec46qj4n',
                            'iflix9rs1nr0vwdxer4pl15bv',
                            'qxgj8m7fqil2r4hee3cdxhpym',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'qlwz0yr1dd6tuk856dfc50hhu',
                        name: 'comfy_cms_revisions_pkey',
                        unique: true,
                        fieldIds: ['vwjv1tpj9swhqpl0sp4yku2xa'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'cyfncpo2zosklocsicymvl4g2',
                name: 'comfy_cms_categorizations',
                schema: 'public',
                x: 1331.039770672155,
                y: -169.01134582534618,
                fields: [
                    {
                        id: '80xj3jejisj80x7c36jiq7jkk',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_categorizations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '31nek4b2kuigij52w2r11h9g8',
                        name: 'category_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i8pknlei7jbvml67hcgkppkv4',
                        name: 'categorized_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5efokkfv8xj0ezihwq9vwld6k',
                        name: 'categorized_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4hkdkoibh879kpg5ixcgcval8',
                        name: 'comfy_cms_categorizations_category_id_categorized_type_cate_key',
                        unique: true,
                        fieldIds: [
                            '31nek4b2kuigij52w2r11h9g8',
                            'i8pknlei7jbvml67hcgkppkv4',
                            '5efokkfv8xj0ezihwq9vwld6k',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '6w0y2wxbz70w78gntc2doram3',
                        name: 'idx_comfy_cms_categorizations',
                        unique: false,
                        fieldIds: [
                            '31nek4b2kuigij52w2r11h9g8',
                            'i8pknlei7jbvml67hcgkppkv4',
                            '5efokkfv8xj0ezihwq9vwld6k',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '4l1axse9ewvlff6iwc72nfa4a',
                        name: 'comfy_cms_categorizations_pkey',
                        unique: true,
                        fieldIds: ['80xj3jejisj80x7c36jiq7jkk'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'e5834gyvmwro9zxtg3b5cw3bz',
                name: 'comfy_cms_pages',
                schema: 'public',
                x: 662.6829427804548,
                y: 668.0517088348578,
                fields: [
                    {
                        id: 'y8j19xae7nn91wn0m7aebp5h0',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('comfy_cms_pages_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'fa381qe39zwfs3bkhb99lfs9f',
                        name: 'site_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'du2trf4cbs0tsezfdwymoavhp',
                        name: 'layout_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uxc4pj43vq7pdr1eikkgqxmus',
                        name: 'parent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fpmprec23i7bkqqa1xqtkrvzh',
                        name: 'target_page_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1k2yq61cqrs8kso303vrw4ome',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fe1ytks9wbi9fddf47op5h9r8',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'iwn2e2bqt9t87vean88uoy5p5',
                        name: 'full_path',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm7p3cagtdjefx06u4vrib6v14',
                        name: 'content_cache',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'z9soyv27f3xolxv0801vi7dgq',
                        name: 'is_published',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'bwyl6de3l5lbxfh3wy2y8hw8x',
                        name: 'position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kjln20azmmcynt6wy14l8hsl2',
                        name: 'children_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'lzc9npr5qp2ynj2vw7afz9rty',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '88xuyadd1wdfw73fwrh9zf45c',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vo15t1ws5xln7bt5ixnqfm9sg',
                        name: 'idx_comfy_cms_pages_full_path',
                        unique: false,
                        fieldIds: [
                            'fa381qe39zwfs3bkhb99lfs9f',
                            'iwn2e2bqt9t87vean88uoy5p5',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'c4amy2sqghpq7nrfcgke6mm2v',
                        name: 'comfy_cms_pages_slug_key',
                        unique: true,
                        fieldIds: ['fe1ytks9wbi9fddf47op5h9r8'],
                        createdAt: now,
                    },
                    {
                        id: 'ujw1dat9o1mjrkjms3f55nw2c',
                        name: 'comfy_cms_pages_site_id_full_path_key',
                        unique: true,
                        fieldIds: [
                            'fa381qe39zwfs3bkhb99lfs9f',
                            'iwn2e2bqt9t87vean88uoy5p5',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'rq35dpca7famqkzmsyylxcpol',
                        name: 'comfy_cms_pages_pkey',
                        unique: true,
                        fieldIds: ['y8j19xae7nn91wn0m7aebp5h0'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jpvv0pdp82w3vvpmdi9yu79ef',
                name: 'comfy_cms_fragments',
                schema: 'public',
                x: 1125.8068396463786,
                y: 506.880687983534,
                fields: [
                    {
                        id: 'm0s6k37m1oom3wihysdnj3imt',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_fragments_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 't388xy2ksn68e3dqg689itbv1',
                        name: 'recordable_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'y3u0b8fi951vpj3zob1tpjqzj',
                        name: 'recordable_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5kftfbvqps0segb7chn4p1sxl',
                        name: 'identifier',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pbzkl3drt5citimcz5ud6l4ee',
                        name: 'tag',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'k7cptmkwjjrn1hzpwa8kxwgzx',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '60v7n5m6s9nnoa88u9watqx5t',
                        name: 'boolean',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't2k02w621znunzmb9eb364o9m',
                        name: 'datetime',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6n2qcdgxfeerac0rx713p6db8',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a3313v4ymwp4kc2om16yv2bug',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'dl6cyf8yqgwi6zxkknnqqlihu',
                        name: 'comfy_cms_fragments_pkey',
                        unique: true,
                        fieldIds: ['m0s6k37m1oom3wihysdnj3imt'],
                        createdAt: now,
                    },
                    {
                        id: 'a8bfgynwe32gw61wk9zu26izz',
                        name: 'idx_comfy_cms_fragments',
                        unique: false,
                        fieldIds: [
                            't388xy2ksn68e3dqg689itbv1',
                            'y3u0b8fi951vpj3zob1tpjqzj',
                            '5kftfbvqps0segb7chn4p1sxl',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'vb4ynhwszf6l38zu9wtx2r78i',
                        name: 'comfy_cms_fragments_recordable_id_recordable_type_identifie_key',
                        unique: true,
                        fieldIds: [
                            't388xy2ksn68e3dqg689itbv1',
                            'y3u0b8fi951vpj3zob1tpjqzj',
                            '5kftfbvqps0segb7chn4p1sxl',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'knry1hxcqwwa09vnlpyunt6a8',
                name: 'comfy_cms_layouts',
                schema: 'public',
                x: -417.3295112025886,
                y: -0.01703883250047511,
                fields: [
                    {
                        id: 'vvpb6i0zl180z0xtkbkmbt8zq',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_layouts_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'g5f55dk6u10i0e8twlopis5yn',
                        name: 'site_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7lg3lic3upf5opwjhorqve3n7',
                        name: 'parent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nypj8f9ge4by4pds1jskvpj09',
                        name: 'app_layout',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cb7bkgpw11yjvz64pi91jqcmh',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wgr37zn8b6j31whn35jisbnfp',
                        name: 'identifier',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bjzpv4r293wagif7rs7vtbs6j',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'r9dzwl2pkctxvoey4gjo85ibv',
                        name: 'css',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sb4t7nwxx2dl16oseryk7jdd1',
                        name: 'js',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uqdj1ajkrrf2zlm48a9pg0r3y',
                        name: 'position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'n3yv8vh9zad5zgpyjiri2zz64',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vad7ga2i4i6r5155127awywsb',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'audt2e5o01r0gak8oxbg2zvb0',
                        name: 'comfy_cms_layouts_site_id_identifier_key',
                        unique: true,
                        fieldIds: [
                            'g5f55dk6u10i0e8twlopis5yn',
                            'wgr37zn8b6j31whn35jisbnfp',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'pahvbcuq0isyvr105qf4eopra',
                        name: 'idx_comfy_cms_layouts',
                        unique: false,
                        fieldIds: [
                            'g5f55dk6u10i0e8twlopis5yn',
                            'wgr37zn8b6j31whn35jisbnfp',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'cxopbq1wyvbfg0fhcjad7w8pn',
                        name: 'comfy_cms_layouts_pkey',
                        unique: true,
                        fieldIds: ['vvpb6i0zl180z0xtkbkmbt8zq'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'og53dwps4q7txai0egunnh6zb',
                name: 'comfy_cms_translations',
                schema: 'public',
                x: -93.51741252208262,
                y: 488.71081161796053,
                fields: [
                    {
                        id: 'vcf3qw3w08vbi1y3giku8jjbd',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_translations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'mhn2bonfsd00rqia8lb7xbe62',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'm92nfn5papv27p2dx5zxaalkp',
                        name: 'layout_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'd8cm7femomjqul6q7ivzj9ehi',
                        name: 'page_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'laz84kf43o2k9dao2k31f4z7h',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8z5ahzbm6vcmxh333kkw6pnou',
                        name: 'content_cache',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'c5ir6j00habaly8w7r9ec3007',
                        name: 'is_published',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'zelme1en34qemwre4i9k8cnmr',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xva9vjrgao3cbgaaqqer26xnc',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tldm4evjlx0h2bfr0onc03ys2',
                        name: 'idx_comfy_cms_translations',
                        unique: false,
                        fieldIds: [
                            'mhn2bonfsd00rqia8lb7xbe62',
                            'm92nfn5papv27p2dx5zxaalkp',
                            'd8cm7femomjqul6q7ivzj9ehi',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'nf9dzxg2ciy86qq9o24bbk24i',
                        name: 'comfy_cms_translations_pkey',
                        unique: true,
                        fieldIds: ['vcf3qw3w08vbi1y3giku8jjbd'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 's88553ow908alh5oai78mda7r',
                name: 'comfy_cms_categories',
                schema: 'public',
                x: 1379.3920137143991,
                y: 200.01703883250048,
                fields: [
                    {
                        id: '76g8ntmzax7x5la7tjh1nc81e',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('comfy_cms_categories_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '9wzko2usjtxzmtha8iwjtyh36',
                        name: 'site_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dhvm5i7whcc1shu8yd3j3j281',
                        name: 'label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jp5qxf4ahf2b1blzr0t0c10fj',
                        name: 'categorized_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'u1a25vc3fx7dvd7esa3569p69',
                        name: 'comfy_cms_categories_site_id_categorized_type_label_key',
                        unique: true,
                        fieldIds: [
                            '9wzko2usjtxzmtha8iwjtyh36',
                            'jp5qxf4ahf2b1blzr0t0c10fj',
                            'dhvm5i7whcc1shu8yd3j3j281',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'p1986ujktrv7yec63i9op4yli',
                        name: 'comfy_cms_categories_pkey',
                        unique: true,
                        fieldIds: ['76g8ntmzax7x5la7tjh1nc81e'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '33ca24mqyw0edfw8nm4tahc3a',
                name: 'comfy_cms_revisions_record_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'bpeqtu17nlds7fk9qt6ouax09',
                targetSchema: 'public',
                targetTableId: '6m12iicr5bmvmjh7vc4nnxwx4',
                sourceFieldId: 'iflix9rs1nr0vwdxer4pl15bv',
                targetFieldId: 'uvy743vegv4khu0lorjnvbyiw',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '37d5nyoucm96qyjrc4j8tnfa4',
                name: 'comfy_cms_categories_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 's88553ow908alh5oai78mda7r',
                targetTableId: '1i1n19xwucw76ftnnid8z7t2o',
                sourceFieldId: '9wzko2usjtxzmtha8iwjtyh36',
                targetFieldId: 'a2hyi3q08x3a1hp394ebbb66h',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '3axngwbad8wo46zbk6ycfrt79',
                name: 'comfy_cms_revisions_record_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'bpeqtu17nlds7fk9qt6ouax09',
                targetSchema: 'public',
                targetTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                sourceFieldId: 'iflix9rs1nr0vwdxer4pl15bv',
                targetFieldId: 'y8j19xae7nn91wn0m7aebp5h0',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6gz2382uk6rbtvshq9l1zzqys',
                name: 'comfy_cms_translations_page_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'og53dwps4q7txai0egunnh6zb',
                targetTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                sourceFieldId: 'd8cm7femomjqul6q7ivzj9ehi',
                targetFieldId: 'y8j19xae7nn91wn0m7aebp5h0',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '74zqqon9vqax6krkvxzdhizwj',
                name: 'comfy_cms_revisions_record_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'bpeqtu17nlds7fk9qt6ouax09',
                targetSchema: 'public',
                targetTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                sourceFieldId: 'iflix9rs1nr0vwdxer4pl15bv',
                targetFieldId: 'vvpb6i0zl180z0xtkbkmbt8zq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'dcfp1of3r49syon1m7ji7r4jz',
                name: 'comfy_cms_translations_layout_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'og53dwps4q7txai0egunnh6zb',
                targetTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                sourceFieldId: 'm92nfn5papv27p2dx5zxaalkp',
                targetFieldId: 'vvpb6i0zl180z0xtkbkmbt8zq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fbfi778xy1oafoaorb69l7xpx',
                name: 'comfy_cms_pages_parent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                targetTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                sourceFieldId: 'uxc4pj43vq7pdr1eikkgqxmus',
                targetFieldId: 'y8j19xae7nn91wn0m7aebp5h0',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'j7mbc1pgg3gxhcw1mtw33q2eu',
                name: 'comfy_cms_categorizations_category_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'cyfncpo2zosklocsicymvl4g2',
                targetTableId: 's88553ow908alh5oai78mda7r',
                sourceFieldId: '31nek4b2kuigij52w2r11h9g8',
                targetFieldId: '76g8ntmzax7x5la7tjh1nc81e',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'k7obmh3n8juorg1l87fiiij8g',
                name: 'comfy_cms_pages_layout_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                targetTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                sourceFieldId: 'du2trf4cbs0tsezfdwymoavhp',
                targetFieldId: 'vvpb6i0zl180z0xtkbkmbt8zq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'kjlielgazpuvg5lzb5i5d6q15',
                name: 'comfy_cms_pages_target_page_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                targetTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                sourceFieldId: 'fpmprec23i7bkqqa1xqtkrvzh',
                targetFieldId: 'y8j19xae7nn91wn0m7aebp5h0',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'mvs0re4fz6xs7ivjev7yxqxw4',
                name: 'comfy_cms_files_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '4gz554fu1is9nn8kokdv8k8lw',
                targetTableId: '1i1n19xwucw76ftnnid8z7t2o',
                sourceFieldId: 'kemt4iwpzt3qf6gtfaf8zr3av',
                targetFieldId: 'a2hyi3q08x3a1hp394ebbb66h',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'q6hdn2vkibid8ffhdpoajdg32',
                name: 'comfy_cms_snippets_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6m12iicr5bmvmjh7vc4nnxwx4',
                targetTableId: '1i1n19xwucw76ftnnid8z7t2o',
                sourceFieldId: '5ma4bqfgltiom4f52uy265ahr',
                targetFieldId: 'a2hyi3q08x3a1hp394ebbb66h',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rzp18p74yxwu1u2y6y9euofm3',
                name: 'comfy_cms_layouts_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                targetTableId: '1i1n19xwucw76ftnnid8z7t2o',
                sourceFieldId: 'g5f55dk6u10i0e8twlopis5yn',
                targetFieldId: 'a2hyi3q08x3a1hp394ebbb66h',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 't7qh9ic3s8ivfkzk644qjl54i',
                name: 'comfy_cms_pages_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'e5834gyvmwro9zxtg3b5cw3bz',
                targetTableId: '1i1n19xwucw76ftnnid8z7t2o',
                sourceFieldId: 'fa381qe39zwfs3bkhb99lfs9f',
                targetFieldId: 'a2hyi3q08x3a1hp394ebbb66h',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'w7seqm46riwegnvpp2ofzjv60',
                name: 'comfy_cms_layouts_parent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                targetTableId: 'knry1hxcqwwa09vnlpyunt6a8',
                sourceFieldId: '7lg3lic3upf5opwjhorqve3n7',
                targetFieldId: 'vvpb6i0zl180z0xtkbkmbt8zq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
