import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/django-db.png';
import imageDark from '@/assets/templates/django-db-dark.png';

const now = Date.now();

export const djangoDb: Template = {
    slug: 'django-database',
    name: 'Django',
    shortDescription: 'High-level Python web framework',
    description:
        'For rapid, clean web app development, with tools, migrations, and database tables',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Django', 'Python'],
    featured: true,
    url: 'https://github.com/django/django',
    diagram: {
        id: 'django_db',
        name: 'django-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '0mwj7i78bohux3lamc5xeer9s',
                name: 'django_content_type',
                schema: 'public',
                x: 691.6464135518331,
                y: 281.2965038885413,
                fields: [
                    {
                        id: 'aaswqtx7y5enj158iecrsvxv1',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('django_content_type_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '5gtjppltnsygv1yee34q7lizp',
                        name: 'app_label',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0pffgfuuaosjc9kpwnxuat4pv',
                        name: 'model',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '8yw9chz65l9e0djd3cyjg95b4',
                        name: 'idx_django_content_type_app_label_model',
                        unique: false,
                        fieldIds: [
                            '5gtjppltnsygv1yee34q7lizp',
                            '0pffgfuuaosjc9kpwnxuat4pv',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'nc0iqhp6nvac5gr7kit3cb1ug',
                        name: 'django_content_type_app_label_model_key',
                        unique: true,
                        fieldIds: [
                            '5gtjppltnsygv1yee34q7lizp',
                            '0pffgfuuaosjc9kpwnxuat4pv',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'z3ykfz97ufe68l46585r7rh08',
                        name: 'django_content_type_pkey',
                        unique: true,
                        fieldIds: ['aaswqtx7y5enj158iecrsvxv1'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '0sqcjqp0wh42ptj8ltj9shw5m',
                name: 'auth_user_user_permissions',
                schema: 'public',
                x: 969.9324055268842,
                y: 67.88127906241971,
                fields: [
                    {
                        id: '48hayinn1vpg0npcbwrnhju02',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('auth_user_user_permissions_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '4ywckubg6r1nuyovtxai77g8x',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5fajzfjhgsf95siv43r3dhr9z',
                        name: 'permission_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'y9vmo108tmagq4oew1el9yxmi',
                        name: 'auth_user_user_permissions_pkey',
                        unique: true,
                        fieldIds: ['48hayinn1vpg0npcbwrnhju02'],
                        createdAt: now,
                    },
                    {
                        id: 'tdjmqah44786blfdyffpve0yx',
                        name: 'idx_auth_user_user_permissions_user_id',
                        unique: false,
                        fieldIds: ['4ywckubg6r1nuyovtxai77g8x'],
                        createdAt: now,
                    },
                    {
                        id: 't4fn8vcwr3fjk8vd7kjjf8xe2',
                        name: 'auth_user_user_permissions_user_id_permission_id_key',
                        unique: true,
                        fieldIds: [
                            '4ywckubg6r1nuyovtxai77g8x',
                            '5fajzfjhgsf95siv43r3dhr9z',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'd0rsyfk7qr34wdw5hqkhy7gs4',
                        name: 'idx_auth_user_user_permissions_permission_id',
                        unique: false,
                        fieldIds: ['5fajzfjhgsf95siv43r3dhr9z'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6ijscya6hovxhx0q7dsq5lgba',
                name: 'auth_permission',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'leg6ngcahmqkrqbq5qnyw6o9c',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('auth_permission_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'o3mmof3mhmjc99fyxijlrhjoj',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '23lkh2kce9zuj24n73hl9kjfk',
                        name: 'content_type_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'bh9megq4qjnu5483xdw1kkloy',
                        name: 'codename',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rwnp76au1aezon00ch719t8zm',
                        name: 'idx_auth_permission_content_type_id_codename',
                        unique: false,
                        fieldIds: [
                            '23lkh2kce9zuj24n73hl9kjfk',
                            'bh9megq4qjnu5483xdw1kkloy',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'zn35qhbfbiwwtyyz34y6994kq',
                        name: 'auth_permission_content_type_id_codename_key',
                        unique: true,
                        fieldIds: [
                            '23lkh2kce9zuj24n73hl9kjfk',
                            'bh9megq4qjnu5483xdw1kkloy',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'ox6twypyhwpk5zyvhxxr8frn9',
                        name: 'auth_permission_pkey',
                        unique: true,
                        fieldIds: ['leg6ngcahmqkrqbq5qnyw6o9c'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'aj90tn5zdut2i9wchf2g054u6',
                name: 'django_session',
                schema: 'public',
                x: 498.1175315856394,
                y: 464.6575256259596,
                fields: [
                    {
                        id: 'pgkj2amki1b2mqtsd9c0nnd1u',
                        name: 'session_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'j2ztu8l6rkjlxsx76ykp2ib8u',
                        name: 'session_data',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ymr32udk6isv8qp1tsl92citq',
                        name: 'expire_date',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'u7uqsqrmxk8ivcy7ud3qkt96s',
                        name: 'django_session_pkey',
                        unique: true,
                        fieldIds: ['pgkj2amki1b2mqtsd9c0nnd1u'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bq198nmyhwfzh6a1fkg7b2vw7',
                name: 'django_migrations',
                schema: 'public',
                x: 204.74159188690328,
                y: 468.76961766614477,
                fields: [
                    {
                        id: '0t7dddvyf9ck4hkdj62eypuab',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('django_migrations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'e5eec3s5p1mn1m3xou4p666f5',
                        name: 'app',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 's0dktocfk76dgsxtmxboy5sl9',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wskoltcxjd11q2vriagunj6dk',
                        name: 'applied',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xlu6psjbppdhy6lsvuk1kwclr',
                        name: 'django_migrations_pkey',
                        unique: true,
                        fieldIds: ['0t7dddvyf9ck4hkdj62eypuab'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ezfuiy69q3e1n0snzgci2aotf',
                name: 'auth_group',
                schema: 'public',
                x: 889.6198761279297,
                y: -150.25737909009885,
                fields: [
                    {
                        id: 'ezeknuboplfry5sbpiji8autf',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('auth_group_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'ea0kvqh2x6qpd4gzes5npsja6',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'gubuzayp4ie7v1flnio36sv1b',
                        name: 'auth_group_pkey',
                        unique: true,
                        fieldIds: ['ezeknuboplfry5sbpiji8autf'],
                        createdAt: now,
                    },
                    {
                        id: 'n4co9vid9w8p763a3li9psjte',
                        name: 'auth_group_name_key',
                        unique: true,
                        fieldIds: ['ea0kvqh2x6qpd4gzes5npsja6'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'gp2tb8rtocqnpyrogbk72ti4e',
                name: 'django_admin_log',
                schema: 'public',
                x: 1074.4346504983594,
                y: 363.39439464701354,
                fields: [
                    {
                        id: 'divj1daariu3ockoff7tfwghj',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('django_admin_log_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '3mztc0xvt0fbogx7a91s23vp4',
                        name: 'action_time',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ool75ur2ztqwxk10emn3vy5z2',
                        name: 'object_id',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zni78ipli4c537c93erb7wjt5',
                        name: 'object_repr',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vd8uhrjztnob8ytlyrl7q3yq7',
                        name: 'action_flag',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kuvjqo6h4orgyz0fytp2l3dsk',
                        name: 'change_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm2bkd2omwo9cs94k7856vv2eo',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8ybk1fb6ce3v3fbaoh9sdrvno',
                        name: 'content_type_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '02etetkil34hidzu2dlsyd0tc',
                        name: 'idx_django_admin_log_user_id',
                        unique: false,
                        fieldIds: ['m2bkd2omwo9cs94k7856vv2eo'],
                        createdAt: now,
                    },
                    {
                        id: '2sb8sgefsg0ytsd0y60ferwyu',
                        name: 'django_admin_log_pkey',
                        unique: true,
                        fieldIds: ['divj1daariu3ockoff7tfwghj'],
                        createdAt: now,
                    },
                    {
                        id: 'bnrbxn8j6g3ogueq6lwcs2cc3',
                        name: 'idx_django_admin_log_content_type_id',
                        unique: false,
                        fieldIds: ['8ybk1fb6ce3v3fbaoh9sdrvno'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'srvnwsww376kltu4bqcaix74j',
                name: 'auth_user',
                schema: 'public',
                x: 1568.9215940685822,
                y: 394.2576459684892,
                fields: [
                    {
                        id: 'n85uz79bjbt8c2o8pldag3rrr',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('auth_user_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'p7wmxev1ei04rfvx0fiuyi6jo',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'h09pzea3qllvhhvh1isma40ev',
                        name: 'last_login',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pv5lp8upk6lpe12bygngewu1f',
                        name: 'is_superuser',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'r8thbfqjvlanga12s21mlcer4',
                        name: 'username',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dwg2tna0dklz7yvsxf9qohgvt',
                        name: 'first_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't96k3jjdd4b5cfl2mg48idr5r',
                        name: 'last_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lqrx9tm94xh6gqychm530g8j5',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3y4rf05ctzdih9lif4pqe5ouu',
                        name: 'is_staff',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd7kize8181ek72yqgg8401x98',
                        name: 'is_active',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zu279l5v45mjm3lb54jf3y8kw',
                        name: 'date_joined',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4c4q2516wmq77s24o7uvysb6p',
                        name: 'auth_user_username_key',
                        unique: true,
                        fieldIds: ['r8thbfqjvlanga12s21mlcer4'],
                        createdAt: now,
                    },
                    {
                        id: 'm38rq1kj7iik25w2qkveyotcd',
                        name: 'auth_user_pkey',
                        unique: true,
                        fieldIds: ['n85uz79bjbt8c2o8pldag3rrr'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vsbckzn4y71ye7whfi5sw1o8t',
                name: 'auth_user_groups',
                schema: 'public',
                x: 1275.9243744207602,
                y: -114.0055607043559,
                fields: [
                    {
                        id: '9f5vlf6678ppx46woqpsgbo8u',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('auth_user_groups_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'wte5c7eqpnh6614c64gmc8h56',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g3afeo3sq0l3f2h5lcrajkowm',
                        name: 'group_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ma7z948nuywxqolen11b50jwh',
                        name: 'auth_user_groups_user_id_group_id_key',
                        unique: true,
                        fieldIds: [
                            'wte5c7eqpnh6614c64gmc8h56',
                            'g3afeo3sq0l3f2h5lcrajkowm',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '3s0v03e0dux5dxx6664iebalq',
                        name: 'idx_auth_user_groups_user_id',
                        unique: false,
                        fieldIds: ['wte5c7eqpnh6614c64gmc8h56'],
                        createdAt: now,
                    },
                    {
                        id: 'mx4qb2szbjrg8b0vrif85462y',
                        name: 'auth_user_groups_pkey',
                        unique: true,
                        fieldIds: ['9f5vlf6678ppx46woqpsgbo8u'],
                        createdAt: now,
                    },
                    {
                        id: '74l3ciypq3xftihxvqykqntzn',
                        name: 'idx_auth_user_groups_group_id',
                        unique: false,
                        fieldIds: ['g3afeo3sq0l3f2h5lcrajkowm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xvzbm8lrq4nl7lfk5zugumn2n',
                name: 'auth_group_permissions',
                schema: 'public',
                x: 510.7002780352177,
                y: -100.63021316033364,
                fields: [
                    {
                        id: 'd4ftozj6uhbdxf3fwqvsxoo3z',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('auth_group_permissions_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'bvkmgqa1misk2pjwjwof9cx60',
                        name: 'group_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lyijn9tl7hf3gurdo5ug7l7fn',
                        name: 'permission_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5y4k0wiwytwu2672hlxss0vay',
                        name: 'auth_group_permissions_group_id_permission_id_key',
                        unique: true,
                        fieldIds: [
                            'bvkmgqa1misk2pjwjwof9cx60',
                            'lyijn9tl7hf3gurdo5ug7l7fn',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'y7yijhut1vzeal2aucj7fyi8t',
                        name: 'auth_group_permissions_pkey',
                        unique: true,
                        fieldIds: ['d4ftozj6uhbdxf3fwqvsxoo3z'],
                        createdAt: now,
                    },
                    {
                        id: 'b5zdp69zqx0cnpnuz1fe35mif',
                        name: 'idx_auth_group_permissions_group_id',
                        unique: false,
                        fieldIds: ['bvkmgqa1misk2pjwjwof9cx60'],
                        createdAt: now,
                    },
                    {
                        id: 'r7luj64081vml4puniy4no62k',
                        name: 'idx_auth_group_permissions_permission_id',
                        unique: false,
                        fieldIds: ['lyijn9tl7hf3gurdo5ug7l7fn'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '5fjfvdyd89kgo7z3nsjib17gv',
                name: 'auth_group_permissions_permission_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xvzbm8lrq4nl7lfk5zugumn2n',
                targetTableId: '6ijscya6hovxhx0q7dsq5lgba',
                sourceFieldId: 'lyijn9tl7hf3gurdo5ug7l7fn',
                targetFieldId: 'leg6ngcahmqkrqbq5qnyw6o9c',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '7rincnrlprecuwvvw02dwemeq',
                name: 'django_admin_log_content_type_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'gp2tb8rtocqnpyrogbk72ti4e',
                targetTableId: '0mwj7i78bohux3lamc5xeer9s',
                sourceFieldId: '8ybk1fb6ce3v3fbaoh9sdrvno',
                targetFieldId: 'aaswqtx7y5enj158iecrsvxv1',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '7t9hv5d7szn6t3026obwyrmz5',
                name: 'django_admin_log_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'gp2tb8rtocqnpyrogbk72ti4e',
                targetTableId: 'srvnwsww376kltu4bqcaix74j',
                sourceFieldId: 'm2bkd2omwo9cs94k7856vv2eo',
                targetFieldId: 'n85uz79bjbt8c2o8pldag3rrr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'irg0omwf0feagbc5y2iro4zy3',
                name: 'auth_user_user_permissions_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '0sqcjqp0wh42ptj8ltj9shw5m',
                targetTableId: 'srvnwsww376kltu4bqcaix74j',
                sourceFieldId: '4ywckubg6r1nuyovtxai77g8x',
                targetFieldId: 'n85uz79bjbt8c2o8pldag3rrr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'j6yim4c01qkvl1bu9dm39grqg',
                name: 'auth_user_user_permissions_permission_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '0sqcjqp0wh42ptj8ltj9shw5m',
                targetTableId: '6ijscya6hovxhx0q7dsq5lgba',
                sourceFieldId: '5fajzfjhgsf95siv43r3dhr9z',
                targetFieldId: 'leg6ngcahmqkrqbq5qnyw6o9c',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ppazloh3vnxbl98vmlpubeqwq',
                name: 'auth_permission_content_type_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6ijscya6hovxhx0q7dsq5lgba',
                targetTableId: '0mwj7i78bohux3lamc5xeer9s',
                sourceFieldId: '23lkh2kce9zuj24n73hl9kjfk',
                targetFieldId: 'aaswqtx7y5enj158iecrsvxv1',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'qxnuct6h2dubpu6zg12uisw5c',
                name: 'auth_user_groups_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vsbckzn4y71ye7whfi5sw1o8t',
                targetTableId: 'srvnwsww376kltu4bqcaix74j',
                sourceFieldId: 'wte5c7eqpnh6614c64gmc8h56',
                targetFieldId: 'n85uz79bjbt8c2o8pldag3rrr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'txo52vd6u7xwaorgjr2q40ink',
                name: 'auth_group_permissions_group_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xvzbm8lrq4nl7lfk5zugumn2n',
                targetTableId: 'ezfuiy69q3e1n0snzgci2aotf',
                sourceFieldId: 'bvkmgqa1misk2pjwjwof9cx60',
                targetFieldId: 'ezeknuboplfry5sbpiji8autf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'w78nsg7j2if4cvntaj8qqqoor',
                name: 'auth_user_groups_group_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vsbckzn4y71ye7whfi5sw1o8t',
                targetTableId: 'ezfuiy69q3e1n0snzgci2aotf',
                sourceFieldId: 'g3afeo3sq0l3f2h5lcrajkowm',
                targetFieldId: 'ezeknuboplfry5sbpiji8autf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
