import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/gravity-db.png';
import imageDark from '@/assets/templates/gravity-db-dark.png';

const now = Date.now();

export const gravityDb: Template = {
    slug: 'gravity-database',
    name: 'Gravity',
    shortDescription: 'Node.js SaaS Boilerplate',
    description:
        'by Kyle Gawley, is a SaaS boilerplate with a React UI, built to jumpstart Node.js SaaS app development',
    image,
    imageDark,
    tags: ['Postgres', 'SaaS', 'Node.js'],
    featured: false,
    url: 'https://usegravity.app',
    diagram: {
        id: 'gravity_db',
        name: 'gravity-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '9mcqm3g6goiqwxv6oylsg3qvy',
                name: 'invite',
                schema: 'public',
                x: 174.2622277626349,
                y: -235.3892617851391,
                fields: [
                    {
                        id: 'rqtz6u3w5i3p74ah8m8z4tj35',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('invite_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 't71dsanwn58iith8b8tp53im7',
                        name: 'invite_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7cv6cti6a3xxc4pas8v6icohj',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f42zkm1kgar1udzc03wklzooj',
                        name: 'account_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1koz4znool0h7xpa7icyb7fjk',
                        name: 'date_sent',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cprnsaaipf1u8fl98ikvkouq5',
                        name: 'used',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vvydfuvao8aln0ddwy3d69qly',
                        name: 'idx_invite_account_id',
                        unique: false,
                        fieldIds: ['f42zkm1kgar1udzc03wklzooj'],
                        createdAt: now,
                    },
                    {
                        id: 'ki6nfumlxlzujm3696n1sa73t',
                        name: 'invite_pkey',
                        unique: true,
                        fieldIds: ['rqtz6u3w5i3p74ah8m8z4tj35'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'gk9doekmajow316hbyavivwwv',
                name: 'session',
                schema: 'public',
                x: 699.1601394664892,
                y: 552.6274940415008,
                fields: [
                    {
                        id: 'u31837ao8oqfnxgzsxtyxxzgo',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('session_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'zg48u21perjt6zjnjlc4xunb3',
                        name: 'user_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zmvylu4kf5c7uupilw0w021k4',
                        name: 'session_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ir70q0c7y02o1v1fd3kugsjvo',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'a0ddsvfclpvk7imbied4r1cu2',
                        name: 'expires_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'v5q4o5ay0qrs32yxvddjm7n2m',
                        name: 'idx_session_user_id',
                        unique: false,
                        fieldIds: ['zg48u21perjt6zjnjlc4xunb3'],
                        createdAt: now,
                    },
                    {
                        id: 'kxya0tzg7bxsxcnvainxmwe7o',
                        name: 'session_session_token_key',
                        unique: true,
                        fieldIds: ['zmvylu4kf5c7uupilw0w021k4'],
                        createdAt: now,
                    },
                    {
                        id: '2whapij8jgd62ltnjz3kpa8ws',
                        name: 'session_pkey',
                        unique: true,
                        fieldIds: ['u31837ao8oqfnxgzsxtyxxzgo'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jsb9c0x12insbcbyrzs23g35k',
                name: 'payment',
                schema: 'public',
                x: -223.60679774997902,
                y: -193.89262614623652,
                fields: [
                    {
                        id: 'xwh27vs9i1c2gnpvgxq0bj9l4',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('payment_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'qn1drhserivlx9s1tpf8y5cio',
                        name: 'account_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mrpfpbrhqow7gs48yzp0r7ewn',
                        name: 'amount',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'i4clo4al2rvt04y5mpja7l54b',
                        name: 'currency',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: "'USD'::character varying",
                        createdAt: now,
                    },
                    {
                        id: 'cxbdivmos31159w4hopqs4ssx',
                        name: 'payment_date',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'wvkakgqbe1e7kuxt0x5ijhlqd',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '446vs82r1fnpqha150g9vljps',
                        name: 'stripe_payment_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'kjwqzaxyb971gx143f3g6j0zu',
                        name: 'payment_stripe_payment_id_key',
                        unique: true,
                        fieldIds: ['446vs82r1fnpqha150g9vljps'],
                        createdAt: now,
                    },
                    {
                        id: 'ljajrsblf5ftmacd3qknu6raj',
                        name: 'payment_pkey',
                        unique: true,
                        fieldIds: ['xwh27vs9i1c2gnpvgxq0bj9l4'],
                        createdAt: now,
                    },
                    {
                        id: '7roio8wf5qyd9f7g3ejn3nc45',
                        name: 'idx_payment_account_id',
                        unique: false,
                        fieldIds: ['qn1drhserivlx9s1tpf8y5cio'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'm4uslifnlqy7gi9lz3fi0jipg',
                name: 'plan_feature',
                schema: 'public',
                x: 843.296798741876,
                y: 20.91062713357283,
                fields: [
                    {
                        id: 'jqbbj4ydwvkmqh1vmchrj0bph',
                        name: 'plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'godyosoc7ltnv5pv1nr9qizzk',
                        name: 'feature_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rmyry50hlrb6ucx1a4put43by',
                        name: 'plan_feature_pkey',
                        unique: true,
                        fieldIds: [
                            'jqbbj4ydwvkmqh1vmchrj0bph',
                            'godyosoc7ltnv5pv1nr9qizzk',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'o3msgohjwlp3kaho95n1qiq27',
                name: 'audit_log',
                schema: 'public',
                x: 524.6790298852982,
                y: 24.089894697482578,
                fields: [
                    {
                        id: 'tbkkmuvximi61njydlirw472b',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('audit_log_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'j86ws1b2vk3vg7bgrwaldimh4',
                        name: 'user_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '71esx919iijcouhgci1e800qb',
                        name: 'account_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2gfltip5xjuth7h6b4q341l9q',
                        name: 'action',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4zxh1jrwzib6sjxvsuxcjigkg',
                        name: 'details',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5q3l9p7b0qmkfvnaxy9ishsos',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ehryt65xj518xw79e6sae5q03',
                        name: 'idx_audit_log_user_id',
                        unique: false,
                        fieldIds: ['j86ws1b2vk3vg7bgrwaldimh4'],
                        createdAt: now,
                    },
                    {
                        id: 'gvo36aousfdldwi5h9p1720mh',
                        name: 'idx_audit_log_account_id',
                        unique: false,
                        fieldIds: ['71esx919iijcouhgci1e800qb'],
                        createdAt: now,
                    },
                    {
                        id: 'daaswvtb2d0zw870tlqrco15s',
                        name: 'audit_log_pkey',
                        unique: true,
                        fieldIds: ['tbkkmuvximi61njydlirw472b'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'q331uck6xuljg8eud6580zkgk',
                name: 'subscription',
                schema: 'public',
                x: -223.6067977499789,
                y: 393.89262614623664,
                fields: [
                    {
                        id: 'ixg46t4ivg30894s7kjpe7zr4',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('subscription_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'vxjx3y7fs8bcaziobvbsamk5a',
                        name: 'account_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'uehfwrisn598i89uy0du3xxan',
                        name: 'plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'eg0kwio9mv4hq4sxaso3h2fuv',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hmlalaf4sn3e8vru0u7tne83w',
                        name: 'start_date',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'vfrewl49mc7o53wsqhgw3ixqe',
                        name: 'end_date',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a4gesvjkg8tzv8vvf0px23dbb',
                        name: 'stripe_subscription_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rh7ks6u1obkt0u98auf4hktra',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'sukshs8q95thov4gy2130i5vy',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xfe6p7wtlz6wmsxi22u9cwm9p',
                        name: 'subscription_stripe_subscription_id_key',
                        unique: true,
                        fieldIds: ['a4gesvjkg8tzv8vvf0px23dbb'],
                        createdAt: now,
                    },
                    {
                        id: 'hldm2oge35zkmk8w7dxoal90n',
                        name: 'subscription_pkey',
                        unique: true,
                        fieldIds: ['ixg46t4ivg30894s7kjpe7zr4'],
                        createdAt: now,
                    },
                    {
                        id: '64irwxp0pxtj423zupblxxf7e',
                        name: 'idx_subscription_account_id',
                        unique: false,
                        fieldIds: ['vxjx3y7fs8bcaziobvbsamk5a'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 't4by2ztfwylasi8nmet2x3n9t',
                name: 'user',
                schema: 'public',
                x: 376.5214998091394,
                y: 461.53276952141255,
                fields: [
                    {
                        id: 'l1x4mv4x6s9rk80yu10l3t2ex',
                        name: 'id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '980pf6mq23c6f9gps4ehq7744',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wpjsjkqk6o6w1kq6o7gxz1m4n',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'muuvx8vrot72zs6yps457jf6r',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7tfqvswgmm1xk3x5d57omgh05',
                        name: 'date_created',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'm2n1gm4q6wbl2c6xuad1x2gr7',
                        name: 'last_login',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rmsrm9w9qe6yxdmbpnj7d1q98',
                        name: 'permission',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wc7ew5zdcllqhahjmnxw92tn4',
                        name: 'push_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j3ljzeav70g5xsu580ggjjfgu',
                        name: 'account_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'c8gze3ohlz560ax8a2xff9zkq',
                        name: 'user_pkey',
                        unique: true,
                        fieldIds: ['l1x4mv4x6s9rk80yu10l3t2ex'],
                        createdAt: now,
                    },
                    {
                        id: 'geat7zfrxyzj6kn3z1ss4cxl2',
                        name: 'idx_user_account_id',
                        unique: false,
                        fieldIds: ['j3ljzeav70g5xsu580ggjjfgu'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zoj6z1arck84k10h5d6jqaqwk',
                name: 'account',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'kc2gu14qor8iqmmu8who72gak',
                        name: 'id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6uvbmv6ramqj4xzdutx6p65dr',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0m1o9ufnos3thn3s30he72xpp',
                        name: 'date_created',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'pllk2x0btm7ziyyq6uhw0wbh2',
                        name: 'stripe_customer_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zraia51z4my5c1jbkyp0pt5z6',
                        name: 'stripe_subscription_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '323xuu8dnt4m4xdlm3s4h49xc',
                        name: 'plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'k2yggy3ceu8yzopd79kiq0xw8',
                        name: 'referrer',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6c88ji50aq3pphoe3q351mhd3',
                        name: 'active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sxnhjzwyvwtervu458kuub504',
                        name: 'account_pkey',
                        unique: true,
                        fieldIds: ['kc2gu14qor8iqmmu8who72gak'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zowb74guu354061ruc9y1s2fi',
                name: 'feature',
                schema: 'public',
                x: 863.1365940700359,
                y: 269.4364829887478,
                fields: [
                    {
                        id: 'wxrb33d4gjj2876ofa1c74z63',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('feature_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '8vr1rhrhn8q36qr425rfqncco',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wgiphu9h73k69isoqohu3h56r',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mht1g1hqtsfmpe68frmlkenvc',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'j2uxeu5kg5i6p0bzmldxtu7az',
                        name: 'feature_name_key',
                        unique: true,
                        fieldIds: ['8vr1rhrhn8q36qr425rfqncco'],
                        createdAt: now,
                    },
                    {
                        id: 'cnj5jqbuc51kle06va6fzsv9l',
                        name: 'feature_pkey',
                        unique: true,
                        fieldIds: ['wxrb33d4gjj2876ofa1c74z63'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '11xz1smunajzaoo01y8t6dwmx',
                name: 'session_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'gk9doekmajow316hbyavivwwv',
                targetTableId: 't4by2ztfwylasi8nmet2x3n9t',
                sourceFieldId: 'zg48u21perjt6zjnjlc4xunb3',
                targetFieldId: 'l1x4mv4x6s9rk80yu10l3t2ex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6dko72revj1g6gt126nm6fz1i',
                name: 'user_account_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 't4by2ztfwylasi8nmet2x3n9t',
                targetTableId: 'zoj6z1arck84k10h5d6jqaqwk',
                sourceFieldId: 'j3ljzeav70g5xsu580ggjjfgu',
                targetFieldId: 'kc2gu14qor8iqmmu8who72gak',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '9p3spt9qogvh16fydi375kyvo',
                name: 'payment_account_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'jsb9c0x12insbcbyrzs23g35k',
                targetTableId: 'zoj6z1arck84k10h5d6jqaqwk',
                sourceFieldId: 'qn1drhserivlx9s1tpf8y5cio',
                targetFieldId: 'kc2gu14qor8iqmmu8who72gak',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'a014dk93xbn9xnkpnx3a4szfu',
                name: 'subscription_account_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'q331uck6xuljg8eud6580zkgk',
                targetTableId: 'zoj6z1arck84k10h5d6jqaqwk',
                sourceFieldId: 'vxjx3y7fs8bcaziobvbsamk5a',
                targetFieldId: 'kc2gu14qor8iqmmu8who72gak',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'c7lp1pi7qlcq7v4p23uwzqb90',
                name: 'invite_account_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '9mcqm3g6goiqwxv6oylsg3qvy',
                targetTableId: 'zoj6z1arck84k10h5d6jqaqwk',
                sourceFieldId: 'f42zkm1kgar1udzc03wklzooj',
                targetFieldId: 'kc2gu14qor8iqmmu8who72gak',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'corebtkudmyruld6t2pxrlo8z',
                name: 'audit_log_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'o3msgohjwlp3kaho95n1qiq27',
                targetTableId: 't4by2ztfwylasi8nmet2x3n9t',
                sourceFieldId: 'j86ws1b2vk3vg7bgrwaldimh4',
                targetFieldId: 'l1x4mv4x6s9rk80yu10l3t2ex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'g6b82id659sw10k0lgqjfuab9',
                name: 'audit_log_account_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'o3msgohjwlp3kaho95n1qiq27',
                targetTableId: 'zoj6z1arck84k10h5d6jqaqwk',
                sourceFieldId: '71esx919iijcouhgci1e800qb',
                targetFieldId: 'kc2gu14qor8iqmmu8who72gak',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'zem1jb3t8xvq0z95cyldkfj94',
                name: 'plan_feature_feature_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'm4uslifnlqy7gi9lz3fi0jipg',
                targetTableId: 'zowb74guu354061ruc9y1s2fi',
                sourceFieldId: 'godyosoc7ltnv5pv1nr9qizzk',
                targetFieldId: 'wxrb33d4gjj2876ofa1c74z63',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
