import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/koel-db.png';
import imageDark from '@/assets/templates/koel-db-dark.png';

const now = Date.now();

export const koelDb: Template = {
    slug: 'koel-database',
    name: 'Koel | koel.dev',
    shortDescription: 'Music streaming server',
    description: 'schema for Koel open source software',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://koel.dev',
    diagram: {
        id: 'koel_db',
        name: 'koel-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '1bbo7xfnv1iva2e1g4wvegnf5',
                name: 'users',
                schema: 'public',
                x: 713.1498138008048,
                y: -242.22539388322525,
                fields: [
                    {
                        id: 'dsfw2sbft9slcl5uvwoagzb10',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3abesa8irp6uvt1x4sfmihjzj',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'eicvvczqhxcu8qvk78i9849mb',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'e1ns99weti8sprn5gp2bdbul6',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ur7bpwpch958dqj9j2bs7uhb6',
                        name: 'is_admin',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gtqceud0jsipodny36jxfnrew',
                        name: 'preferences',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0m31hmm0u9casjsn3cs33flz4',
                        name: 'remember_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uf2dr9j761tpjlvwn2uwec5pz',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '20ykyg1qzqxxgxwb60mpox4jg',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2h2inppld9pdkw50tjbymowul',
                        name: 'users_email_key',
                        unique: true,
                        fieldIds: ['eicvvczqhxcu8qvk78i9849mb'],
                        createdAt: now,
                    },
                    {
                        id: 'wwks490rjdhpfvg2il92qq2cs',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['dsfw2sbft9slcl5uvwoagzb10'],
                        createdAt: now,
                    },
                    {
                        id: 'kyx1x39649qdy38nm69totuy3',
                        name: 'idx_users_email',
                        unique: true,
                        fieldIds: ['eicvvczqhxcu8qvk78i9849mb'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6wwb5b3z1yhbqjudyd2ozmgxl',
                name: 'password_resets',
                schema: 'public',
                x: 323.62038924930494,
                y: 77.65597775718257,
                fields: [
                    {
                        id: 'drysxyola6lz0lnp684ko3pjk',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'u7w5k1el47l8egyxc86gd6jc7',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3cn1tmjt5pvelsmjfz3abukdv',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'x9i3tacvdc5bfvxw83a67hsb8',
                        name: 'password_resets_pkey',
                        unique: true,
                        fieldIds: ['drysxyola6lz0lnp684ko3pjk'],
                        createdAt: now,
                    },
                    {
                        id: 'hh2s78ps7e1a23fifj996fyr3',
                        name: 'idx_password_resets_token',
                        unique: false,
                        fieldIds: ['u7w5k1el47l8egyxc86gd6jc7'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'blosecajwasyvqjym6i9w9qpu',
                name: 'interactions',
                schema: 'public',
                x: 696.9511011880829,
                y: 182.3399443929565,
                fields: [
                    {
                        id: '974h8bnm4otod49y616fh2ala',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3z6yf3bikh7nz7ntdyhspgfzc',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'byd351vas0hiweidg32wtuifx',
                        name: 'song_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i0f9eo819w5gao3gp3d4wea5l',
                        name: 'liked',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gev1ewcz1vfkuzfbeuypu2fvq',
                        name: 'play_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'h34fmivxjajhzv9pmkeh4g1sx',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'r2bwk69a7rc02guzmkimyt9up',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'yorges2bbnhl2208eita8rbuf',
                        name: 'idx_interactions_user_id',
                        unique: false,
                        fieldIds: ['3z6yf3bikh7nz7ntdyhspgfzc'],
                        createdAt: now,
                    },
                    {
                        id: 'o6tcpz3dy4qc010kt8feuav0r',
                        name: 'idx_interactions_song_id',
                        unique: false,
                        fieldIds: ['byd351vas0hiweidg32wtuifx'],
                        createdAt: now,
                    },
                    {
                        id: 'iocl25ciua2tck0r6wb9iwues',
                        name: 'interactions_pkey',
                        unique: true,
                        fieldIds: ['974h8bnm4otod49y616fh2ala'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'lo0qu9vhj7p4ivtmh75ianitt',
                name: 'artists',
                schema: 'public',
                x: 711.1065801668212,
                y: 635.2096385542169,
                fields: [
                    {
                        id: 'ti4sfv1s5irkk0smwyeqghnwu',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '77y6dxcb2cde1psxpd61ap76k',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '94kdt7yzrf3k75maep4myfo5i',
                        name: 'image',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cxnj4wg1lzndsbm0llsqvpqdc',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kfcpj5hcuv56emsbzok563nqn',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'w97d0l8hja81migmvgwysvsui',
                        name: 'artists_pkey',
                        unique: true,
                        fieldIds: ['ti4sfv1s5irkk0smwyeqghnwu'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'nu0rl3kwie8fdyksen9197hj6',
                name: 'settings',
                schema: 'public',
                x: 324.7862835959222,
                y: 298.9445783132531,
                fields: [
                    {
                        id: 'o5wrzxdkjufdd2vkyigqg63a9',
                        name: 'key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hta8e699svku3h4n53ivaj4g3',
                        name: 'value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vsswjq7lyvzt1kjnn4uil4fbr',
                        name: 'settings_pkey',
                        unique: true,
                        fieldIds: ['o5wrzxdkjufdd2vkyigqg63a9'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'omv1l5zyi5min10iiew33qirs',
                name: 'albums',
                schema: 'public',
                x: 295.4265060240966,
                y: 514.272845227062,
                fields: [
                    {
                        id: 'ljeeuqyeymidghrhx3ehe4ti8',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '61a72o357ug9sy3aet0bwshuk',
                        name: 'artist_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dptnuqmbmkvag5xm9x2196m02',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'u2iantg6xnxh51ix063oc1770',
                        name: 'cover',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1sflvykljwzee9plha0mjj26x',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rcezbd00izo9ccs9i545ghckw',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'i530gadq42rsjhbqvl6pu5n7a',
                        name: 'albums_pkey',
                        unique: true,
                        fieldIds: ['ljeeuqyeymidghrhx3ehe4ti8'],
                        createdAt: now,
                    },
                    {
                        id: 'e81lqj13sborcqsw5ft06bx8q',
                        name: 'idx_albums_artist_id',
                        unique: false,
                        fieldIds: ['61a72o357ug9sy3aet0bwshuk'],
                        createdAt: now,
                    },
                    {
                        id: 'qensm7inbwdcl3ygjmfr8759g',
                        name: 'idx_albums_name',
                        unique: false,
                        fieldIds: ['dptnuqmbmkvag5xm9x2196m02'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'paxmza7oe241fr0h2hnd1xm09',
                name: 'personal_access_tokens',
                schema: 'public',
                x: 5.960333642261389,
                y: 80.2291010194624,
                fields: [
                    {
                        id: 'aq9twy83aoqaul4heuaaa8f7v',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'z4s5q33u5a6rloboajmppx56c',
                        name: 'tokenable_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i2u2vlrmhvlhn784edu4gtt7s',
                        name: 'tokenable_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '33y6q9dme2jd50bg83uqp0q3m',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'q310bhlz6c9xzub8mkrm29hqx',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's565m6ikpm2uazuqa7nzponr5',
                        name: 'abilities',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qigp8rhr2ricakvwu34t117bg',
                        name: 'last_used_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ekt5sbi2o5svximhvxfblb33o',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xolimy8jr9nr592hg221eotq2',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'x09y37938y63ev1yjs10fny4w',
                        name: 'personal_access_tokens_pkey',
                        unique: true,
                        fieldIds: ['aq9twy83aoqaul4heuaaa8f7v'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'w5gjpa758vhjygti5ciu97ri0',
                name: 'playlists',
                schema: 'public',
                x: 1063.513994439295,
                y: -47.63294717330854,
                fields: [
                    {
                        id: 'cmpkn7oc4tnqfbr5jdmr5afpc',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ttehfu91qsa1zt3ykewg76e1l',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'grzqydghd11b9x4pjmxax3npv',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'djv785sm2nrz4mdyjx0xlttck',
                        name: 'rules',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fyb7h2qy9puc07k7di0fktqpu',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ns7garupvsu2d21mwrtfurka3',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xbponwp6o1dbcny7p8396kq4e',
                        name: 'playlists_pkey',
                        unique: true,
                        fieldIds: ['cmpkn7oc4tnqfbr5jdmr5afpc'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wey7nxcmp4i5t0lgdgb2t4bz8',
                name: 'songs',
                schema: 'public',
                x: 1065.9562557924003,
                y: 413.9210379981466,
                fields: [
                    {
                        id: '3zwecxjaci6fczjfpmh22q6wh',
                        name: 'id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2xdwpb6f4k92vdvfufnfq6501',
                        name: 'album_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6n9sm4zkioh6umrwcp4q53edl',
                        name: 'artist_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm2d7lyuj0jhf56v25o2evbb74',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'm1tjxhkl7sytoy52gur7ju2l8',
                        name: 'length',
                        type: {
                            id: 'double_precision',
                            name: 'double precision',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ke3vqdtesh2n99vm9xhhhj36i',
                        name: 'track',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'brxi1kk957vt1gs7p119q4ua5',
                        name: 'disc',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4xvqdttz0jg7rr28h04em27t0',
                        name: 'lyrics',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hpwn8nsv9bujobedafkkji9d0',
                        name: 'path',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1k3f7rakospztma47o266688p',
                        name: 'mtime',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'd20l6vp0hzmqe1jisoxlexld5',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rxra5l5wmc2veejsl2s766bb4',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'n3liojv5ta70mbbqufe97tfsf',
                        name: 'songs_pkey',
                        unique: true,
                        fieldIds: ['3zwecxjaci6fczjfpmh22q6wh'],
                        createdAt: now,
                    },
                    {
                        id: 'xn7q1yixlkbd88zkt2jqd3agj',
                        name: 'idx_songs_title',
                        unique: false,
                        fieldIds: ['m2d7lyuj0jhf56v25o2evbb74'],
                        createdAt: now,
                    },
                    {
                        id: 'e6txu6v4n24zy2n3oxzuk683x',
                        name: 'idx_songs_track_disc',
                        unique: true,
                        fieldIds: [
                            'ke3vqdtesh2n99vm9xhhhj36i',
                            'brxi1kk957vt1gs7p119q4ua5',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '9ks55ojbbg4a3w7h46azbgidy',
                        name: 'idx_songs_artist_id',
                        unique: false,
                        fieldIds: ['6n9sm4zkioh6umrwcp4q53edl'],
                        createdAt: now,
                    },
                    {
                        id: 'nihozcellgl5qw8cw7n5kr9aw',
                        name: 'idx_track_disc',
                        unique: true,
                        fieldIds: [
                            'ke3vqdtesh2n99vm9xhhhj36i',
                            'brxi1kk957vt1gs7p119q4ua5',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '60mhs0dxqhrp5pi2ehmsqgkht',
                        name: 'idx_songs_album_id',
                        unique: false,
                        fieldIds: ['2xdwpb6f4k92vdvfufnfq6501'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wwvgva66b5wxe3gmu3jthz3kd',
                name: 'playlist_song',
                schema: 'public',
                x: 1399.1859128822985,
                y: 236.37553290083412,
                fields: [
                    {
                        id: 'xgmoikmpcqy428acquoni733u',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qcz9l2vw7d28kangjrcf1857l',
                        name: 'playlist_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5ktgtio3chmwbraiyjkyf6wvn',
                        name: 'song_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'zktsnmbk214ctyefwkjya7yyb',
                        name: 'idx_playlist_song_playlist_id',
                        unique: false,
                        fieldIds: ['qcz9l2vw7d28kangjrcf1857l'],
                        createdAt: now,
                    },
                    {
                        id: 'qvz9kxu2xbvk5pprj13syrpj0',
                        name: 'playlist_song_pkey',
                        unique: true,
                        fieldIds: ['xgmoikmpcqy428acquoni733u'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '07cnc7vgdaxtfo9wgonqz5rv5',
                name: 'songs_album_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'wey7nxcmp4i5t0lgdgb2t4bz8',
                targetTableId: 'omv1l5zyi5min10iiew33qirs',
                sourceFieldId: '2xdwpb6f4k92vdvfufnfq6501',
                targetFieldId: 'ljeeuqyeymidghrhx3ehe4ti8',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '8xjzzb5qvbhsc0an6krl543ps',
                name: 'playlists_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'w5gjpa758vhjygti5ciu97ri0',
                targetTableId: '1bbo7xfnv1iva2e1g4wvegnf5',
                sourceFieldId: 'ttehfu91qsa1zt3ykewg76e1l',
                targetFieldId: 'dsfw2sbft9slcl5uvwoagzb10',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '9tdfvffhqqbgtk1yogt7zy7k2',
                name: 'songs_artist_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'wey7nxcmp4i5t0lgdgb2t4bz8',
                targetTableId: 'lo0qu9vhj7p4ivtmh75ianitt',
                sourceFieldId: '6n9sm4zkioh6umrwcp4q53edl',
                targetFieldId: 'ti4sfv1s5irkk0smwyeqghnwu',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'd1oa9279d9xji8b5tr1igfa9f',
                name: 'playlist_song_playlist_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'wwvgva66b5wxe3gmu3jthz3kd',
                targetTableId: 'w5gjpa758vhjygti5ciu97ri0',
                sourceFieldId: 'qcz9l2vw7d28kangjrcf1857l',
                targetFieldId: 'cmpkn7oc4tnqfbr5jdmr5afpc',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ei8makn2vhtzlr51yvpilqncx',
                name: 'playlist_song_song_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'wwvgva66b5wxe3gmu3jthz3kd',
                targetSchema: 'public',
                targetTableId: 'wey7nxcmp4i5t0lgdgb2t4bz8',
                sourceFieldId: '5ktgtio3chmwbraiyjkyf6wvn',
                targetFieldId: '3zwecxjaci6fczjfpmh22q6wh',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ff5gcorrrowpaovxb5ggg1eby',
                name: 'interactions_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'blosecajwasyvqjym6i9w9qpu',
                targetTableId: '1bbo7xfnv1iva2e1g4wvegnf5',
                sourceFieldId: '3z6yf3bikh7nz7ntdyhspgfzc',
                targetFieldId: 'dsfw2sbft9slcl5uvwoagzb10',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rcobiwp1wuqk2v7tvcfzy91qs',
                name: 'albums_artist_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'omv1l5zyi5min10iiew33qirs',
                targetTableId: 'lo0qu9vhj7p4ivtmh75ianitt',
                sourceFieldId: '61a72o357ug9sy3aet0bwshuk',
                targetFieldId: 'ti4sfv1s5irkk0smwyeqghnwu',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
