import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/laravel-spark-db.png';
import imageDark from '@/assets/templates/laravel-spark-db-dark.png';

const now = Date.now();

export const laravelSparkDb: Template = {
    slug: 'laravel-spark-database',
    name: 'Laravel Spark',
    shortDescription: 'Recurring billing solution for Laravel',
    description: 'A starter-kit for your next great SaaS application',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://github.com/laravel/spark-aurelius',
    diagram: {
        id: 'laravel_spark_db',
        name: 'laravel-spark-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '3jvmtsxycjfoe139op30zzhlz',
                name: 'team_subscriptions',
                schema: 'public',
                x: -547.3219335678851,
                y: -228.24948097507573,
                fields: [
                    {
                        id: '37h5tfskdps7rmp9us2uceq6c',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('team_subscriptions_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'nzbta5jmnf258kdchfqiylit2',
                        name: 'team_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zga7iw6n1q6fosentweehy7lb',
                        name: 'stripe_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'fe138jknzenrpxmybn18gyiah',
                        name: 'stripe_plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9afe5ufrgwznyge7ztudoc0o0',
                        name: 'quantity',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5a75wrotyz2g0ip2w5skwnwyy',
                        name: 'trial_ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gqvio9lgehtv8pri0u0go32ea',
                        name: 'ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kanw1laa5vfr5uouxxw3jzov1',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ppi5ztfmfh67jits6pq5yes9x',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'poo1nffzm647sq7hrbqpp1lvw',
                        name: 'team_subscriptions_pkey',
                        unique: true,
                        fieldIds: ['37h5tfskdps7rmp9us2uceq6c'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '4bxahy0gb1h3dyrtd2459qwvb',
                name: 'invoices',
                schema: 'public',
                x: 108.95988730761746,
                y: 138.05543975141467,
                fields: [
                    {
                        id: 'zplhikdjwej558393rgu5wsxi',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('invoices_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'nzcdiown05omd5pfp8bvqso1j',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5fyx2qkkbxsppr4tozd5josct',
                        name: 'team_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oof54cb2pyvtsd1unjooyfxvy',
                        name: 'provider_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3yove3hk4pdnlpk4oj5csruwz',
                        name: 'provider_plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tlvqsks3da74kq4fk80vz2fi2',
                        name: 'amount',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'nor9z7skycbwyjdytxi3s6alr',
                        name: 'total',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'hzz3pnoi87x0htllztuw079ad',
                        name: 'tax',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'y51cso8kguaxlffleiqhubdoi',
                        name: 'card_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm0pp8pu3013abiaheevskatqs',
                        name: 'billing_address',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'aafhr7qxqx15jyeitjw5rxtwp',
                        name: 'billing_city',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'saw9z3z4qcvyx87t58hxxovwa',
                        name: 'billing_state',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yhib760afvdargf39d90awcch',
                        name: 'billing_zip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1yc4aeauxjb8tvcgzxfm3znyw',
                        name: 'billing_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ogsfx4sscq471x94tcfbazcui',
                        name: 'vat_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cbox2xmtjema491daedwfgchg',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nsz71xz2c10todqm0b7x8pgzf',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vwgy8s2tuo1trv2ma5180uiof',
                        name: 'invoices_pkey',
                        unique: true,
                        fieldIds: ['zplhikdjwej558393rgu5wsxi'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5hxs7wpg67p88r4521wi8syep',
                name: 'notifications',
                schema: 'public',
                x: 1163.7853479712396,
                y: -197.1187205307031,
                fields: [
                    {
                        id: '6qsl64hukbivf2m2yanctaopx',
                        name: 'id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zdsjqtn7ihjg6t7bccpy8vl13',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7a2yjh7lksumxpk0vp5m8tyzl',
                        name: 'icon',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '81sn5cdvfs5bsxuxsfyr5erse',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '02xpsjtazmemsg9o0hh63bwhf',
                        name: 'action_text',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xtz16agynpqqmgslwznpksu5k',
                        name: 'action_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a6ztogu4es0q20c7my4vuy1o6',
                        name: 'read',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tbnqficb95tgel5wb3obx174h',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yynj32ludyklabh4qz6sjnsiq',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '46zk8ee827baophuq39oxf2n0',
                        name: 'idx_notifications_user_id_created_at',
                        unique: false,
                        fieldIds: [
                            'zdsjqtn7ihjg6t7bccpy8vl13',
                            'tbnqficb95tgel5wb3obx174h',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'ax4fbjaxzc3wzkjsbc32cxlwq',
                        name: 'notifications_pkey',
                        unique: true,
                        fieldIds: ['6qsl64hukbivf2m2yanctaopx'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '89xjr2o46iek3wzb8r7eej9r0',
                name: 'announcements',
                schema: 'public',
                x: 928.5143618095431,
                y: -421.8452789182581,
                fields: [
                    {
                        id: 'vzinhpw7l1u8sjl1jg1qcy63p',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('announcements_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'w2cv9qy96agjnd6mhdxmozpxw',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nnada99l55gu46noiurmvz5eu',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sdm18o43ctcs6t07orbo9vqyk',
                        name: 'action_text',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nr2dk9wn19sqpwfwljivj7m6m',
                        name: 'action_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'khogjyfb35l3hlrqeuzymnfry',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's3rmg7iklhkcfltn6ir0xgnog',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2gfoi6bm2apvw9cw3yiztk5g6',
                        name: 'announcements_pkey',
                        unique: true,
                        fieldIds: ['vzinhpw7l1u8sjl1jg1qcy63p'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'awdd4fwb2bu3x7135cs86zkhz',
                name: 'team_users',
                schema: 'public',
                x: -113.19393385672583,
                y: -205.18115189434653,
                fields: [
                    {
                        id: '021igiwy41c1jfhrd40ugbndx',
                        name: 'team_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tqgy5bjffa8rafp48pxrfnhv6',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8pvasrruu1npdypr5rz1pcas7',
                        name: 'role',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'yg4u0pmqn873ec8y1rltt27xc',
                        name: 'idx_team_users_team_id_user_id',
                        unique: false,
                        fieldIds: [
                            '021igiwy41c1jfhrd40ugbndx',
                            'tqgy5bjffa8rafp48pxrfnhv6',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'rnseay48dvtxmq7lcoka8iph5',
                        name: 'team_users_pkey',
                        unique: true,
                        fieldIds: [
                            '021igiwy41c1jfhrd40ugbndx',
                            'tqgy5bjffa8rafp48pxrfnhv6',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'dyct2wou6zaw3j3oepnaxw6qi',
                name: 'api_tokens',
                schema: 'public',
                x: 1069.3785389123366,
                y: 216.20009653382067,
                fields: [
                    {
                        id: '261md8r0ntxcalop6ialip4vb',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('api_tokens_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'yml91en4uxha1berq47n661eu',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2kcxypjuuwop4c8o389jekfqu',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '49g7o5vla8va8t344y7p9lcbl',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jr2h39t8ejz678xhkfb5cawwl',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rpw805wva55y9yr93kr82s4h4',
                        name: 'transient',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qavrwwjxhccmmtciwybkssyf2',
                        name: 'last_used_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'it2f67pg5qaboozfm9o1b7v1r',
                        name: 'expires_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6pwce5wd253r4bms6u2z47nrw',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'l1gw8cm8ecggag9pghk0pgvi3',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'gu5cjtp02iljswx1pypcs01kl',
                        name: 'idx_api_tokens_user_id_expires_at',
                        unique: false,
                        fieldIds: [
                            'yml91en4uxha1berq47n661eu',
                            'it2f67pg5qaboozfm9o1b7v1r',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'sudzw632z52onlaix20qp44g4',
                        name: 'api_tokens_pkey',
                        unique: true,
                        fieldIds: ['261md8r0ntxcalop6ialip4vb'],
                        createdAt: now,
                    },
                    {
                        id: 'rewq0hkvpqosmr0e4whh8uxbs',
                        name: 'api_tokens_token_key',
                        unique: true,
                        fieldIds: ['49g7o5vla8va8t344y7p9lcbl'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'dyr53kx47mi6qqosnbpblawrx',
                name: 'users',
                schema: 'public',
                x: 513.318817064524,
                y: 127.3519805410346,
                fields: [
                    {
                        id: 't7luke7y8ogkwumfxmooa70jm',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('users_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'hcgubljbqptmd3j3g7j1zva4i',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4wh2w3qvaecsawe7n8jxf9cul',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jcdq04nu4smidfbu3z3dhtctp',
                        name: 'email_verified_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q7qb9x22zxbd0h8uxvg9b7j2m',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'acei9o7l6vve1rk87utw4tcap',
                        name: 'remember_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6y18329rg227dbemxo052r5nt',
                        name: 'photo_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vph3us73jyozvmw91ymjx1sgm',
                        name: 'uses_two_factor_auth',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'n46p8pnzskj19dgjh0mui4l3l',
                        name: 'authy_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6fuchxoyqjzc6brp1kdcw7eg4',
                        name: 'country_code',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nv5q9h6tbzd12wydwj6qsjxln',
                        name: 'phone',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nrirhcg3dula877mp2tg3hs1q',
                        name: 'stripe_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6wymm09r8p402oj3zxnmfwcna',
                        name: 'two_factor_reset_code',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'h777hdxb4qntx3onxf4846tg6',
                        name: 'current_team_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8k5rtidl2cfigc3m61dh55pj9',
                        name: 'current_billing_plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7jylxl8s5ea4gg7tlwkuhvecd',
                        name: 'card_brand',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'd6na5l4kshiuzxppxwr68wyh3',
                        name: 'card_last_four',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mtpo6kip3q8po6jser5zn4wog',
                        name: 'card_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3nwo24a92ycmhibtn5wxfecxh',
                        name: 'billing_address',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'z44r9d201dy89zli8austinx9',
                        name: 'billing_address_line_2',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '32mp2nhighgp3gf30kykx9dbn',
                        name: 'billing_city',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5ybid22eod84ba2xii9rhnr8e',
                        name: 'billing_state',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6fhidkemuq1p6k1jr6pspe7bi',
                        name: 'billing_zip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ghn69851yk78u6car8e7w6xgi',
                        name: 'billing_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'khq0glqyk4yehku92np3t4b9d',
                        name: 'vat_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'k0z4qob80anbw3n2ob7y61njn',
                        name: 'extra_billing_information',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'aa6orp4j6uk9jvw3or9tyg98l',
                        name: 'trial_ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oct21boksdf5eh78v3gq721a2',
                        name: 'last_read_announcements_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ezk8twf5bz6u55xg9t79cqph7',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qvh7flrph4hnhcftxpql87au4',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qkx4zz1fyes2kdjist818awug',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['t7luke7y8ogkwumfxmooa70jm'],
                        createdAt: now,
                    },
                    {
                        id: 'sgw20bq4otfk19bopyuwk91bi',
                        name: 'users_email_key',
                        unique: true,
                        fieldIds: ['4wh2w3qvaecsawe7n8jxf9cul'],
                        createdAt: now,
                    },
                    {
                        id: 'j7acx0mvr5ow2z006fxc50ugg',
                        name: 'idx_users_email',
                        unique: false,
                        fieldIds: ['4wh2w3qvaecsawe7n8jxf9cul'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'foix2fjym2dbo1v3lycoc9ld7',
                name: 'teams',
                schema: 'public',
                x: -346.97871178498485,
                y: 598.1984969413621,
                fields: [
                    {
                        id: '7do8qklbp9i98s27yx0le0v7j',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('teams_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'ly6dam6u5qyb7ktsegzb8ru9i',
                        name: 'owner_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oqxomaynw3kmifkuhu5gde0d0',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'z7m2il14zuiz3qtc5r2cly110',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'l33bb50b4dqzkdfazdfmf2x9g',
                        name: 'photo_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tuw70rn6qilumweo5d3loycet',
                        name: 'stripe_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'szrh7bfnec0t8hlogro8zyp4a',
                        name: 'current_billing_plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hrixv4yjhcnrfkhyj18x64cf5',
                        name: 'card_brand',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q50nndo05zae0t0v04qpm65eh',
                        name: 'card_last_four',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ezuwxy8kyx65pxjhpzs0ssnbr',
                        name: 'card_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cdhgc4hf1xv0qojjb9z6gzmkt',
                        name: 'billing_address',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o2v2ufdkj94o5nj6l5ago08q4',
                        name: 'billing_address_line_2',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6gz8x1ktjn2g9tcv1grsf47op',
                        name: 'billing_city',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '99w636vdtw3exws3zod1b56ly',
                        name: 'billing_state',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i0kyd9g6by9pleqdojahg7wde',
                        name: 'billing_zip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'c1fs08z68vbae40r84lncwh69',
                        name: 'billing_country',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6y7o4yttpdcoxi1rstld1tdqr',
                        name: 'vat_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6ukk4x3zbcmi8xx10pm31zvhf',
                        name: 'extra_billing_information',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lwn30dqlkw3x8idth6bgl78xe',
                        name: 'trial_ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8ihhsxmcqh0r120ubmdz7w24i',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cxqujcrc9uezdksrf6a3sdsh9',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'im80uyvya0psoo67rhltg2f8s',
                        name: 'teams_pkey',
                        unique: true,
                        fieldIds: ['7do8qklbp9i98s27yx0le0v7j'],
                        createdAt: now,
                    },
                    {
                        id: 'h2gg3jr91cgrymzjy6a9sz2c8',
                        name: 'teams_slug_key',
                        unique: true,
                        fieldIds: ['z7m2il14zuiz3qtc5r2cly110'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'i0x468sfe0orhcn5pl6fvctl0',
                name: 'password_resets',
                schema: 'public',
                x: 1306.442178810179,
                y: 672.8235809118509,
                fields: [
                    {
                        id: '4kfq3wdknxrbo3fxqv7el0qg7',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'x09zb6gjt7wdbooo5cb4dbb9j',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '70z8qcdbdgnt89nj0fsaq7b6t',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'me72i6ghzatln2liqaka31qys',
                        name: 'password_resets_pkey',
                        unique: true,
                        fieldIds: ['4kfq3wdknxrbo3fxqv7el0qg7'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'mlsskjr0dy8ui6uq81l22e0cp',
                name: 'performance_indicators',
                schema: 'public',
                x: 1045.4291946956632,
                y: 682.055941623104,
                fields: [
                    {
                        id: 'fztvo3qtbsuak5l1qe77floi3',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('performance_indicators_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'djaylwov03o19fpkbu1p22spq',
                        name: 'monthly_recurring_revenue',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'gwvhemf09j09seio53576x3un',
                        name: 'yearly_recurring_revenue',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'ftzeqeyifkwzb9smylwbe04a7',
                        name: 'daily_volume',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'm0h6x57a5vycqjllwpx0gn2n2',
                        name: 'new_users',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '657gnbtfzipgitf47hjwfa2vr',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '91df0rgshayr9wmcuz3s3yra6',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '9tqmdgu574flzwo30nlwfayd2',
                        name: 'performance_indicators_pkey',
                        unique: true,
                        fieldIds: ['fztvo3qtbsuak5l1qe77floi3'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'pygvuwu2zvvci6a47wzh7pioj',
                name: 'invitations',
                schema: 'public',
                x: 431.2628754414195,
                y: 718.1453603925248,
                fields: [
                    {
                        id: 'pt3b4qn4njj4eomj0kvv38p70',
                        name: 'id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '10p0uvi5oy4zs6ozqbr2awl76',
                        name: 'team_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a7otts0e7rxskcpyr6kcr763k',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'c7zyanlfu1r28gbojd8fuw4bb',
                        name: 'role',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3j20j1jtx3gprznpacta0cv7s',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3msnr6vw2mvdr04bpz9lk8lik',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4a1i9879g73v0i2wwcbqmtxm1',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8kxhrf1pdue9g8z4vdajp0hzv',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '1hmm4aq12z9obssjblmhu7lgc',
                        name: 'invitations_pkey',
                        unique: true,
                        fieldIds: ['pt3b4qn4njj4eomj0kvv38p70'],
                        createdAt: now,
                    },
                    {
                        id: 'y7gxetceqqa5n7qolqb5hr731',
                        name: 'invitations_token_key',
                        unique: true,
                        fieldIds: ['3msnr6vw2mvdr04bpz9lk8lik'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'qyk9l1afii25znsdwtq7ac823',
                name: 'subscriptions',
                schema: 'public',
                x: 535.754960976059,
                y: -437.92228397368166,
                fields: [
                    {
                        id: 'd3omubr5vxb9hg4wyim8l3sxc',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('subscriptions_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'h6z443oalimgg5cbtsjdkjx9k',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'spjiaursn6keivjeld9xzsufl',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0uiu9ov6ef47kspq6o0jy1ez2',
                        name: 'stripe_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'g7rqzqs3r4q2tzpv12ya3r71l',
                        name: 'stripe_plan',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ugx33969bkrm0qhxrqth6bphr',
                        name: 'stripe_status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '50qg2uv0ulhm8mu0lrx839pfn',
                        name: 'quantity',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8t0xhytz6stqxnxdv2t10swon',
                        name: 'trial_ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'blb3osdhvvld4fsoazhp7121n',
                        name: 'ends_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't48jobc4xslo39sr8z6769r32',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wb7fhj8dbz3jmk2poupyk18il',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ih93q8hpimbyu1ndmei9qir0o',
                        name: 'subscriptions_pkey',
                        unique: true,
                        fieldIds: ['d3omubr5vxb9hg4wyim8l3sxc'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '50qkl64brmv9gw9kr3vzalsf1',
                name: 'announcements_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '89xjr2o46iek3wzb8r7eej9r0',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'w2cv9qy96agjnd6mhdxmozpxw',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5vq90hp8wfqeo5ecriydsj77i',
                name: 'invitations_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'pygvuwu2zvvci6a47wzh7pioj',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'a7otts0e7rxskcpyr6kcr763k',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'curtlz417gcs4uskjmekbpy3d',
                name: 'invoices_team_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '4bxahy0gb1h3dyrtd2459qwvb',
                targetTableId: 'foix2fjym2dbo1v3lycoc9ld7',
                sourceFieldId: '5fyx2qkkbxsppr4tozd5josct',
                targetFieldId: '7do8qklbp9i98s27yx0le0v7j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hx93kg5pld1dmnjkml295budo',
                name: 'team_users_team_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'awdd4fwb2bu3x7135cs86zkhz',
                targetTableId: 'foix2fjym2dbo1v3lycoc9ld7',
                sourceFieldId: '021igiwy41c1jfhrd40ugbndx',
                targetFieldId: '7do8qklbp9i98s27yx0le0v7j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ls7bcyp19xis8xrp5nxlsd6vg',
                name: 'subscriptions_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'qyk9l1afii25znsdwtq7ac823',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'h6z443oalimgg5cbtsjdkjx9k',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'mplfehxojkx9rv9b1u9z5rcx8',
                name: 'teams_owner_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'foix2fjym2dbo1v3lycoc9ld7',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'ly6dam6u5qyb7ktsegzb8ru9i',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 's8n7oinpqoxgd8gsehqqisxdm',
                name: 'notifications_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '5hxs7wpg67p88r4521wi8syep',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'zdsjqtn7ihjg6t7bccpy8vl13',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vh9e8se2mrt3p4al5uffybh0r',
                name: 'invoices_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '4bxahy0gb1h3dyrtd2459qwvb',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'nzcdiown05omd5pfp8bvqso1j',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'wa6p46cu4s9xexfowury339ru',
                name: 'team_subscriptions_team_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3jvmtsxycjfoe139op30zzhlz',
                targetTableId: 'foix2fjym2dbo1v3lycoc9ld7',
                sourceFieldId: 'nzbta5jmnf258kdchfqiylit2',
                targetFieldId: '7do8qklbp9i98s27yx0le0v7j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ynitl1nohp9f3w9wl1zpnq4dt',
                name: 'api_tokens_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'dyct2wou6zaw3j3oepnaxw6qi',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'yml91en4uxha1berq47n661eu',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'z9oh68wp0hbpcw0ihw1sd3b43',
                name: 'invitations_team_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'pygvuwu2zvvci6a47wzh7pioj',
                targetTableId: 'foix2fjym2dbo1v3lycoc9ld7',
                sourceFieldId: '10p0uvi5oy4zs6ozqbr2awl76',
                targetFieldId: '7do8qklbp9i98s27yx0le0v7j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'zkdba7smxqg1m0q9kz7bh6t83',
                name: 'team_users_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'awdd4fwb2bu3x7135cs86zkhz',
                targetTableId: 'dyr53kx47mi6qqosnbpblawrx',
                sourceFieldId: 'tqgy5bjffa8rafp48pxrfnhv6',
                targetFieldId: 't7luke7y8ogkwumfxmooa70jm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
