import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/lobsters-db.png';
import imageDark from '@/assets/templates/lobsters-db-dark.png';

const now = Date.now();

export const lobstersDb: Template = {
    slug: 'lobsters-database',
    name: 'Lobsters',
    shortDescription: 'Computing-focused community centered',
    description:
        'Around link aggregation and discussion - Example database schema diagram for lobsters',
    image,
    imageDark,
    tags: ['Postgres', 'Example Apps'],
    featured: false,
    url: 'https://github.com/SukhjinderArora/lobsters-clone',
    diagram: {
        id: 'lobsters_db',
        name: 'lobsters-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.MYSQL,
        tables: [
            {
                id: '0esn3myj5fkhmni76sz24uh1l',
                name: 'moderation_logs',
                schema: 'template1-db',
                x: 123.66934023447857,
                y: 478.0866225058478,
                fields: [
                    {
                        id: '21hhgymxf90do74h1w1q6mm52',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'h7ko8616u9ta7obi2uxt1vtfm',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5ysqav2xzsya4b651h5h8dqwm',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jetuh9p8z0ws0ghqcnuqg0og5',
                        name: 'action',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ydznphqxtpe57a1a3i8ir4oj5',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'apvn8uks8wnz79vajvkfnffi0',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['21hhgymxf90do74h1w1q6mm52'],
                        createdAt: now,
                    },
                    {
                        id: '4ydtptqwm6sytm5zs7n8hkg2h',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['h7ko8616u9ta7obi2uxt1vtfm'],
                        createdAt: now,
                    },
                    {
                        id: 'g89dr29ywnv09dshg8cjid5o7',
                        name: 'user_id',
                        unique: false,
                        fieldIds: ['5ysqav2xzsya4b651h5h8dqwm'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6x5l6o01cdnqxpdrnc6suhf2m',
                name: 'invitations',
                schema: 'template1-db',
                x: 1097.940779583232,
                y: 343.9145915377326,
                fields: [
                    {
                        id: 'rthxkab63nht1rtk4na89vvr4',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'n8qcyagm5r36v0g7c5jpp0bjx',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '54x4z9j1euuwxew1839afvgsv',
                        name: 'email',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '24gjs67cvg9c9hksywhrpw5qr',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'o7njvpa44tev2vj6y9m83zkge',
                        name: 'used_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '3j04y23qgcbay7fpj9gn1jx19',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['rthxkab63nht1rtk4na89vvr4'],
                        createdAt: now,
                    },
                    {
                        id: 'c14qtbgt7gczwfdkdkau7ut70',
                        name: 'user_id',
                        unique: false,
                        fieldIds: ['n8qcyagm5r36v0g7c5jpp0bjx'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '8nhj3tjdvouvomt1940t7pg5b',
                name: 'tags',
                schema: 'template1-db',
                x: 900,
                y: -349.99999999999994,
                fields: [
                    {
                        id: 't88yt32caepwcwpbdwq6yunhp',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0w4n09pj2h388py97grbkddce',
                        name: 'tag_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'huvg0582nmyb5fo8rtsb99r27',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'tuai1c8nsb2m9v2n13kjz9dvn',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9wdx24kas7swv8vcobogqncmd',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'f4j6w753d5x30qi7txas9j4lf',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['t88yt32caepwcwpbdwq6yunhp'],
                        createdAt: now,
                    },
                    {
                        id: 'ij668mgt7mde0t6p4n6vi7885',
                        name: 'tag_name',
                        unique: true,
                        fieldIds: ['0w4n09pj2h388py97grbkddce'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '8zj7bm5sobx6lc8inxjiw08cs',
                name: 'stories',
                schema: 'template1-db',
                x: 172.99933138344545,
                y: -147.9955551822826,
                fields: [
                    {
                        id: '9zhevj9k3sr71qunu9eto3k0j',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'omqqnbq8s94zukws29rjtrhp0',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fs6ghtypl0qot5umiqjwn6hdr',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '85m7zkip1yvit4zst54k6mo8t',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ofiqtiv5blvk2psn5t83kmncc',
                        name: 'url',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'b9jzb64nbhzhnp3yiy7r9k7ku',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'c32z1zomwho4qfm3imh6mxnx2',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oi1zd877r9ren51m98r7hv0b5',
                        name: 'moderated',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'blsninelkz0os2skws9d261md',
                        name: 'score',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'h9ol2i4zc00s858yj43x0r0cz',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['9zhevj9k3sr71qunu9eto3k0j'],
                        createdAt: now,
                    },
                    {
                        id: 'qua7fpqb3ndh30wjalq3sq9ft',
                        name: 'user_id',
                        unique: false,
                        fieldIds: ['omqqnbq8s94zukws29rjtrhp0'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '9wxfmjnnje5w59yerd73cz9dw',
                name: 'users',
                schema: 'template1-db',
                x: 623.1687054530346,
                y: -29.093576670229254,
                fields: [
                    {
                        id: 'shvxpnxhrumb5o1wafxj07moo',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'natb552qnte01wjfzk7mf8ry0',
                        name: 'username',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '2fo2zvpvhsi609mrz75zgpgqy',
                        name: 'email',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'crae77v32lox343aoabgcu8aw',
                        name: 'encrypted_password',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'a01vyo0xc68jr2gzv1dr58pw8',
                        name: 'password_digest',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'cmajazva1xeihpzytrsuknqnl',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kj1qm117k1mon7vi8znotgqm7',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uagg25l03hz7asaivjv8il1ib',
                        name: 'settings',
                        type: {
                            id: 'json',
                            name: 'json',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4z5cajd9g919xfz5r3r1qhiz6',
                        name: 'banned',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'kuqq40wp2jzc8y10m2ptl8mc0',
                        name: 'is_admin',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5qjl9x9elrve58s3bfyg0x0hz',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['shvxpnxhrumb5o1wafxj07moo'],
                        createdAt: now,
                    },
                    {
                        id: '5ffp4jrx998r77jdujprs6ozt',
                        name: 'username',
                        unique: true,
                        fieldIds: ['natb552qnte01wjfzk7mf8ry0'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bmspaixcc45d8jk5fz8vt7050',
                name: 'ar_internal_metadata',
                schema: 'template1-db',
                x: -429.9631042251518,
                y: 637.9808834960214,
                fields: [
                    {
                        id: 'xz1icgseeq3ovbb7z31d66vi1',
                        name: 'key',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '7kgige8lmojblyssuzjpanryo',
                        name: 'value',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '7wwr4uasthbck7z8tdnjpzm7v',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ypyxb7qqdo2jp7sier21gzgv9',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xxc4la3pco7uvm4m87oxzdi8b',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['xz1icgseeq3ovbb7z31d66vi1'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c5r9i6m7x1vagsnj5kkhzo9ej',
                name: 'hidden_stories',
                schema: 'template1-db',
                x: 671.5181135791465,
                y: 599.3883097506239,
                fields: [
                    {
                        id: 'w4kgz2l7iiz1lvdd71z935glc',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bsa025se8d113zak2hp04ny5k',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4uqxqamzp2k18pgq2dgbcwlv4',
                        name: 'hidden_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ljqgccfbcxqpwzrlawem53wty',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'w4kgz2l7iiz1lvdd71z935glc',
                            'bsa025se8d113zak2hp04ny5k',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'tndifhhdahgwf83iylebga6lq',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['bsa025se8d113zak2hp04ny5k'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'gulkegqq5s0x6jcpa1tulvoo2',
                name: 'votes',
                schema: 'template1-db',
                x: 192.8932188134524,
                y: -677.8174593052022,
                fields: [
                    {
                        id: 'gjj355pgsoxca1mjlliw91kga',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9jubc2tz9e96uqq00osf2a0n9',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '02i1fxp0hyc6stx29u1imhymj',
                        name: 'comment_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vb0snqwvsfdwapchggif7943p',
                        name: 'vote',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pysfn1qhipt6yf8w4kw9qlpp5',
                        name: 'voted_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '9pfqj6wacxxuv8y6076l8kqzu',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'gjj355pgsoxca1mjlliw91kga',
                            '9jubc2tz9e96uqq00osf2a0n9',
                            '02i1fxp0hyc6stx29u1imhymj',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'bfsccksiuqpr5i04bidh89kjz',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['9jubc2tz9e96uqq00osf2a0n9'],
                        createdAt: now,
                    },
                    {
                        id: '7end0b184a30shiyytyglcccf',
                        name: 'comment_id',
                        unique: false,
                        fieldIds: ['02i1fxp0hyc6stx29u1imhymj'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jh8ibbu5ujypvs3v7mvonb7ic',
                name: 'saved_stories',
                schema: 'template1-db',
                x: -311.0309810787983,
                y: -157.18966268712256,
                fields: [
                    {
                        id: 'njisjg85dvav35ef72nkfi8hb',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0jqum4f9sa3ayfsx6661eqx1h',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ldr49z7wra5nhk7rjaq5nbuck',
                        name: 'saved_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'i6fvafiicjg66znpwusae91zt',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'njisjg85dvav35ef72nkfi8hb',
                            '0jqum4f9sa3ayfsx6661eqx1h',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'y25sjqevluwtad09scm7mkcsy',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['0jqum4f9sa3ayfsx6661eqx1h'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'mgfnl610ri6uf954o5aqzkxlz',
                name: 'comments',
                schema: 'template1-db',
                x: -298.34185572378647,
                y: -487.7154937881493,
                fields: [
                    {
                        id: 'noumroprztpi610y3ak6rk281',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '81tp6ws27oibs7g9cyuwed7tv',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vizwjv6dwzhtwiksbgyd7skom',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ffruvi2ydbtv6agub9ibzj0fc',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'cpy0wkkb00nkstr6szhiimzfs',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6hslr8hncmobcsff734m6devv',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xqqlyjzgmgbztb7lscjbh3owh',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['noumroprztpi610y3ak6rk281'],
                        createdAt: now,
                    },
                    {
                        id: '4l0mx62tx8gmu5xbv5pu2p4m3',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['81tp6ws27oibs7g9cyuwed7tv'],
                        createdAt: now,
                    },
                    {
                        id: '9ojyf1ca2bdjv2l89eiwrejkc',
                        name: 'user_id',
                        unique: false,
                        fieldIds: ['vizwjv6dwzhtwiksbgyd7skom'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rqmsv56dskx4lbsitwc2dxzwq',
                name: 'schema_migrations',
                schema: 'template1-db',
                x: 122.04134059256535,
                y: 865.593242361952,
                fields: [
                    {
                        id: 'nb2ppkolr4keszfi8vmkbuq5x',
                        name: 'version',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'n0m23qqv7rma3d6i7ik86fl9m',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['nb2ppkolr4keszfi8vmkbuq5x'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rz7hh0d24mgp2e3pnqh2pgjem',
                name: 'messages',
                schema: 'template1-db',
                x: 1184.1754334714758,
                y: -104.02199763592256,
                fields: [
                    {
                        id: 'u5a9h1iqjjrczscqe47u1xddw',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kycu1ck60p5jdubmvcv538ctv',
                        name: 'sender_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'uj0fvw4nal00c1bbttw3kw4x2',
                        name: 'recipient_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mlyo4ieba7moxvoczghl331ec',
                        name: 'subject',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'jt84imdzs0wav71n7kgoyrfdm',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'njzqol7jf4adr79o5rcb7ia6w',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ushq7y57kizavsc5fs3h8sr9d',
                        name: 'read_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5o83ckvpc3utxcnevpso6xho9',
                        name: 'deleted_by_sender',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '52znmere91ed75cqg9gjckq94',
                        name: 'deleted_by_recipient',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'biqwp3qorbfqq6z6mc5mi71uu',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['u5a9h1iqjjrczscqe47u1xddw'],
                        createdAt: now,
                    },
                    {
                        id: 'o4ntvss0g2p9nwz7itcqmiwx9',
                        name: 'sender_id',
                        unique: false,
                        fieldIds: ['kycu1ck60p5jdubmvcv538ctv'],
                        createdAt: now,
                    },
                    {
                        id: 'xghta3vlhhv0n54jtirue4ld2',
                        name: 'recipient_id',
                        unique: false,
                        fieldIds: ['uj0fvw4nal00c1bbttw3kw4x2'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vyocfr4c0h0mczrcnst51bn5e',
                name: 'story_tags',
                schema: 'template1-db',
                x: 499.99999999999994,
                y: -349.99999999999994,
                fields: [
                    {
                        id: 'tvcn3axepfbhabumofkp69dr7',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mv7s4vagr9itpxj8a49ldy1wu',
                        name: 'tag_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'h9d776e5tqbbbpnpqh0ln37ni',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'tvcn3axepfbhabumofkp69dr7',
                            'mv7s4vagr9itpxj8a49ldy1wu',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'ybbdt8gyuqi08qs554mw2xc8q',
                        name: 'tag_id',
                        unique: false,
                        fieldIds: ['mv7s4vagr9itpxj8a49ldy1wu'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'y545uaplf9lfu57cy7rzydmdr',
                name: 'domains',
                schema: 'template1-db',
                x: -159.0566808953813,
                y: 712.7192699893121,
                fields: [
                    {
                        id: 'lz7ntpwvnj86dvtn22zfzeogd',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xxm1f7jw6c9cdtnm06vvbpmv9',
                        name: 'domain',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ed5n0gyse2796jikar5iv0joq',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '62fi68o9gduwkdx34bieuqylc',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'me1khgep9z9xxg39enogllw4b',
                        name: 'banned',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'oyf3mo3gsn1olz93brf7jdxjh',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['lz7ntpwvnj86dvtn22zfzeogd'],
                        createdAt: now,
                    },
                    {
                        id: '7fead2x6n02gfl4axno7rdav3',
                        name: 'domain',
                        unique: true,
                        fieldIds: ['xxm1f7jw6c9cdtnm06vvbpmv9'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zypz8joo0zka4c3epzavwxf11',
                name: 'moderations',
                schema: 'template1-db',
                x: -373.94976977199997,
                y: 273.86885893836813,
                fields: [
                    {
                        id: 'i2wxi877h7mt5gvw9c6z0d981',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ro7w4qtopchdt65e0ksfhoidv',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pnd5hvg8usvb20bavk3j5ruiw',
                        name: 'story_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '76imw6tu4afs0om0otdxcjozp',
                        name: 'comment_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'iieahrjwssmhmppecypy021pn',
                        name: 'reason',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'jia3rurh6z5z6h2pectcuwub1',
                        name: 'suggested_action',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '7qpa60pn9mjpg6zrvg1pmurl3',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'aycd9xvo3aqfev0y69otts5a4',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['i2wxi877h7mt5gvw9c6z0d981'],
                        createdAt: now,
                    },
                    {
                        id: 'eabnd4h8yw95jf52v54k7xq0j',
                        name: 'user_id',
                        unique: false,
                        fieldIds: ['ro7w4qtopchdt65e0ksfhoidv'],
                        createdAt: now,
                    },
                    {
                        id: 'nymwmr9tjtiqpqz06kidx3zk9',
                        name: 'story_id',
                        unique: false,
                        fieldIds: ['pnd5hvg8usvb20bavk3j5ruiw'],
                        createdAt: now,
                    },
                    {
                        id: 'hbzri06emmuowfz5nstqdd3yy',
                        name: 'comment_id',
                        unique: false,
                        fieldIds: ['76imw6tu4afs0om0otdxcjozp'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '5ehh4fizbayu83h22h5jwm3ih',
                name: 'stories_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'omqqnbq8s94zukws29rjtrhp0',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5sqj6ygjsxwu1vnapmf3vt1yu',
                name: 'votes_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'gulkegqq5s0x6jcpa1tulvoo2',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: '9jubc2tz9e96uqq00osf2a0n9',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6xt8hds5qrkt68td13rtud5id',
                name: 'invitations_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: '6x5l6o01cdnqxpdrnc6suhf2m',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'n8qcyagm5r36v0g7c5jpp0bjx',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '79z2vmxn74i9wdhisgtmlbm43',
                name: 'hidden_stories_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'c5r9i6m7x1vagsnj5kkhzo9ej',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: 'bsa025se8d113zak2hp04ny5k',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '8634m9a6vuq0txn79hkuotj6z',
                name: 'moderation_logs_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: '0esn3myj5fkhmni76sz24uh1l',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: '5ysqav2xzsya4b651h5h8dqwm',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '8wag23xsyxburegit2hw65hiu',
                name: 'votes_ibfk_3',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'gulkegqq5s0x6jcpa1tulvoo2',
                targetTableId: 'mgfnl610ri6uf954o5aqzkxlz',
                sourceFieldId: '02i1fxp0hyc6stx29u1imhymj',
                targetFieldId: 'noumroprztpi610y3ak6rk281',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '9067j6k18t53zhsvhkozix3mc',
                name: 'messages_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'rz7hh0d24mgp2e3pnqh2pgjem',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'uj0fvw4nal00c1bbttw3kw4x2',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'coglcss78m94skqppr3798vfg',
                name: 'votes_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'gulkegqq5s0x6jcpa1tulvoo2',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'gjj355pgsoxca1mjlliw91kga',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'dbjqtl75u46wtb4zx24rbdx76',
                name: 'moderation_logs_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: '0esn3myj5fkhmni76sz24uh1l',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: 'h7ko8616u9ta7obi2uxt1vtfm',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'h2044xtyk9xgu4woo57dk9hsf',
                name: 'messages_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'rz7hh0d24mgp2e3pnqh2pgjem',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'kycu1ck60p5jdubmvcv538ctv',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'i241xpd61n0hrooeuhflymjj2',
                name: 'story_tags_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'vyocfr4c0h0mczrcnst51bn5e',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: 'tvcn3axepfbhabumofkp69dr7',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ic7fqns3unn28xatgc18ksnjp',
                name: 'moderations_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'zypz8joo0zka4c3epzavwxf11',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: 'pnd5hvg8usvb20bavk3j5ruiw',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'lc7t54iw3gumy53fily0y4rba',
                name: 'moderations_ibfk_3',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'zypz8joo0zka4c3epzavwxf11',
                targetTableId: 'mgfnl610ri6uf954o5aqzkxlz',
                sourceFieldId: '76imw6tu4afs0om0otdxcjozp',
                targetFieldId: 'noumroprztpi610y3ak6rk281',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'macovvlt998u2g04yrh5sg5tv',
                name: 'moderations_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'zypz8joo0zka4c3epzavwxf11',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'ro7w4qtopchdt65e0ksfhoidv',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'n470fjpfqp324im65s70pfd7u',
                name: 'hidden_stories_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'c5r9i6m7x1vagsnj5kkhzo9ej',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'w4kgz2l7iiz1lvdd71z935glc',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'nuv5jpjfduedkfnp2r86j5un3',
                name: 'saved_stories_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'jh8ibbu5ujypvs3v7mvonb7ic',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'njisjg85dvav35ef72nkfi8hb',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rqep2txn9v6zygasn2k1bsi8k',
                name: 'story_tags_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'vyocfr4c0h0mczrcnst51bn5e',
                targetTableId: '8nhj3tjdvouvomt1940t7pg5b',
                sourceFieldId: 'mv7s4vagr9itpxj8a49ldy1wu',
                targetFieldId: 't88yt32caepwcwpbdwq6yunhp',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tr9e25q0cxcmrkr2d2880mn6q',
                name: 'comments_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'mgfnl610ri6uf954o5aqzkxlz',
                targetTableId: '9wxfmjnnje5w59yerd73cz9dw',
                sourceFieldId: 'vizwjv6dwzhtwiksbgyd7skom',
                targetFieldId: 'shvxpnxhrumb5o1wafxj07moo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'us0oouzbi73es19f9aenyngrm',
                name: 'saved_stories_ibfk_2',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'jh8ibbu5ujypvs3v7mvonb7ic',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: '0jqum4f9sa3ayfsx6661eqx1h',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'v4aanav49zd824blgerez22it',
                name: 'comments_ibfk_1',
                sourceSchema: 'template1-db',
                targetSchema: 'template1-db',
                sourceTableId: 'mgfnl610ri6uf954o5aqzkxlz',
                targetTableId: '8zj7bm5sobx6lc8inxjiw08cs',
                sourceFieldId: '81tp6ws27oibs7g9cyuwed7tv',
                targetFieldId: '9zhevj9k3sr71qunu9eto3k0j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
