import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/octobox-db.png';
import imageDark from '@/assets/templates/octobox-db-dark.png';

const now = Date.now();

export const octoboxDb: Template = {
    slug: 'octobox-database',
    name: 'Octobox',
    shortDescription: 'GitHub notifications Manager',
    description:
        'Octobox helps you manage your GitHub notifications efficiently so you can spend less time managing and more time building.',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Rails'],
    featured: true,
    url: 'https://github.com/octobox/octobox',
    diagram: {
        id: 'octobox_db',
        name: 'octobox-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '37np0qffoyukcatnqkwd2szdh',
                name: 'users',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'zp2xsp1vy5v7hvg33xmjgoio2',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'p4baw2bc3hpt7px5qwf7v8cm8',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'q8pfwtofmh1ztez7uxakgzd8g',
                        name: 'github_login',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lpcbm9mdwfg9vwopyi3aj15op',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'l2yn50oesv1r4ews99n5hcz79',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'svb1wb0ypg97qhbei1p9y23z2',
                        name: 'last_synced_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'udaga2r9cqxubcaprjwwmtqba',
                        name: 'refresh_interval',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kgqffmx5mgczgkas7mal6o5f9',
                        name: 'api_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'y9p03xk7jp9rqvrmvghc5em30',
                        name: 'sync_job_id',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'amlkpvbpb2kg0lrbov7dqka40',
                        name: 'encrypted_access_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gj5w5n78utgk2u9l887xgb4ao',
                        name: 'encrypted_access_token_iv',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1afk8adyebbi97ael86ksiys2',
                        name: 'encrypted_personal_access_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'aody93at5irbv0spetf1dz92y',
                        name: 'encrypted_personal_access_token_iv',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xj4z08juky73pze9e54kw0cx1',
                        name: 'encrypted_app_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't6s5jdw2lbnmb23d29xlq2ptk',
                        name: 'encrypted_app_token_iv',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jademvmj5bqdaxka30xg73ljr',
                        name: 'theme',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '73mig1zevf6ksb2cfbfmz029x',
                        name: 'display_comments',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'psykmdoy821o4i7bna063vf0w',
                        name: 'users_github_id_unique',
                        unique: true,
                        fieldIds: ['p4baw2bc3hpt7px5qwf7v8cm8'],
                        createdAt: now,
                    },
                    {
                        id: 'j8fpv7ek7wnguqucasnak3yn8',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['zp2xsp1vy5v7hvg33xmjgoio2'],
                        createdAt: now,
                    },
                    {
                        id: 'tipumn37rqx90t20ua53ur9pm',
                        name: 'users_api_token_unique',
                        unique: true,
                        fieldIds: ['kgqffmx5mgczgkas7mal6o5f9'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5az7tvlsq0h06z0u44eljxvat',
                name: 'notifications',
                schema: 'public',
                x: -99.99999999999991,
                y: 533.0127018922194,
                fields: [
                    {
                        id: '0cjyot7ss345hirj0b0ptr63w',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vhf76uw2vbyxe31h1g5fbwtcu',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ffiuvd0ho72iq0sl3fm3wafsk',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hgb2xijbp1xd9cyahvgnug16h',
                        name: 'repository_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1mjpxo4aw51bcirxt3oc0wlv5',
                        name: 'repository_full_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3x7b6mfnsf2vd4vhzb6c85vtm',
                        name: 'subject_title',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wrr7uxbba3rymy1s1m3h8gbhr',
                        name: 'subject_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f2723chewvy2meyi7gtnlw9bs',
                        name: 'subject_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wmf1fv16xs6jzsv9tv2kprou5',
                        name: 'reason',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ds9snjgz5osde9ekyp3vez7zg',
                        name: 'unread',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xc01d8d5zks278mz92momtl19',
                        name: 'last_read_at',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sm37qq714idyqja873xvs0t52',
                        name: 'url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j7lzie22rwtkzdc1cbeksi1lz',
                        name: 'archived',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1nb3urlsbsw78i6ks4mv7x2fs',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zkk8jrwq8lzuvajn4k5iabe68',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '51uu0775w7nv1bu2kzjdzmpcx',
                        name: 'starred',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q35d8p8n7nnz993lur3qdwptz',
                        name: 'repository_owner_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'el0xkn5eq5ech3g00swfsc0uv',
                        name: 'latest_comment_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't7zohdm6eqb3i7d7cwtn7w2mj',
                        name: 'muted_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vfxxn1ptiynvu7n3e3orbuv77',
                        name: 'notifications_user_id_archived_updated_at_index',
                        unique: false,
                        fieldIds: [
                            'vhf76uw2vbyxe31h1g5fbwtcu',
                            'j7lzie22rwtkzdc1cbeksi1lz',
                            'zkk8jrwq8lzuvajn4k5iabe68',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'sa5v1imisfqhruhl2f371ybug',
                        name: 'notifications_subject_url_index',
                        unique: false,
                        fieldIds: ['wrr7uxbba3rymy1s1m3h8gbhr'],
                        createdAt: now,
                    },
                    {
                        id: 'p8wqgz88g1u35vwtbvdumz5n7',
                        name: 'notifications_user_id_github_id_unique',
                        unique: true,
                        fieldIds: [
                            'vhf76uw2vbyxe31h1g5fbwtcu',
                            'ffiuvd0ho72iq0sl3fm3wafsk',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '3qqa6ymeuvgszrdhyxnm1nyw5',
                        name: 'notifications_pkey',
                        unique: true,
                        fieldIds: ['0cjyot7ss345hirj0b0ptr63w'],
                        createdAt: now,
                    },
                    {
                        id: '0pfxupcv8kazc5j0e6lqeaaiv',
                        name: 'notifications_muted_at_index',
                        unique: false,
                        fieldIds: ['t7zohdm6eqb3i7d7cwtn7w2mj'],
                        createdAt: now,
                    },
                    {
                        id: '6q0lpdyq1cdvq8s8f1tt4tc1l',
                        name: 'notifications_repository_full_name_index',
                        unique: false,
                        fieldIds: ['1mjpxo4aw51bcirxt3oc0wlv5'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c0bbaby788cbi5gllfx8y5kvy',
                name: 'repositories',
                schema: 'public',
                x: 300.0000000000001,
                y: 533.0127018922194,
                fields: [
                    {
                        id: 'hllsvvzdsa1ti5mbwjce5eb0m',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9l4532f1cgcmt5hizgq6ycqmd',
                        name: 'full_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3zkk69s9f6f0o398mnev8sorx',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '32boc01nkjh798msgroxdht6a',
                        name: 'private',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x4v4tknbbqmhufh8ejgf322e5',
                        name: 'owner',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1v67ykz9ovly04jfjvn8m1wuz',
                        name: 'last_synced_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a4u5ilqa8zsxr2aarn810v936',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'erud34rsun7pl7bg8a2qogu3j',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'liz4rgeho5elqk7hka4cr1hk4',
                        name: 'app_installation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4t3um6rr3g5x8169o76f8y4vh',
                        name: 'repositories_pkey',
                        unique: true,
                        fieldIds: ['hllsvvzdsa1ti5mbwjce5eb0m'],
                        createdAt: now,
                    },
                    {
                        id: 'e0biwkqvbn85k1199585r4dmv',
                        name: 'repositories_github_id_index',
                        unique: false,
                        fieldIds: ['3zkk69s9f6f0o398mnev8sorx'],
                        createdAt: now,
                    },
                    {
                        id: '2h4osgx506nni8takxgp31fis',
                        name: 'repositories_full_name_unique',
                        unique: true,
                        fieldIds: ['9l4532f1cgcmt5hizgq6ycqmd'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'fjvn8b9no6bwsamjxpz0ybtwv',
                name: 'app_installations',
                schema: 'public',
                x: 700.0000000000001,
                y: 533.0127018922194,
                fields: [
                    {
                        id: 'ngod02y4j6f7cm10nvccq94p7',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vwixchhemb056y4t6gwtif9gm',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pz3fasji7x4i2qsvimb8dyu4z',
                        name: 'app_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7hfi9p81n975attk9j9njl97v',
                        name: 'account_login',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm51w7ua3aiprmzfwzf76onlpq',
                        name: 'account_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2t8yaiy82kcz5r4siqtdfoa1w',
                        name: 'account_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8x6ushq205320l3x09y0d1hqe',
                        name: 'target_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2s2p9basc497qwij3p3c2kkrp',
                        name: 'target_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5uoihxylnx3n8jjyo4aixqpkd',
                        name: 'permission_pull_requests',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vpnwelfqudgc1axh5ersd5bz6',
                        name: 'permission_issues',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'u2rjvm2eo4jm3xdi8kem4rf6j',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tdlglnof4ml53b4vw5wrmhju1',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dbrjhctpy8ejthykq73cnc1lg',
                        name: 'permission_statuses',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 't91uptkw6hh478yveag7n9e8a',
                        name: 'app_installations_pkey',
                        unique: true,
                        fieldIds: ['ngod02y4j6f7cm10nvccq94p7'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'o74arv476fr0n9xuzsv0atulh',
                name: 'app_installation_permissions',
                schema: 'public',
                x: 1100,
                y: 533.0127018922194,
                fields: [
                    {
                        id: '887npfguizau91vpxqv00fabh',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2t3pwzqhm8kil7sntyfsh0yd7',
                        name: 'app_installation_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't62wpjjlniz8727737x78qbf0',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tvptc3bz4i5hixe158trg9er8',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tode6je7j77x4lzyj2fecif26',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ivfc7gytpu48izpuw07fva6iy',
                        name: 'app_installation_permissions_pkey',
                        unique: true,
                        fieldIds: ['887npfguizau91vpxqv00fabh'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ocpsd70dkrp5sy3pshyn0t2td',
                name: 'subscription_plans',
                schema: 'public',
                x: 100.00000000000003,
                y: 1050,
                fields: [
                    {
                        id: 'y4ft5c1c2g357l8iqg1tvmhqo',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ylkjtzhgieg860njjpfbhmgpv',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2zyr3l94bw5sfzafvl9aad4px',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kv04xqd7ympyfhcxlyhs9neiv',
                        name: 'description',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9aiwyirprxplznnjdlvtpjagc',
                        name: 'monthly_price_in_cents',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ogt62vsabaa69hd48h8a6mpa7',
                        name: 'yearly_price_in_cents',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zithlm49swhv1mdbqiq79mjg3',
                        name: 'price_model',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2wa79q0xxrwbokg5fki6o6mcw',
                        name: 'has_free_trial',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1h728nxnom8nyb1k7ydonsg18',
                        name: 'unit_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1cmfmjco4kd6w8c6r6lfc4zto',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '47gl5qpph42m4rqxrgk46m25d',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3enfnsfq4dh430th2y1256ai9',
                        name: 'number',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'o3a2q8u1himc6xqyd8ihh1b55',
                        name: 'subscription_plans_pkey',
                        unique: true,
                        fieldIds: ['y4ft5c1c2g357l8iqg1tvmhqo'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ovgsryw25j95li3tg9up0c2ih',
                name: 'comments',
                schema: 'public',
                x: 2100,
                y: 100,
                fields: [
                    {
                        id: 'aunzw3n1w1kukpijygyb32tz7',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'j7l6llgfhjvlc4pq6yhb1s2de',
                        name: 'subject_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xc3fl39b5zpp5ngobca3k8ng6',
                        name: 'github_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '25j3i64k41uauc3ygr3tmyoyk',
                        name: 'author',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tnwdd84xoeidzqa7h9f8x42qc',
                        name: 'author_association',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wxeg9rmwbdiqppnk641s739qz',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yumx70hs0dtivwyroi8wimmt0',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bri8jugf3idw4v3o6jm6q7u38',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zllcvsk4ks685cor0d3r91zg5',
                        name: 'review_state',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xdjtug1eut1re5bc3ayh3rvwi',
                        name: 'url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'zqemd5kqna4wtzs0xsyhcn3o4',
                        name: 'comments_subject_id_index',
                        unique: false,
                        fieldIds: ['j7l6llgfhjvlc4pq6yhb1s2de'],
                        createdAt: now,
                    },
                    {
                        id: 'od8frlwv7n734fq95mxbmzjq0',
                        name: 'comments_pkey',
                        unique: true,
                        fieldIds: ['aunzw3n1w1kukpijygyb32tz7'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'pgv2qrv0zltf7bahswjn85rvj',
                name: 'pinned_searches',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'c2opr5r12hxqzf1xb8jvob0my',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 't4xqm3qlowlofgh8ox4ygg0sm',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5j9h427q8bgiax0wcdsw32jew',
                        name: 'query',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3gq8iysrfng2biujq3qh7e8on',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9m5vold4x76hzm6caw3tr33jo',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'o9n75sgdb2utucizzdvjj48hr',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sar3w24lkix9o1auzddnry9hi',
                        name: 'pinned_searches_user_id_index',
                        unique: false,
                        fieldIds: ['t4xqm3qlowlofgh8ox4ygg0sm'],
                        createdAt: now,
                    },
                    {
                        id: 'sth5lham4yptgb3x2lg6fjzou',
                        name: 'pinned_searches_pkey',
                        unique: true,
                        fieldIds: ['c2opr5r12hxqzf1xb8jvob0my'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wfsf2mk6hsdo34lb4d3vstnup',
                name: 'subjects',
                schema: 'public',
                x: 1700,
                y: 100,
                fields: [
                    {
                        id: 'x4ihmgw06f2hktcy1gwcydoqn',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'g6vbh7sce5n3z4pjr0a181c9i',
                        name: 'url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mifo6hjcut13mlcsv6292f0qn',
                        name: 'state',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q1tt1827md17mhi9qj9yrv4n9',
                        name: 'author',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'aq4oojacdn552requ32fo98g9',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'itknc4ntvsx4igrs6deb4wlle',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xp6wd0r9hfhtrnfxjh6nivcxs',
                        name: 'html_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '534mir0orksn8su60rgcod656',
                        name: 'assignees',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '813kavmcr5eed9vs3p0nn05jz',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hy417mvyo3dwcbffqg7agir0h',
                        name: 'repository_full_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zwn8z8p9g9xp4svkur1mxaoow',
                        name: 'locked',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q9dojlyyovg2xwjizguyfw9pu',
                        name: 'sha',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7qsgw492vx9rn6yhuqizvfzfm',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'v34638whp5myyiytzmnpgqv06',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'khr12v2g2jcjs1h0ttg3pajqq',
                        name: 'comment_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a9wiof1ypblclnzxjkgiqg08v',
                        name: 'draft',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'iaz0v2kq93odx7jk1s3wxivu6',
                        name: 'subjects_pkey',
                        unique: true,
                        fieldIds: ['x4ihmgw06f2hktcy1gwcydoqn'],
                        createdAt: now,
                    },
                    {
                        id: 'iopuijdji16fgy1ay032yrgge',
                        name: 'subjects_repository_full_name_index',
                        unique: false,
                        fieldIds: ['hy417mvyo3dwcbffqg7agir0h'],
                        createdAt: now,
                    },
                    {
                        id: 'jycapdcmrz9bk4oe20x59g4f7',
                        name: 'subjects_url_index',
                        unique: false,
                        fieldIds: ['g6vbh7sce5n3z4pjr0a181c9i'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xwpaod0scheluskbj4u0gic5p',
                name: 'labels',
                schema: 'public',
                x: 1300,
                y: 100.00000000000006,
                fields: [
                    {
                        id: 'h44dv1pgz290bqqi5urymq078',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4c5e1payeq9ml0dpc7u99a99w',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nlfmrtgugyjuvlg59vyn8xp1j',
                        name: 'color',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'd81p3uprsyj6geuqubcq08yzh',
                        name: 'subject_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ohl27nbzkhrmggnqollls5lrb',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nlwg1rtbl0tfmfz6rd7os4vdi',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2ts2vqf4egiie477cn8shehnb',
                        name: 'github_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4truc3rjqzb4loo55dbpg09y4',
                        name: 'labels_subject_id_index',
                        unique: false,
                        fieldIds: ['d81p3uprsyj6geuqubcq08yzh'],
                        createdAt: now,
                    },
                    {
                        id: 'pru3aka4n1cfxcaxk6t6x1jnw',
                        name: 'labels_name_index',
                        unique: false,
                        fieldIds: ['4c5e1payeq9ml0dpc7u99a99w'],
                        createdAt: now,
                    },
                    {
                        id: 'ay14h83a4l0d2p1tlpdavqn1d',
                        name: 'labels_pkey',
                        unique: true,
                        fieldIds: ['h44dv1pgz290bqqi5urymq078'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'yv0yx7t8oxxr8icwcevqiu3b3',
                name: 'subscription_purchases',
                schema: 'public',
                x: 500,
                y: 1050,
                fields: [
                    {
                        id: '0qrly6mnoy5353f31oyxi4ayo',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'oxw842dhhgfkco6eib0zx75q8',
                        name: 'subscription_plan_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3q1pwuu5a9fbzgmu2za4wmgya',
                        name: 'account_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rn72zdppm2dmsyv8bzf8yemwr',
                        name: 'billing_cycle',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hzzxtzil0v8imb9ida60b3y8t',
                        name: 'unit_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'y51s8vn69pe4uqw03vbw2gy7d',
                        name: 'on_free_trial',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zc6puudmrv7l96dg5yn1g6vob',
                        name: 'free_trial_ends_on',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g0dfthiy8nkzwun0xlgewu4fa',
                        name: 'next_billing_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vdz625w0y8xhop1v8gl6n02bd',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dazp4ps1dqdl4nctltl2uykcb',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'cqi5ylbfj4fl0zssm5lsryv53',
                        name: 'oc_transactionid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'p15tpzq2lo0ry5pj0u0rjfofh',
                        name: 'subscription_purchases_pkey',
                        unique: true,
                        fieldIds: ['0qrly6mnoy5353f31oyxi4ayo'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '0d4uvwu6ekvps1f41rkg2nov6',
                name: 'notifications_repository_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '5az7tvlsq0h06z0u44eljxvat',
                targetTableId: 'c0bbaby788cbi5gllfx8y5kvy',
                sourceFieldId: 'hgb2xijbp1xd9cyahvgnug16h',
                targetFieldId: 'hllsvvzdsa1ti5mbwjce5eb0m',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2yjx9j6e4dde95gsdyxz29dg0',
                name: 'labels_subject_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xwpaod0scheluskbj4u0gic5p',
                targetTableId: 'wfsf2mk6hsdo34lb4d3vstnup',
                sourceFieldId: 'd81p3uprsyj6geuqubcq08yzh',
                targetFieldId: 'x4ihmgw06f2hktcy1gwcydoqn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'd2r50b73rjdobn6svz4pgdrfj',
                name: 'app_installation_permissions_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'o74arv476fr0n9xuzsv0atulh',
                targetTableId: '37np0qffoyukcatnqkwd2szdh',
                sourceFieldId: 't62wpjjlniz8727737x78qbf0',
                targetFieldId: 'zp2xsp1vy5v7hvg33xmjgoio2',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'dj9lzbowq6h09sfj1z335bdoo',
                name: 'app_installation_permissions_app_installation_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'o74arv476fr0n9xuzsv0atulh',
                targetTableId: 'fjvn8b9no6bwsamjxpz0ybtwv',
                sourceFieldId: '2t3pwzqhm8kil7sntyfsh0yd7',
                targetFieldId: 'ngod02y4j6f7cm10nvccq94p7',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'h5pk88xog4mje1v8n95500cia',
                name: 'comments_subject_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ovgsryw25j95li3tg9up0c2ih',
                targetTableId: 'wfsf2mk6hsdo34lb4d3vstnup',
                sourceFieldId: 'j7l6llgfhjvlc4pq6yhb1s2de',
                targetFieldId: 'x4ihmgw06f2hktcy1gwcydoqn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tylbof2t3jiycv7gb4ef9nr4w',
                name: 'subscription_purchases_subscription_plan_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'yv0yx7t8oxxr8icwcevqiu3b3',
                targetTableId: 'ocpsd70dkrp5sy3pshyn0t2td',
                sourceFieldId: 'oxw842dhhgfkco6eib0zx75q8',
                targetFieldId: 'y4ft5c1c2g357l8iqg1tvmhqo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vbiugdwzcbbv946r2ntsourzg',
                name: 'pinned_searches_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'pgv2qrv0zltf7bahswjn85rvj',
                targetTableId: '37np0qffoyukcatnqkwd2szdh',
                sourceFieldId: 't4xqm3qlowlofgh8ox4ygg0sm',
                targetFieldId: 'zp2xsp1vy5v7hvg33xmjgoio2',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ysqwoyi0ef6nvd06l8swg0qm7',
                name: 'repositories_app_installation_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c0bbaby788cbi5gllfx8y5kvy',
                targetTableId: 'fjvn8b9no6bwsamjxpz0ybtwv',
                sourceFieldId: 'liz4rgeho5elqk7hka4cr1hk4',
                targetFieldId: 'ngod02y4j6f7cm10nvccq94p7',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'zw1ccdac9rqjbc8sdrudek0qn',
                name: 'notifications_user_id_foreign',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '5az7tvlsq0h06z0u44eljxvat',
                targetTableId: '37np0qffoyukcatnqkwd2szdh',
                sourceFieldId: 'vhf76uw2vbyxe31h1g5fbwtcu',
                targetFieldId: 'zp2xsp1vy5v7hvg33xmjgoio2',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
