import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/pokemon.png';
import imageDark from '@/assets/templates/pokemon-dark.png';

const now = Date.now();

export const pokemonDb: Template = {
    slug: 'pokemon-database',
    name: 'Pokemon',
    shortDescription: 'Pokemon information',
    description: 'Mysql Relational of 722 pokemons. 14 Tables 5 views.',
    image,
    imageDark,
    tags: ['MySQL', 'Pokemon', 'Example Apps'],
    featured: true,
    url: 'https://github.com/brianr852/Pokemon-Database',
    diagram: {
        id: 'pokemon_db',
        name: 'pokemon-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.MYSQL,
        tables: [
            {
                id: '2b38krxujczg4jp3tlr8hc7ol',
                name: 'types',
                schema: 'pokemon',
                x: 873.4650174912003,
                y: -253.43478015206603,
                fields: [
                    {
                        id: 'efj03bsmn9ivm9qi9t24anhej',
                        name: 'type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9073grdj8mwel9lpt4hqzx5m2',
                        name: 'type_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'uzs7zymuvc175cz1x0ds0i062',
                        name: 'damage_type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '55323rwkpmrhvm2uk28e0t9n4',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['efj03bsmn9ivm9qi9t24anhej'],
                        createdAt: now,
                    },
                    {
                        id: 'w2uvoyhe1k3drm8ka6b7ci1lf',
                        name: 'damage_type_idx',
                        unique: false,
                        fieldIds: ['uzs7zymuvc175cz1x0ds0i062'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '2eb724n7iyn7vxxs73u8gw6d3',
                name: 'pokemon_total',
                schema: 'pokemon',
                x: 605.8858130588021,
                y: 572.8436020247541,
                fields: [
                    {
                        id: 'ixmzgt9b137dzn9xcxxfm9gi4',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'e5hxf7ndsq12z4edeg5f2b3ik',
                        name: 'pok_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'n5t8uxbujp13ky7p0f2h8nma9',
                        name: 'b_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8gqu68ykh189zf8c7xp1rm4dx',
                        name: 'b_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '11yrvtmbaga6vf9qngsh35jpm',
                        name: 'b_hp',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g0md3lrs57qra8ingxymw5idk',
                        name: 'b_speed',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0ylxst9rv7zw18i1wnpvgg1jv',
                        name: 'b_sp_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o1glneixynpu8lprjfonpnvub',
                        name: 'b_sp_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qlhp4yghufke3wrkauluy8u5c',
                        name: 'total',
                        type: {
                            id: 'decimal',
                            name: 'decimal',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 37,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b0b0b0',
                isView: true,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '3skhj1iu1edto5pkzblqhf1xg',
                name: 'pokemon_moves',
                schema: 'pokemon',
                x: -223.60679774997902,
                y: -45.78731054539702,
                fields: [
                    {
                        id: '339w8xtgvkp0ktdg3lf3zmppy',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8r9rgt64rpzt78pximuf01qv8',
                        name: 'version_group_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yuclv9h7jovv8i8ayx4rk2pqo',
                        name: 'move_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vptk6gjv8oldelvfmubdkvs9h',
                        name: 'method_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'w01c8aoxxh8m7wjpwmyyz1vsb',
                        name: 'level',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'zxxgg4a9ec0mlnb9oro2m7ei3',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            '339w8xtgvkp0ktdg3lf3zmppy',
                            '8r9rgt64rpzt78pximuf01qv8',
                            'yuclv9h7jovv8i8ayx4rk2pqo',
                            'vptk6gjv8oldelvfmubdkvs9h',
                            'w01c8aoxxh8m7wjpwmyyz1vsb',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'o8x46yb35nfdl3aq9u9gso5ee',
                        name: 'ix_pokemon_moves_level',
                        unique: false,
                        fieldIds: ['w01c8aoxxh8m7wjpwmyyz1vsb'],
                        createdAt: now,
                    },
                    {
                        id: '4dmcr7oe18a51n501rg38b1nz',
                        name: 'ix_pokemon_moves_version_group_id',
                        unique: false,
                        fieldIds: ['8r9rgt64rpzt78pximuf01qv8'],
                        createdAt: now,
                    },
                    {
                        id: 'z24dw9o8t40yjj4ln5mng4geo',
                        name: 'ix_pokemon_moves_move_id',
                        unique: false,
                        fieldIds: ['yuclv9h7jovv8i8ayx4rk2pqo'],
                        createdAt: now,
                    },
                    {
                        id: 'e9zfksyhzth1fecp142zc1hi9',
                        name: 'ix_pokemon_moves_pokemon_move_method_id',
                        unique: false,
                        fieldIds: ['vptk6gjv8oldelvfmubdkvs9h'],
                        createdAt: now,
                    },
                    {
                        id: '2dg349maegfnkjapjf0y0gy33',
                        name: 'ix_pokemon_moves_pokemon_id',
                        unique: false,
                        fieldIds: ['339w8xtgvkp0ktdg3lf3zmppy'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'a6ctr3r7t8wx1y578790gzf6h',
                name: 'version_groups',
                schema: 'pokemon',
                x: -506.55187033196404,
                y: -266.05074583478284,
                fields: [
                    {
                        id: 's5m6gddoig27qt7v510aukn9n',
                        name: 'version_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5ljafsood0nyh5kgf9czd2f26',
                        name: 'version_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'vpil87wt9k1s3gs79t6qpas53',
                        name: 'order',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4e31patra5em5z4paon0m2e5z',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['s5m6gddoig27qt7v510aukn9n'],
                        createdAt: now,
                    },
                    {
                        id: 'ji9qant27auhpdz67lyorwdk7',
                        name: 'identifier',
                        unique: true,
                        fieldIds: ['5ljafsood0nyh5kgf9czd2f26'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'an84j4zlsvyeias30iyrl5q2i',
                name: 'pokemon_types',
                schema: 'pokemon',
                x: 524.0469791064756,
                y: -3.1634143296112995,
                fields: [
                    {
                        id: '435ezkn4cziu77uk2wzhdqyzh',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pt8hvrs26tvp33z5jcx2hjy2a',
                        name: 'type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3hjpudao6q12rg6l1pozbnzvl',
                        name: 'slot',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tz2552n9e5xn17h0e78a9de84',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            '435ezkn4cziu77uk2wzhdqyzh',
                            '3hjpudao6q12rg6l1pozbnzvl',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'q9ey60zjv019bap5lccad0xto',
                        name: 'type_id',
                        unique: false,
                        fieldIds: ['pt8hvrs26tvp33z5jcx2hjy2a'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'b5da4wx8ytzughqio0363pkpp',
                name: 'pokemon_abilities',
                schema: 'pokemon',
                x: 148.78836674754348,
                y: 313.4720514781526,
                fields: [
                    {
                        id: 'i9xtkk6bs5jam0udvkylgdbgp',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3ub2idu3egp8qyukodpxia0xf',
                        name: 'abil_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7lqmjqz48hp482ydhute79gfu',
                        name: 'is_hidden',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8tqccsvgmyikc0edytft8fhby',
                        name: 'slot',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ynr2l14glt177h5lg8vgkqzn3',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'i9xtkk6bs5jam0udvkylgdbgp',
                            '8tqccsvgmyikc0edytft8fhby',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '5tafa2tya8cj6mmgzr1bup41g',
                        name: 'abil_id',
                        unique: false,
                        fieldIds: ['3ub2idu3egp8qyukodpxia0xf'],
                        createdAt: now,
                    },
                    {
                        id: 'l9dvdeo2qw5b4ygznog60ql53',
                        name: 'ix_pokemon_abilities_is_hidden',
                        unique: false,
                        fieldIds: ['7lqmjqz48hp482ydhute79gfu'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bqs4duxbfgmvyk8xpkiah0nlk',
                name: 'pokemon_evolution',
                schema: 'pokemon',
                x: 19.797206619011945,
                y: 695.4830028631238,
                fields: [
                    {
                        id: 'l0y0cuwx6f3ugjnyfot853338',
                        name: 'evol_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'iud3vstugtinb8kyuwxbw6i39',
                        name: 'evolved_species_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ceujkrrr2sr01yg4kmftjx578',
                        name: 'evol_minimum_level',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'e298imj9ngwlgbznw4n3ks4nh',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['l0y0cuwx6f3ugjnyfot853338'],
                        createdAt: now,
                    },
                    {
                        id: '0e0ci8xev4hrqm9bf9x1db65s',
                        name: 'evolved_species_id',
                        unique: false,
                        fieldIds: ['iud3vstugtinb8kyuwxbw6i39'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'iqdj5nih431rwu53njb2u7f3h',
                name: 'pokemon',
                schema: 'pokemon',
                x: 116.27857835040618,
                y: 29.458533315272234,
                fields: [
                    {
                        id: 'hybyihxuw9dyax3kbnsxx3uez',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'k1b576nk09xkspa39dyrlymce',
                        name: 'pok_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'yw17ocu1vkakrkutqmo76utjs',
                        name: 'pok_height',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'v04yxqz5f5bahda4nau3z1hus',
                        name: 'pok_weight',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'k6grysh72jyq629cy6vaqg3ys',
                        name: 'pok_base_experience',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '0hpl7hps7y7tihrwmqavlmvrw',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['hybyihxuw9dyax3kbnsxx3uez'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'kxv4737o7czb40yeh8e2nj2n0',
                name: 'att_def_hp',
                schema: 'pokemon',
                x: 869.2053944312631,
                y: 235.13020145570192,
                fields: [
                    {
                        id: 'tg4c5y0wrezg3ege7xhuwifmh',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'txnmo4uw22e0h55gcjoayssga',
                        name: 'pok_name',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '6rb3zw9h8fz9qh3k4mae2fzg8',
                        name: 'b_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'gysb4kjet0hihhwafl287crnm',
                        name: 'b_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'o4b8g02v1pay93c6o7lbrj6z7',
                        name: 'b_speed',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'r10i6f69bmz7wpfjtya348v99',
                        name: 'b_sp_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'bkvftpoqzs2w3ywstnuovroj0',
                        name: 'b_sp_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b0b0b0',
                isView: true,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'lwr23uuyw7m0w4b97rme9e9qo',
                name: 'top_10_view',
                schema: 'pokemon',
                x: -568.4914974258002,
                y: 614.5677218425993,
                fields: [
                    {
                        id: 'c24al7azqiyz1ult3ix62dlg4',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'xqmnpithdgxz0m23efcjophbm',
                        name: 'pok_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'wcampqvrp0em7zovoqy159wv8',
                        name: 'b_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7x25b9b828wy2g7ydgjlwp7pt',
                        name: 'b_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '20wkf4iiqkzd8k2mdxnqeqy7d',
                        name: 'b_hp',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '22v21w1grzxy4eeqxwd2naqwt',
                        name: 'b_speed',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x1xvarjztlpc3wtaklk38pcyp',
                        name: 'b_sp_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'p4s2whwx9g1au8evot4107zgr',
                        name: 'b_sp_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rtxbtkvn1t0efko4axg2qf2dm',
                        name: 'TOTAL',
                        type: {
                            id: 'decimal',
                            name: 'decimal',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 37,
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b0b0b0',
                isView: true,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'n0gd0o26z50hs3el69lsqdspq',
                name: 'pok_abilities',
                schema: 'pokemon',
                x: 924.5003442816526,
                y: 573.3300416541815,
                fields: [
                    {
                        id: 'xutqjn5oejz3u0vyumtgmins9',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'wu4m3q2q5hcznhpakkpscb9a1',
                        name: 'pok_name',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'wuljucnf7ttajt1q9r7krnj2d',
                        name: 'abil_name',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'ldvpp9dy8p2tzlt0l9adx3uts',
                        name: 'is_hidden',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'qapmr8w8zn601qcsbhiayfwoh',
                        name: 'pok_base_experience',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b0b0b0',
                isView: true,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'o1q0k0iqprc4nft3xr0ahombk',
                name: 'type_efficacy',
                schema: 'pokemon',
                x: 932.4972316079298,
                y: -15.860793854582056,
                fields: [
                    {
                        id: 'rvijvbidfhkmprs3ppl6bjoie',
                        name: 'damage_type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'q9hgbv5nkzej8u13rucyxjejp',
                        name: 'target_type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '19kjor592l4oqbjc0wpmtgy11',
                        name: 'damage_factor',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'f8s3ggdpbov69478z8as4u5p3',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: [
                            'rvijvbidfhkmprs3ppl6bjoie',
                            'q9hgbv5nkzej8u13rucyxjejp',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'sizy32etlognb8khgl0eydusv',
                        name: 'target_type_id',
                        unique: false,
                        fieldIds: ['q9hgbv5nkzej8u13rucyxjejp'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'tac2tasvm41j5ohw56tae59tm',
                name: 'pokemon_habitats',
                schema: 'pokemon',
                x: -590.0204058678445,
                y: 285.42021161133914,
                fields: [
                    {
                        id: 'rzx2xym9nzp961g40uwgh9fp0',
                        name: 'hab_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'g3vj41vs1xxr0xljyv0s1qf6o',
                        name: 'hab_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: '361zv15lafzygo5ceirv8m65s',
                        name: 'hab_descript',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4blx0zp1e3grmrt7b4nxdyq30',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['rzx2xym9nzp961g40uwgh9fp0'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'uzpyc3qa0b459o1nfhs9boeqy',
                name: 'moves',
                schema: 'pokemon',
                x: 242.92574062833955,
                y: -267.3623895489227,
                fields: [
                    {
                        id: 'tx05rqaw9rjr2yrc1ft4m8vda',
                        name: 'move_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'auhg4icrfppbmgdlbywqpn1le',
                        name: 'move_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                    {
                        id: 'm60sorkymw4po8y6qwecxn2ld',
                        name: 'type_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tq8qnqu9rgx1f3cl0gaqvnk70',
                        name: 'move_power',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5e7kht5y6zvi6hrw8u0p7608f',
                        name: 'move_pp',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0pscehnlo12ccg73mkse3ummm',
                        name: 'move_accuracy',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4uhaeuh17t53gdzykytr571jy',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['tx05rqaw9rjr2yrc1ft4m8vda'],
                        createdAt: now,
                    },
                    {
                        id: 'k4m8ihhkrspccecild8akk0lo',
                        name: 'type_id',
                        unique: false,
                        fieldIds: ['m60sorkymw4po8y6qwecxn2ld'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'v06q4teh4o8g6f1i8ol2ymb9k',
                name: 'abilities',
                schema: 'pokemon',
                x: 272.261042823043,
                y: 575.3974731905092,
                fields: [
                    {
                        id: 'amv9hgvanenoucx8kmph56y35',
                        name: 'abil_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vyuitty6r0y1d3sys152zxq33',
                        name: 'abil_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2xr87x0vllhpqhck5xglpm6zn',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['amv9hgvanenoucx8kmph56y35'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'v31q6zdsb08dw2262ekmcpc60',
                name: 'pokemon_move_methods',
                schema: 'pokemon',
                x: -570.9905740536955,
                y: 32.175754614674304,
                fields: [
                    {
                        id: '8ze7f82oh01gffeqopido9ppw',
                        name: 'method_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '93szw1ayzqj22ia8cmc8smzqq',
                        name: 'method_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb3_general_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2wyn0dfdl7zlszzpqhm1dndgg',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['8ze7f82oh01gffeqopido9ppw'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wwff8jejj87wwuwqwhrup6bgq',
                name: 'pokemon_evolution_matchup',
                schema: 'pokemon',
                x: -267.5498837288867,
                y: 289.3151732863062,
                fields: [
                    {
                        id: '8gj47ogh5knemijrczk6h8ita',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i9d1gvp1csfvf2u2tl6d0ne3g',
                        name: 'evolves_from_species_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's8rcfrc2y7nnu97wevdiasadj',
                        name: 'hab_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wkhr7cx1oijsuctjdq60c0ci9',
                        name: 'gender_rate',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xbxilcgzhx8929rav4dg7yeki',
                        name: 'capture_rate',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'c2fb5j2shxq19phnritefoqhf',
                        name: 'base_happiness',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'eh2v11xu7026rgjch1xzupvqm',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['8gj47ogh5knemijrczk6h8ita'],
                        createdAt: now,
                    },
                    {
                        id: 'qc7ongl01sjwij2osp2k6nltk',
                        name: 'evolves_from_species_id',
                        unique: false,
                        fieldIds: ['i9d1gvp1csfvf2u2tl6d0ne3g'],
                        createdAt: now,
                    },
                    {
                        id: '10vxxaxgux7ljiucmn6a5zw59',
                        name: 'habitat_id',
                        unique: false,
                        fieldIds: ['s8rcfrc2y7nnu97wevdiasadj'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
                width: 337,
            },
            {
                id: 'z76lvz1iq4x6bji6e3nwkgw9f',
                name: 'habitat_view',
                schema: 'pokemon',
                x: -289.39252154021415,
                y: 731.8300921566613,
                fields: [
                    {
                        id: 'yckzwfxk0xw4zcvs74io5hqy5',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'nr523lv9g3fyp580vda81n0hs',
                        name: 'pok_name',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '8prdp6mj25sa9s8rme3ca2fg1',
                        name: 'hab_name',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'xm5ni0g8klad4tm8lpm494ss7',
                        name: 'pok_height',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'vtccos2l0seb4cg3e19cv0nsn',
                        name: 'pok_weight',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '2uileq5kmueqfylwi39n58sqq',
                        name: 'capture_rate',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'xz7cue27tynkz8u7bht3rb83p',
                        name: 'base_happiness',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [],
                color: '#b0b0b0',
                isView: true,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zpw68rhn61olde7psa208sns5',
                name: 'base_stats',
                schema: 'pokemon',
                x: 585.2066446815784,
                y: 261.2017602083919,
                fields: [
                    {
                        id: 'lzvke3sygowig92l5umxwdyni',
                        name: 'pok_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tx9r9ed4dy3l2375x2vtv61ny',
                        name: 'b_hp',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3tsxug79sokm1ou7wvcip9a4f',
                        name: 'b_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1ty204epml63g5h5wsn1ocg0x',
                        name: 'b_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'refbyfsyo3izkpacidlq2vj1s',
                        name: 'b_sp_atk',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'iwayu4ijq8jgpch1hxhd4ohoz',
                        name: 'b_sp_def',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8qpu41e7r40g8j8we50r9raee',
                        name: 'b_speed',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'f90bqbh4jtasp7noy6tll9rwh',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['lzvke3sygowig92l5umxwdyni'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '0sgdml1yvl02y4y1hl257zgkq',
                name: 'pokemon_evolution_matchup_ibfk_6',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'wwff8jejj87wwuwqwhrup6bgq',
                targetTableId: 'tac2tasvm41j5ohw56tae59tm',
                sourceFieldId: 's8rcfrc2y7nnu97wevdiasadj',
                targetFieldId: 'rzx2xym9nzp961g40uwgh9fp0',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '1ataj7nbcittt3qkbuc6yzgi7',
                name: 'poke_fk',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'wwff8jejj87wwuwqwhrup6bgq',
                targetTableId: 'iqdj5nih431rwu53njb2u7f3h',
                sourceFieldId: '8gj47ogh5knemijrczk6h8ita',
                targetFieldId: 'hybyihxuw9dyax3kbnsxx3uez',
                sourceCardinality: 'one',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5q5kxh60dqkvsgsd6cdzwhfu1',
                name: 'pokemon_moves_ibfk_2',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: '3skhj1iu1edto5pkzblqhf1xg',
                targetTableId: 'uzpyc3qa0b459o1nfhs9boeqy',
                sourceFieldId: 'yuclv9h7jovv8i8ayx4rk2pqo',
                targetFieldId: 'tx05rqaw9rjr2yrc1ft4m8vda',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5znlmo5pgrm5lzc8kk4yrotfd',
                name: 'pokemon_types_ibfk_1',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'an84j4zlsvyeias30iyrl5q2i',
                targetTableId: 'iqdj5nih431rwu53njb2u7f3h',
                sourceFieldId: '435ezkn4cziu77uk2wzhdqyzh',
                targetFieldId: 'hybyihxuw9dyax3kbnsxx3uez',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'bud8sj1kva65oq6new8zayney',
                name: 'damage_type',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: '2b38krxujczg4jp3tlr8hc7ol',
                targetTableId: 'o1q0k0iqprc4nft3xr0ahombk',
                sourceFieldId: 'uzs7zymuvc175cz1x0ds0i062',
                targetFieldId: 'rvijvbidfhkmprs3ppl6bjoie',
                sourceCardinality: 'many',
                targetCardinality: 'many',
                createdAt: now,
            },
            {
                id: 'gd57h1npjzgp8lqd5bfj6ii19',
                name: 'pokemon_moves_ibfk_4',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: '3skhj1iu1edto5pkzblqhf1xg',
                targetTableId: 'v31q6zdsb08dw2262ekmcpc60',
                sourceFieldId: 'vptk6gjv8oldelvfmubdkvs9h',
                targetFieldId: '8ze7f82oh01gffeqopido9ppw',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hhncqgq7x7fs1rphf4swc6x8z',
                name: 'moves_ibfk_2',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'uzpyc3qa0b459o1nfhs9boeqy',
                targetTableId: '2b38krxujczg4jp3tlr8hc7ol',
                sourceFieldId: 'm60sorkymw4po8y6qwecxn2ld',
                targetFieldId: 'efj03bsmn9ivm9qi9t24anhej',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hkox6rwd6z6aq29g4gog19jo4',
                name: 'pokemon_moves_ibfk_3',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: '3skhj1iu1edto5pkzblqhf1xg',
                targetTableId: 'a6ctr3r7t8wx1y578790gzf6h',
                sourceFieldId: '8r9rgt64rpzt78pximuf01qv8',
                targetFieldId: 's5m6gddoig27qt7v510aukn9n',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hxzyjhcf718kc05yvswldurgd',
                name: 'pokemon_evolution_ibfk_1',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'bqs4duxbfgmvyk8xpkiah0nlk',
                targetTableId: 'wwff8jejj87wwuwqwhrup6bgq',
                sourceFieldId: 'iud3vstugtinb8kyuwxbw6i39',
                targetFieldId: '8gj47ogh5knemijrczk6h8ita',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'js826r5j9y9fpaca2e5z3v1kc',
                name: 'pokemon_abilities_ibfk_1',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'b5da4wx8ytzughqio0363pkpp',
                targetTableId: 'iqdj5nih431rwu53njb2u7f3h',
                sourceFieldId: 'i9xtkk6bs5jam0udvkylgdbgp',
                targetFieldId: 'hybyihxuw9dyax3kbnsxx3uez',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'l37hvkmqfenw2ifs38pplnc90',
                name: 'pok_id',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'zpw68rhn61olde7psa208sns5',
                targetTableId: 'iqdj5nih431rwu53njb2u7f3h',
                sourceFieldId: 'lzvke3sygowig92l5umxwdyni',
                targetFieldId: 'hybyihxuw9dyax3kbnsxx3uez',
                sourceCardinality: 'one',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'pc4i8r2z64iaif40osru4e1be',
                name: 'pokemon_abilities_ibfk_2',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'b5da4wx8ytzughqio0363pkpp',
                targetTableId: 'v06q4teh4o8g6f1i8ol2ymb9k',
                sourceFieldId: '3ub2idu3egp8qyukodpxia0xf',
                targetFieldId: 'amv9hgvanenoucx8kmph56y35',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vvmmur2q0s3l9vg2usudnma0j',
                name: 'pokemon_moves_ibfk_1',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: '3skhj1iu1edto5pkzblqhf1xg',
                targetTableId: 'iqdj5nih431rwu53njb2u7f3h',
                sourceFieldId: '339w8xtgvkp0ktdg3lf3zmppy',
                targetFieldId: 'hybyihxuw9dyax3kbnsxx3uez',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'zyjvyjtx3m7axn5sh75k17jey',
                name: 'pokemon_types_ibfk_2',
                sourceSchema: 'pokemon',
                targetSchema: 'pokemon',
                sourceTableId: 'an84j4zlsvyeias30iyrl5q2i',
                targetTableId: '2b38krxujczg4jp3tlr8hc7ol',
                sourceFieldId: 'pt8hvrs26tvp33z5jcx2hjy2a',
                targetFieldId: 'efj03bsmn9ivm9qi9t24anhej',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [
            {
                id: '4fsi7ctzth0o9aq0o5a8eowwc',
                schema: 'pokemon',
                tableId: 'zpw68rhn61olde7psa208sns5',
                dependentSchema: 'pokemon',
                dependentTableId: 'lwr23uuyw7m0w4b97rme9e9qo',
                createdAt: now,
            },
            {
                id: 'cbe3zwfn1lbkqxmuzynobte9e',
                schema: 'pokemon',
                tableId: 'zpw68rhn61olde7psa208sns5',
                dependentSchema: 'pokemon',
                dependentTableId: '2eb724n7iyn7vxxs73u8gw6d3',
                createdAt: now,
            },
            {
                id: 'ja0hww1sc4v2w7gyiltzvx03e',
                schema: 'pokemon',
                tableId: 'iqdj5nih431rwu53njb2u7f3h',
                dependentSchema: 'pokemon',
                dependentTableId: 'lwr23uuyw7m0w4b97rme9e9qo',
                createdAt: now,
            },
            {
                id: 'yo6o141gkxoy5hxosjlkokrea',
                schema: 'pokemon',
                tableId: 'iqdj5nih431rwu53njb2u7f3h',
                dependentSchema: 'pokemon',
                dependentTableId: '2eb724n7iyn7vxxs73u8gw6d3',
                createdAt: now,
            },
        ],
    },
};
