import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/refinerycms-db.png';
import imageDark from '@/assets/templates/refinerycms-db-dark.png';

const now = Date.now();

export const refinerycmsDb: Template = {
    slug: 'refinerycms-database',
    name: 'Refinerycms',
    shortDescription: 'Ruby on Rails - Content management system',
    description:
        'Is the leading open source CMS on the Ruby on Rails framework. For creating custom content manageable websites',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Rails', 'CMS'],
    featured: true,
    url: 'https://github.com/refinery/refinerycms',
    diagram: {
        id: 'refinerycms_db',
        name: 'refinerycms-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '0kys8v69us9hbf0co0225dybz',
                name: 'refinery_pages',
                schema: 'public',
                x: 229.2394424211834,
                y: 156.8653546653207,
                fields: [
                    {
                        id: '5w012p88r4rek8982cxclnl48',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('refinery_pages_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'lzevldhuyo06sspphm4wucizo',
                        name: 'parent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yk4bq7711j5fddoqsof7j4u9v',
                        name: 'path',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm7vykm599oa0s7hak069u57qu',
                        name: 'show_in_menu',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'oimep75r2bju12ph7ztijflsw',
                        name: 'link_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vcd3buqs75mdojua7076xqjbv',
                        name: 'menu_match',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ppdpuv5kms8eiz1mq1qvmmret',
                        name: 'deletable',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'dr3j1wjfkeyiyle1q5qnit2vc',
                        name: 'draft',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'iaa88kbyxvsbq8fprf57q31ve',
                        name: 'skip_to_first_child',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'katwma7rn3pw0e6x7rexgtlfe',
                        name: 'lft',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vcfz7zok6l27dlfdtj95wjgpx',
                        name: 'rgt',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1ckfcg95ky3lp1ec55hver01e',
                        name: 'depth',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rcb5rnq8nl4fayhzt02gfnegf',
                        name: 'view_template',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0rlklhd2qaco6zjldz8rmdzdn',
                        name: 'layout_template',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pgf4zovdu5618qzaz76nr271d',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'usqziu3i0ntpdidisg3vygyjy',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ayqgxg0m24cydemeg2j6thvkd',
                        name: 'children_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '6eamlfan55ss7szb6eif4ydha',
                        name: 'refinery_pages_pkey',
                        unique: true,
                        fieldIds: ['5w012p88r4rek8982cxclnl48'],
                        createdAt: now,
                    },
                    {
                        id: 'va9hp8z6nawt4pmn89sct0yat',
                        name: 'idx_refinery_pages_parent_id',
                        unique: false,
                        fieldIds: ['lzevldhuyo06sspphm4wucizo'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '92c2fr501z0r9f3w1nuv7hqth',
                name: 'refinery_page_translations',
                schema: 'public',
                x: -99.99999999999991,
                y: 533.0127018922194,
                fields: [
                    {
                        id: 'uu5py9i7tvqt7yb20cbl12epi',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_page_translations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'gxucq2jirgj2154f1kbosszje',
                        name: 'refinery_page_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qphxggyr451wu60jxqmwyeo34',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'a8yanumpne9ljm99x5gbhkumn',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qd63pzr1wg1pgmkh4afvqv1ko',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ppar7easmrljvwjucwezdwjcd',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '54t4qguqt3ecd159e44rdup1u',
                        name: 'custom_slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0i8cdq5il4gs0rpt1mkxai2wg',
                        name: 'menu_title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '83xoggy6fq9qmjvmahnvy76pm',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'egfgzq493yfifmqw5eeuhtvi0',
                        name: 'refinery_page_translations_pkey',
                        unique: true,
                        fieldIds: ['uu5py9i7tvqt7yb20cbl12epi'],
                        createdAt: now,
                    },
                    {
                        id: '3836t31nwewjaop5qlxa6lqc5',
                        name: 'refinery_page_translations_refinery_page_id_locale_key',
                        unique: true,
                        fieldIds: [
                            'gxucq2jirgj2154f1kbosszje',
                            'qphxggyr451wu60jxqmwyeo34',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '12edjtllo0c5pj3j3khr122zn',
                        name: 'idx_refinery_page_translations_page_id',
                        unique: false,
                        fieldIds: ['gxucq2jirgj2154f1kbosszje'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'az3v69juj3jrw4xtvuv3w5f5d',
                name: 'refinery_authentication_users',
                schema: 'public',
                x: 249.91775320857278,
                y: 679.486182795465,
                fields: [
                    {
                        id: '91ttm15k7g2vorzb6rgo0444u',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_authentication_users_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'j9a0tv182t7nkp9s4zzjg698e',
                        name: 'username',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ybw25y34rgbrqq7cuv5c3yp24',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd1ltk39stbddosok6q9belgx7',
                        name: 'encrypted_password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5axdyqn4990anbktrhuj7uofj',
                        name: 'current_sign_in_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jg2q4b95zv8u126i52mztou90',
                        name: 'last_sign_in_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xdz334d3k511vuhj74idw5tgh',
                        name: 'current_sign_in_ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'p3ea62dol30delzexoazvo1c5',
                        name: 'last_sign_in_ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'b2i970wo3lhmqxv5qvcvjswpd',
                        name: 'sign_in_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '5iewf3892e3gl97qd4v5t9uzi',
                        name: 'remember_created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xcvl0keiint8jddwcw40eip51',
                        name: 'reset_password_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fehqicapvw16eyiy83nm5035h',
                        name: 'reset_password_sent_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xgdn0zjl5srwt2cdfpmzn2jig',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hlx0959pz7g96mx43osm50b3m',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1aiosqosixnfedk8xtduj252y',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gtipy4p2z0k1vce7wh2oeitre',
                        name: 'full_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5zbybx13z2d7kh7ma9w6gz6kz',
                        name: 'refinery_authentication_users_pkey',
                        unique: true,
                        fieldIds: ['91ttm15k7g2vorzb6rgo0444u'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bgv9x5k13hzj1re3wqt0t9o4v',
                name: 'refinery_page_part_translations',
                schema: 'public',
                x: 866.3977449704923,
                y: 296.4439524801989,
                fields: [
                    {
                        id: 'na82v4308qa3fibjpb5axjzql',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_page_part_translations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'qllab1c60stttba572afmuiai',
                        name: 'refinery_page_part_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'se0uglcze7spj1k5w8q3z73xb',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'y7sfbpy7la99re2xdvmfsxd3f',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f7yw2vrw55ob428limom1uln7',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2lg5qdu8as4edbpptg5zufm9g',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bt8bj3trzvueqh3jlsk00ip9f',
                        name: 'idx_refinery_page_part_translations_part_id',
                        unique: false,
                        fieldIds: ['qllab1c60stttba572afmuiai'],
                        createdAt: now,
                    },
                    {
                        id: 'cw8ptlacxfhvnwdn4x5mrm3t4',
                        name: 'refinery_page_part_translation_refinery_page_part_id_locale_key',
                        unique: true,
                        fieldIds: [
                            'qllab1c60stttba572afmuiai',
                            'se0uglcze7spj1k5w8q3z73xb',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '3pstn8fz4gcu765yjhua3b8rj',
                        name: 'refinery_page_part_translations_pkey',
                        unique: true,
                        fieldIds: ['na82v4308qa3fibjpb5axjzql'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'd9lhzeswfxg2yf5rwj0u6c4h2',
                name: 'refinery_authentication_user_roles',
                schema: 'public',
                x: 600.8067650885232,
                y: 860.1746618108403,
                fields: [
                    {
                        id: '42794lkejwwtxizfwn5666y7n',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_authentication_user_roles_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'mj35p9z8gx9f79n0dvfa4bskv',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ybixjuasbfq711r01cpsmy4uv',
                        name: 'role_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ik9j01qh08om3fixpqnk4d3y3',
                        name: 'refinery_authentication_user_roles_pkey',
                        unique: true,
                        fieldIds: ['42794lkejwwtxizfwn5666y7n'],
                        createdAt: now,
                    },
                    {
                        id: '2k2lud63wcdnke7rlyi0wtyi2',
                        name: 'refinery_authentication_user_roles_user_id_role_id_key',
                        unique: true,
                        fieldIds: [
                            'mj35p9z8gx9f79n0dvfa4bskv',
                            'ybixjuasbfq711r01cpsmy4uv',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '8auv7que43c4ng2v86217o8lx',
                        name: 'idx_refinery_authentication_user_roles_user_id',
                        unique: false,
                        fieldIds: ['mj35p9z8gx9f79n0dvfa4bskv'],
                        createdAt: now,
                    },
                    {
                        id: 'xqjh7jcg87g0hd971ft31ly9g',
                        name: 'idx_refinery_authentication_user_roles_role_id',
                        unique: false,
                        fieldIds: ['ybixjuasbfq711r01cpsmy4uv'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jlkaqwomq1h61d2ukg41ckcvi',
                name: 'refinery_images',
                schema: 'public',
                x: 1575.8531974050043,
                y: -101.52734012974977,
                fields: [
                    {
                        id: 'pflvzdhfc8eue9m46ndkmb011',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('refinery_images_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'utjysodvtiwoxumz6stidot7v',
                        name: 'image_mime_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2bn1rg82hfltbe0eo5604g52m',
                        name: 'image_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'thuyam3y8kl4hlaouyb82rapm',
                        name: 'image_size',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o161ddzn9487c8wcvl0ro2mh3',
                        name: 'image_width',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'we1izdong38a2oon1qz82m50u',
                        name: 'image_height',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4s9w55236dz4z3qnrdyhwwqsq',
                        name: 'image_uid',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5092e6ce9fli7k8fjziogtr59',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vpo0mcy4pb60v3x9ltjf51yn4',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bx3r8c39zfa6tfds24u4vn1og',
                        name: 'refinery_images_pkey',
                        unique: true,
                        fieldIds: ['pflvzdhfc8eue9m46ndkmb011'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jtjpfsqpmhkplka00h7fvkweu',
                name: 'refinery_authentication_roles',
                schema: 'public',
                x: 900,
                y: 666.3154981790651,
                fields: [
                    {
                        id: 'lnclb8wwog1fehv7owsoecj6j',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_authentication_roles_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '854irrwfbuu2al0q5z6qyyebs',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'fzwz87rsofkrsf419dctat2yh',
                        name: 'refinery_authentication_roles_pkey',
                        unique: true,
                        fieldIds: ['lnclb8wwog1fehv7owsoecj6j'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ojwtj2y46se64tt1qd7m7lkcw',
                name: 'refinery_resource_translations',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: 'zfky51214gs41juaz0nfb1z4e',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_resource_translations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'p56j9c43zosgj116fxg3guydb',
                        name: 'refinery_resource_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'iiavrhga4p4m4ccjnvgovru0o',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9mb3el80bt0c0fyd3ah9mfan9',
                        name: 'resource_title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zbou3jywd329ofcfknfvgmxu8',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '320a7qzypj8emcwsz31o9ebc8',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'n3l3mw6gy9nfuemyo18qh5p23',
                        name: 'refinery_resource_translations_refinery_resource_id_locale_key',
                        unique: true,
                        fieldIds: [
                            'p56j9c43zosgj116fxg3guydb',
                            'iiavrhga4p4m4ccjnvgovru0o',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '9zt4chajx7e7ytsfm0or8y6kk',
                        name: 'refinery_resource_translations_pkey',
                        unique: true,
                        fieldIds: ['zfky51214gs41juaz0nfb1z4e'],
                        createdAt: now,
                    },
                    {
                        id: 'qjqataetyjctqm3je37b6f1bh',
                        name: 'idx_refinery_resource_translations_resource_id',
                        unique: false,
                        fieldIds: ['p56j9c43zosgj116fxg3guydb'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ozy6j111lda7uukpdsjcd4dhh',
                name: 'refinery_page_parts',
                schema: 'public',
                x: 533.6022550295079,
                y: -24.069864724336185,
                fields: [
                    {
                        id: '8uqx94rc08fid6ni08eryfs7o',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_page_parts_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'mjn96dcqh1eglgrfbqswy8h0w',
                        name: 'refinery_page_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '99nnttv8fh3v4pfwqr0byx7js',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nab8y2kg1ia5e99jto9fw40z6',
                        name: 'position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4cc5vgizxdw8cmskijg5fvpe8',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0cs57b62awzmsge44qee2bxj9',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '10d4ypau9r7va848q2fbxmh0x',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vcwgq8voqzcvtyea36mvlwrq7',
                        name: 'idx_refinery_page_parts_page_id',
                        unique: false,
                        fieldIds: ['mjn96dcqh1eglgrfbqswy8h0w'],
                        createdAt: now,
                    },
                    {
                        id: '0sdoid7tbbbfl48jqlbjx0rj9',
                        name: 'refinery_page_parts_pkey',
                        unique: true,
                        fieldIds: ['8uqx94rc08fid6ni08eryfs7o'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'p5hofapibkk3hf64g0ak4am2v',
                name: 'refinery_resources',
                schema: 'public',
                x: 1700,
                y: 600,
                fields: [
                    {
                        id: 'fpz87bef6sxzktbnsc2f16x7u',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_resources_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '2geu0um0k2a25nt4ic6lpdgmf',
                        name: 'file_mime_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'di74d3v5s6xjo1wudcwd2d6nu',
                        name: 'file_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'd3z436v5i6qybn7xxz0i43r7z',
                        name: 'file_size',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jw9skkurlrgqn32fl01r4ft20',
                        name: 'file_uid',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'c0ax48fupz3lbwt7z323m3qlc',
                        name: 'file_ext',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uefd28uyvdhv2mz6tvtb38zmf',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6nzulglmtpiwz0f1jdwdt9gq2',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sm2yae2aqi92lffzvqlin1ng1',
                        name: 'refinery_resources_pkey',
                        unique: true,
                        fieldIds: ['fpz87bef6sxzktbnsc2f16x7u'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'z6wjw0jok023a9o6z420pbypt',
                name: 'refinery_image_translations',
                schema: 'public',
                x: 1213.2797034291007,
                y: 33.783873957367916,
                fields: [
                    {
                        id: 'lu3limyzf56lsray464ynun9z',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default:
                            "nextval('refinery_image_translations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'ktz1mn9yugv5gwsjr9s9bulwz',
                        name: 'refinery_image_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xzv1q8m8az73w28jw4id8verk',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5jj95obtrmpme85y919r3wm5w',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'otok7kgos7i9tpfyneczcdvex',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'opqceeimb8zwzmwxf2rlva8nl',
                        name: 'image_alt',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xb8uoknax98spicvsjea6dskx',
                        name: 'image_title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '1ef6js0vivcvx20bkuhu6h1zg',
                        name: 'refinery_image_translations_refinery_image_id_locale_key',
                        unique: true,
                        fieldIds: [
                            'ktz1mn9yugv5gwsjr9s9bulwz',
                            'xzv1q8m8az73w28jw4id8verk',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'si5487fpr2xj5puqcpszukdzf',
                        name: 'idx_refinery_image_translations_image_id',
                        unique: false,
                        fieldIds: ['ktz1mn9yugv5gwsjr9s9bulwz'],
                        createdAt: now,
                    },
                    {
                        id: 'nq7iy3jnlm64m1lfzo32n3zr3',
                        name: 'refinery_image_translations_pkey',
                        unique: true,
                        fieldIds: ['lu3limyzf56lsray464ynun9z'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '0gdn2s190su96bitg282ic1t1',
                name: 'refinery_image_translations_refinery_image_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'z6wjw0jok023a9o6z420pbypt',
                targetTableId: 'jlkaqwomq1h61d2ukg41ckcvi',
                sourceFieldId: 'ktz1mn9yugv5gwsjr9s9bulwz',
                targetFieldId: 'pflvzdhfc8eue9m46ndkmb011',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2ia47qvis4w2elsngz0wsoajn',
                name: 'refinery_authentication_user_roles_role_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'd9lhzeswfxg2yf5rwj0u6c4h2',
                targetTableId: 'jtjpfsqpmhkplka00h7fvkweu',
                sourceFieldId: 'ybixjuasbfq711r01cpsmy4uv',
                targetFieldId: 'lnclb8wwog1fehv7owsoecj6j',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5plx2308myiry2npue0uz3d1w',
                name: 'refinery_page_parts_refinery_page_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ozy6j111lda7uukpdsjcd4dhh',
                targetTableId: '0kys8v69us9hbf0co0225dybz',
                sourceFieldId: 'mjn96dcqh1eglgrfbqswy8h0w',
                targetFieldId: '5w012p88r4rek8982cxclnl48',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'cl9r3l2zdykd3rugbdt6x0pg8',
                name: 'refinery_pages_parent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '0kys8v69us9hbf0co0225dybz',
                targetTableId: '0kys8v69us9hbf0co0225dybz',
                sourceFieldId: 'lzevldhuyo06sspphm4wucizo',
                targetFieldId: '5w012p88r4rek8982cxclnl48',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'e44lnvcqfwm1530359w6dew6n',
                name: 'refinery_page_part_translations_refinery_page_part_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'bgv9x5k13hzj1re3wqt0t9o4v',
                targetTableId: 'ozy6j111lda7uukpdsjcd4dhh',
                sourceFieldId: 'qllab1c60stttba572afmuiai',
                targetFieldId: '8uqx94rc08fid6ni08eryfs7o',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'uul1nr7grcd4q3ehw407tvku2',
                name: 'refinery_resource_translations_refinery_resource_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ojwtj2y46se64tt1qd7m7lkcw',
                targetTableId: 'p5hofapibkk3hf64g0ak4am2v',
                sourceFieldId: 'p56j9c43zosgj116fxg3guydb',
                targetFieldId: 'fpz87bef6sxzktbnsc2f16x7u',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vkc75adlk6trztbc7n7elu3vc',
                name: 'refinery_page_translations_refinery_page_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '92c2fr501z0r9f3w1nuv7hqth',
                targetTableId: '0kys8v69us9hbf0co0225dybz',
                sourceFieldId: 'gxucq2jirgj2154f1kbosszje',
                targetFieldId: '5w012p88r4rek8982cxclnl48',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'zmcyzmo9bdk5jbs1g6fsi2u9m',
                name: 'refinery_authentication_user_roles_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'd9lhzeswfxg2yf5rwj0u6c4h2',
                targetTableId: 'az3v69juj3jrw4xtvuv3w5f5d',
                sourceFieldId: 'mj35p9z8gx9f79n0dvfa4bskv',
                targetFieldId: '91ttm15k7g2vorzb6rgo0444u',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
