import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/snipe-it-db.png';
import imageDark from '@/assets/templates/snipe-it-db-dark.png';

const now = Date.now();

export const snipeItDb: Template = {
    slug: 'snipe-it-database',
    name: 'Snipe-It',
    shortDescription: 'Free open source IT asset management',
    description:
        'For tracking and visualizing assets with a Laravel-powered schema',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://github.com/snipe/snipe-it',
    diagram: {
        id: 'snipe_it_db',
        name: 'snipe-it-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '29v4ws6cza9exwzldm3al7ukk',
                name: 'manufacturers',
                schema: 'public',
                x: -49.99999999999997,
                y: 600,
                fields: [
                    {
                        id: 'm0b0t5o6zlhkgtj13jb3rj6tm',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('manufacturers_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'c7wgj7lldd95ttcbq1v6i7r5z',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jih406a8ozkwheozpctjt1bnj',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'em6l86idb3wvq44568ojy8x1h',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'lsr9bqh2jfqul0cawrf4ody6o',
                        name: 'manufacturers_pkey',
                        unique: true,
                        fieldIds: ['m0b0t5o6zlhkgtj13jb3rj6tm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '9gcncr71xdcz74srhajdxi3d4',
                name: 'departments',
                schema: 'public',
                x: 488.90872965260115,
                y: 559.6194077712559,
                fields: [
                    {
                        id: 'thqtiib2tn2dwhapd0ol2fjzo',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('departments_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'y5jjmvijho6u7j30p78h1kyfo',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'euwdhzg1wp6bylfjks0zuh4nf',
                        name: 'location_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4cjj3kkt620wn51waely9sdfx',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vyns2omw23hxtvs1pu6isj3qe',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'slwnqp6la1j24i5gt93uo89lp',
                        name: 'departments_pkey',
                        unique: true,
                        fieldIds: ['thqtiib2tn2dwhapd0ol2fjzo'],
                        createdAt: now,
                    },
                    {
                        id: 'auy3qr1fm32174nbm50b0sa0k',
                        name: 'idx_departments_name',
                        unique: false,
                        fieldIds: ['y5jjmvijho6u7j30p78h1kyfo'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'aqt9gvsat8bmsb7psji7u6toc',
                name: 'tickets',
                schema: 'public',
                x: -594.9747468305834,
                y: 232.67272305701886,
                fields: [
                    {
                        id: 'y6l33akqbfjhg3eepkl4wfwh4',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('tickets_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'm8av1nsf1hcptfc6n6paye7h2',
                        name: 'asset_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4w39kdvys1a2km7588eiexufx',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7pp2cy8lphuguudpfpvb599eh',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6a3eio7yrbsah8zzy8ybrsovm',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'y1u7ypv40mefrymgkhra2zkl7',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2a383uuagfr8wa4mkpn82jccm',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'va33r3goivs8z2y1s6ondlgk2',
                        name: 'tickets_pkey',
                        unique: true,
                        fieldIds: ['y6l33akqbfjhg3eepkl4wfwh4'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'd0mkjmeux1avwtq1aq41do1ms',
                name: 'assets_departments',
                schema: 'public',
                x: 888.9087296526011,
                y: 559.6194077712559,
                fields: [
                    {
                        id: 'iss2nftrbb9vazcg1v10678ed',
                        name: 'asset_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '78lg6ty9o982a6ifi65e4k99j',
                        name: 'department_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'whacapzzqm5kzv58iu9a7nbya',
                        name: 'assets_departments_pkey',
                        unique: true,
                        fieldIds: [
                            'iss2nftrbb9vazcg1v10678ed',
                            '78lg6ty9o982a6ifi65e4k99j',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'dij8tkboo7q39p94qdqs191g1',
                name: 'users',
                schema: 'public',
                x: -394.9747468305832,
                y: 665.685424949238,
                fields: [
                    {
                        id: 'nu3he7otigkya7voa2ilcvpcq',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('users_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'ps48ttjk5ebn30u1h01mf7cif',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'oedjk6mk40v9enc8b8yf2lrn5',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gc8uvfoa218571j12udh805zb',
                        name: 'password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '86o59x4z63hl4luqiksr1oyrw',
                        name: 'remember_token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'es7vujl5j3w1kumu8a2zp30ll',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'haxxbuzgojqamq2kz9fz65c7d',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'wk1rj5wqlavw9o77ln41nmubi',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['nu3he7otigkya7voa2ilcvpcq'],
                        createdAt: now,
                    },
                    {
                        id: 'lqdnu934plvvrcpq7na72ss1d',
                        name: 'users_email_key',
                        unique: true,
                        fieldIds: ['ps48ttjk5ebn30u1h01mf7cif'],
                        createdAt: now,
                    },
                    {
                        id: 'j8bh7kkt7f3gxbtf29cy123kh',
                        name: 'idx_users_email',
                        unique: false,
                        fieldIds: ['ps48ttjk5ebn30u1h01mf7cif'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'f9tjw0nac1c8otmtkua4xh73y',
                name: 'announcements',
                schema: 'public',
                x: -419.23881554251165,
                y: 1089.9494936611666,
                fields: [
                    {
                        id: 'rm8abre1xote1m9oihpqd63om',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('announcements_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'rh9t3d9pcfdfljgbeyse4jv20',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zpmrrmoosp3dx3vaptnirv1zm',
                        name: 'body',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g6zlr5p8qqm2etltdx76pvuda',
                        name: 'action_text',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'du866b1k1a7vq803mo245covi',
                        name: 'action_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uft1z5t868hej28avtmh2m8s4',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4mme2no7t3d9jwpr9fgbkrz66',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'viudmxe2s4umw9hyvcc86jx4h',
                        name: 'idx_announcements_user_id',
                        unique: false,
                        fieldIds: ['rh9t3d9pcfdfljgbeyse4jv20'],
                        createdAt: now,
                    },
                    {
                        id: 'qjibuua3hrny94d6z15uka2e9',
                        name: 'announcements_pkey',
                        unique: true,
                        fieldIds: ['rm8abre1xote1m9oihpqd63om'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ffvfm6f2835bxy763oezmhq9b',
                name: 'locations',
                schema: 'public',
                x: 288.9087296526012,
                y: 992.6321096634751,
                fields: [
                    {
                        id: '728n5xow82pj4jmszi11408a5',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('locations_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '0ivxybxsru506k9y8vetybefz',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '1fufafdu0kbtyk6tjwx3mkp7e',
                        name: 'address',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fjqtati7ql4ikgg4zrdysdyf6',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gmxslfpx75j91py07bnu5krpy',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'emvvonlv5lc5obln86knm8mpu',
                        name: 'idx_locations_name',
                        unique: false,
                        fieldIds: ['0ivxybxsru506k9y8vetybefz'],
                        createdAt: now,
                    },
                    {
                        id: 'e3vlo1znvr6la5xgrpnfjpmx9',
                        name: 'locations_pkey',
                        unique: true,
                        fieldIds: ['728n5xow82pj4jmszi11408a5'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                name: 'assets',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'hqp6bxym8g6ms3w3vt7f31ywq',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('assets_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '1nie7ygadkg6r3yuhzigc9ml1',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ieerp2kaa7k8ekgld0rlpttin',
                        name: 'serial',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qo8lrpd3fb8ltkatsgzez5rl6',
                        name: 'manufacturer_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'akq22zkf7hfhzgojv63jl5mmq',
                        name: 'category_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nvo2jzz6b9jq9ga8e2lzopl4n',
                        name: 'location_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sovbsi9ykfqpr8bftc8d9l687',
                        name: 'department_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w8uafrnm06hizt01jw7sqx0ay',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ttlir0dsodgczpyu63ktxnyaz',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tr7junzlm7xzxy6tv9rfmskyq',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '109pedfj3zlwgw7x17z07sri8',
                        name: 'idx_assets_name',
                        unique: false,
                        fieldIds: ['1nie7ygadkg6r3yuhzigc9ml1'],
                        createdAt: now,
                    },
                    {
                        id: 'a1f5jk16ehacvtc385zm0ieh8',
                        name: 'assets_pkey',
                        unique: true,
                        fieldIds: ['hqp6bxym8g6ms3w3vt7f31ywq'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'l82uf64ic8m1v3gi01mys2lq9',
                name: 'notifications',
                schema: 'public',
                x: -794.9747468305832,
                y: 665.6854249492382,
                fields: [
                    {
                        id: '3a8dd2dr9j741475lvz9w535n',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('notifications_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'prikl42cn9lx1n9emhz4mu7yq',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'jucd5cm6hy4p7kbac1ku1v72c',
                        name: 'message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pkxxhhz7bzojzwhjt1tj06myp',
                        name: 'is_read',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'k3ygf755g81u2slnc6znxb4g9',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pfvbw4j70m0ww5dv8fiea6d0r',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tz17evmawpm8n4mo5o0rt8l3r',
                        name: 'idx_notifications_user_id',
                        unique: false,
                        fieldIds: ['prikl42cn9lx1n9emhz4mu7yq'],
                        createdAt: now,
                    },
                    {
                        id: 'jzud0kjk3rxmm0a1r9p3fh4g2',
                        name: 'notifications_pkey',
                        unique: true,
                        fieldIds: ['3a8dd2dr9j741475lvz9w535n'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ppwcitqjfqq174m7dthgrovfs',
                name: 'password_resets',
                schema: 'public',
                x: 650,
                y: 1100,
                fields: [
                    {
                        id: 'gqg3znfr9qzx5b4b20wto5hjo',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6262o6z79z2n1dljr6k8bh5sc',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'cso11nttqhs12xu00nxbs21r1',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'o0ejn7gf43rbd9e9cjiqny1cx',
                        name: 'password_resets_pkey',
                        unique: true,
                        fieldIds: ['gqg3znfr9qzx5b4b20wto5hjo'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'qbczan7ykpkqz7206wudxmgtp',
                name: 'invoices',
                schema: 'public',
                x: -744.9747468305831,
                y: 1098.6981268414575,
                fields: [
                    {
                        id: 'hlfnrnmozo119wwvtgsblv9u9',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('invoices_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'enbx5078tzufrn0y7ttm0aeov',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sxn0pz881z5pp2so9ppkpco9c',
                        name: 'amount',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: '08ha5fg9kfnmataebchctmyxb',
                        name: 'due_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'udjeu8ew7m0ak4r2aojldqhti',
                        name: 'status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tggkxsjqmyicwjwh22tkcosh8',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x703lgwbw7exdg0z3180kfwvr',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '34scxr72oslemxuiis342eryz',
                        name: 'idx_invoices_user_id',
                        unique: false,
                        fieldIds: ['enbx5078tzufrn0y7ttm0aeov'],
                        createdAt: now,
                    },
                    {
                        id: '898sqiujupoyk7frfdmiaafdk',
                        name: 'invoices_pkey',
                        unique: true,
                        fieldIds: ['hlfnrnmozo119wwvtgsblv9u9'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ugav1xjtjdyr5vfghur1h6340',
                name: 'maintenance',
                schema: 'public',
                x: -300.00000000000006,
                y: -199.99999999999994,
                fields: [
                    {
                        id: '67a0fvhtrj9ga0fugb3r60vtf',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('maintenance_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'ubu8l1ydpalv4lty2gi7i70kz',
                        name: 'asset_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'u4qh5p38t832l8508z2mnmwqa',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gkmvb1sz32pbwov34xfz193rr',
                        name: 'date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fq5nb0afbcv3eccpfdhy1ni4b',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'usvz5a9ct4oj182sbac64fi82',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '095phuqic5wpos5gftbo87yzg',
                        name: 'maintenance_pkey',
                        unique: true,
                        fieldIds: ['67a0fvhtrj9ga0fugb3r60vtf'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'w8oufyqqtq1nziht8qkilr8sk',
                name: 'categories',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'gmxe57sfvks6oyeawm7riergd',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('categories_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'xqd8yv56sj4ruw0pdafzym25l',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8va4d40rw10qa6hk6lmu4gmj4',
                        name: 'parent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'c8ioi75gxuuruu1qovhdyqisj',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qhum8q0qtbhjqtbrp0y7unkyn',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5v1ej5m7ca2918e2jv4gjhgxj',
                        name: 'idx_categories_name',
                        unique: false,
                        fieldIds: ['xqd8yv56sj4ruw0pdafzym25l'],
                        createdAt: now,
                    },
                    {
                        id: '1la3spjexqkyw994wer52wplc',
                        name: 'categories_pkey',
                        unique: true,
                        fieldIds: ['gmxe57sfvks6oyeawm7riergd'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zklx3zotwnp54mzmvomis61gt',
                name: 'api_tokens',
                schema: 'public',
                x: -44.974746830583115,
                y: 1098.6981268414575,
                fields: [
                    {
                        id: 'g4dc7oz2zta9az8t793fmck2t',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval('api_tokens_id_seq'::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'iu1wfvffursno9rz9sy1ukifa',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'keyu8vcr514705z1j3i2pfpn2',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'sxnobuli69iin9zryafegqz4l',
                        name: 'token',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tygu0g6gveg3p393xdpyl4i9g',
                        name: 'expires_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'js37tir385vh3xsvqku2kvbrr',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ws8h2b1dab8miileukh39lpr6',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'pcuj5jo46idyfqixwdnr9hawg',
                        name: 'api_tokens_pkey',
                        unique: true,
                        fieldIds: ['g4dc7oz2zta9az8t793fmck2t'],
                        createdAt: now,
                    },
                    {
                        id: 'qi5q29fia5g3t6f5u2ao5ftl2',
                        name: 'api_tokens_token_key',
                        unique: true,
                        fieldIds: ['sxnobuli69iin9zryafegqz4l'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '3bl6wdsmq8ru284mkzpaqfra2',
                name: 'assets_departments_department_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'd0mkjmeux1avwtq1aq41do1ms',
                targetTableId: '9gcncr71xdcz74srhajdxi3d4',
                sourceFieldId: '78lg6ty9o982a6ifi65e4k99j',
                targetFieldId: 'thqtiib2tn2dwhapd0ol2fjzo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6d7nzsjcbhm3ru0um23l5xqhs',
                name: 'maintenance_asset_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ugav1xjtjdyr5vfghur1h6340',
                targetTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                sourceFieldId: 'ubu8l1ydpalv4lty2gi7i70kz',
                targetFieldId: 'hqp6bxym8g6ms3w3vt7f31ywq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6mb9ahqjbh3vyy4d3yy6av56m',
                name: 'assets_manufacturer_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                targetTableId: '29v4ws6cza9exwzldm3al7ukk',
                sourceFieldId: 'qo8lrpd3fb8ltkatsgzez5rl6',
                targetFieldId: 'm0b0t5o6zlhkgtj13jb3rj6tm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'b6aim2soqplyd67j5kqwotchq',
                name: 'invoices_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'qbczan7ykpkqz7206wudxmgtp',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: 'enbx5078tzufrn0y7ttm0aeov',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fdgvzi4kstd0jd3sc8scem2c3',
                name: 'assets_departments_asset_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'd0mkjmeux1avwtq1aq41do1ms',
                targetTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                sourceFieldId: 'iss2nftrbb9vazcg1v10678ed',
                targetFieldId: 'hqp6bxym8g6ms3w3vt7f31ywq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'gzg5jumr6l2pn7ajsmf8orrs9',
                name: 'departments_location_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '9gcncr71xdcz74srhajdxi3d4',
                targetTableId: 'ffvfm6f2835bxy763oezmhq9b',
                sourceFieldId: 'euwdhzg1wp6bylfjks0zuh4nf',
                targetFieldId: '728n5xow82pj4jmszi11408a5',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hydyrblwbzyexplek8wzm3cke',
                name: 'tickets_asset_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'aqt9gvsat8bmsb7psji7u6toc',
                targetTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                sourceFieldId: 'm8av1nsf1hcptfc6n6paye7h2',
                targetFieldId: 'hqp6bxym8g6ms3w3vt7f31ywq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'kjoon43dtxtalwlnymqib8ote',
                name: 'api_tokens_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'zklx3zotwnp54mzmvomis61gt',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: 'iu1wfvffursno9rz9sy1ukifa',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'mjrulubxg0lpx5qxvtrs85z8n',
                name: 'notifications_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'l82uf64ic8m1v3gi01mys2lq9',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: 'prikl42cn9lx1n9emhz4mu7yq',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'mnp0avfbisw7gy8kri8npmsdk',
                name: 'assets_location_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                targetTableId: 'ffvfm6f2835bxy763oezmhq9b',
                sourceFieldId: 'nvo2jzz6b9jq9ga8e2lzopl4n',
                targetFieldId: '728n5xow82pj4jmszi11408a5',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rf75bt0r0i971l7v5be7pb9le',
                name: 'categories_parent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'w8oufyqqtq1nziht8qkilr8sk',
                targetTableId: 'w8oufyqqtq1nziht8qkilr8sk',
                sourceFieldId: '8va4d40rw10qa6hk6lmu4gmj4',
                targetFieldId: 'gmxe57sfvks6oyeawm7riergd',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rojmfwlsa4d49jhko581q3wen',
                name: 'assets_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: 'w8uafrnm06hizt01jw7sqx0ay',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vr9b7v1e6t8oqe0mzb6jctlk5',
                name: 'tickets_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'aqt9gvsat8bmsb7psji7u6toc',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: '4w39kdvys1a2km7588eiexufx',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'xza9qob37bymmkj5lwed9etuv',
                name: 'assets_category_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                targetTableId: 'w8oufyqqtq1nziht8qkilr8sk',
                sourceFieldId: 'akq22zkf7hfhzgojv63jl5mmq',
                targetFieldId: 'gmxe57sfvks6oyeawm7riergd',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'yg6lgz90nn9syiw4g9c76pscs',
                name: 'announcements_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'f9tjw0nac1c8otmtkua4xh73y',
                targetTableId: 'dij8tkboo7q39p94qdqs191g1',
                sourceFieldId: 'rh9t3d9pcfdfljgbeyse4jv20',
                targetFieldId: 'nu3he7otigkya7voa2ilcvpcq',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'yw3kr853lwxfolflp3annw1n3',
                name: 'assets_department_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hxpfhx7gb3dkdnc70nvuqo9bp',
                targetTableId: '9gcncr71xdcz74srhajdxi3d4',
                sourceFieldId: 'sovbsi9ykfqpr8bftc8d9l687',
                targetFieldId: 'thqtiib2tn2dwhapd0ol2fjzo',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
