import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/staytus-db.png';
import imageDark from '@/assets/templates/staytus-db-dark.png';

const now = Date.now();

export const staytusDb: Template = {
    slug: 'staytus-database',
    name: 'Staytus',
    shortDescription: 'Service status publishing solution',
    description:
        'An open-source platform for publishing the status of your services, providing beautiful public and admin interfaces.',
    image,
    imageDark,
    tags: ['MySQL', 'Open Source', 'Rails'],
    featured: true,
    url: 'https://github.com/adamcooke/staytus',
    diagram: {
        id: 'staytus_db',
        name: 'staytus-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.MYSQL,
        tables: [
            {
                id: '0g6y4lqz8r2s0f1frzdsklep3',
                name: 'maintenances',
                schema: 't_staytus_db',
                x: 2260,
                y: 100,
                fields: [
                    {
                        id: 'uec8qvmjsjyc3eyt0ob6g1lo4',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'llujh8t25ff7c1is70ep8u5do',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'h9pse4cqmchzi3w685ssfde7o',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '6ol1oh7n9wywvl4vrqqzqw4tq',
                        name: 'start_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qvr5uie0jlzroqbh44589f7v1',
                        name: 'finish_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dqxyfu4ewhb0fuxrg7slrnel0',
                        name: 'length_in_minutes',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i07uatas3r3nsj3x277nfgtgq',
                        name: 'user_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'win0hcvv3oxsw4vk7evvddao2',
                        name: 'service_status_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7ryh3dr8o3gbheab4hindw7gn',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ra2evksjk2rbku64d3gsuctgd',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vdv729crfxnldatfgknxox31s',
                        name: 'closed_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'exbmkiz87wse3sqhsx2eyjyv3',
                        name: 'identifier',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'lfp5r2qtfjpm349x0gdh34uvr',
                        name: 'notify',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '0ewkap9s608o3lxqxytbjev38',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['uec8qvmjsjyc3eyt0ob6g1lo4'],
                        createdAt: now,
                    },
                    {
                        id: 'cid1j08voe69kpw75d6ry873k',
                        name: 'maintenances_service_status_id_foreign',
                        unique: false,
                        fieldIds: ['win0hcvv3oxsw4vk7evvddao2'],
                        createdAt: now,
                    },
                    {
                        id: 'm8z30ytau823v5xslhj1t3794',
                        name: 'maintenances_user_id_foreign',
                        unique: false,
                        fieldIds: ['i07uatas3r3nsj3x277nfgtgq'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '2dfe92ureapqe4n4hxv54bw5x',
                name: 'issue_updates',
                schema: 't_staytus_db',
                x: 1420,
                y: 400,
                fields: [
                    {
                        id: 'q23xz0e62etyc5rxl5fk1vb0z',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3huo3ep5ftlwm0phkn8d6urbq',
                        name: 'issue_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f5149o44pkz5sn61i4m4itn6q',
                        name: 'user_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ftvkprxy3bw4lvx94j3wjyc0p',
                        name: 'service_status_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hle17dqp0sjv6xuhdva0vsugt',
                        name: 'state',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '57jh963nk2duy6rcuzpqxiwd7',
                        name: 'text',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'cehjbntug4uy919jcdt3joovi',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zx8t6rkegqw433yckdhy6karg',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i8bb5x9qsbs1d933y2jxndig9',
                        name: 'identifier',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '9o218g5m4bs1vwlediqjd9h7b',
                        name: 'notify',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vzt1xy8ozwy52fugtia7yiukc',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['q23xz0e62etyc5rxl5fk1vb0z'],
                        createdAt: now,
                    },
                    {
                        id: 'xaqtf6bks9ym18b9nf62aqx1y',
                        name: 'issue_updates_issue_id_foreign',
                        unique: false,
                        fieldIds: ['3huo3ep5ftlwm0phkn8d6urbq'],
                        createdAt: now,
                    },
                    {
                        id: '9jq5xtabi67a8j1modrsi77ae',
                        name: 'issue_updates_service_status_id_foreign',
                        unique: false,
                        fieldIds: ['ftvkprxy3bw4lvx94j3wjyc0p'],
                        createdAt: now,
                    },
                    {
                        id: '812qcj18okqh5di677sxsivs1',
                        name: 'issue_updates_user_id_foreign',
                        unique: false,
                        fieldIds: ['f5149o44pkz5sn61i4m4itn6q'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '4k36q8p2lmugq9ophivx8893g',
                name: 'email_templates',
                schema: 't_staytus_db',
                x: 980,
                y: 300,
                fields: [
                    {
                        id: '5lpim898x5ttzvxpoi41zf6rj',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4kieqa4ce7xgqpgxf4v8qw5e9',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'f2e98lk5z0cjp3ey5qbl99n97',
                        name: 'subject',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'u3f8tmxzgw0cuncvljoenrdh4',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '03vz3at5tyf4g1h4567u9qc6z',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'arseju0svgq3zea5w4nqg2s8v',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '99n24ubcx17jr0ioq1be33a06',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['5lpim898x5ttzvxpoi41zf6rj'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'a37clougxq0ts3bxx4xagcdkk',
                name: 'issue_service_joins',
                schema: 't_staytus_db',
                x: 1340,
                y: 1060,
                fields: [
                    {
                        id: 'wdr6j56qa1uc99shh4a0nfyhj',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'emb6xna8sr3wd29oovid4b2nb',
                        name: 'issue_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '58bvgcijjsdxzgw6ukill1zo2',
                        name: 'service_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f06g60jgg10ufj9ts3w10vvwm',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'evnmfzv5i6luss8f662b00s39',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'd99aa4uks0iq3vlsduwhlvsaw',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['wdr6j56qa1uc99shh4a0nfyhj'],
                        createdAt: now,
                    },
                    {
                        id: 'gcrmlf0n2jc1ugos85vm7qqja',
                        name: 'issue_service_joins_service_id_foreign',
                        unique: false,
                        fieldIds: ['58bvgcijjsdxzgw6ukill1zo2'],
                        createdAt: now,
                    },
                    {
                        id: 'wgytkayv2l5zur5o3em23rygq',
                        name: 'issue_service_joins_issue_id_foreign',
                        unique: false,
                        fieldIds: ['emb6xna8sr3wd29oovid4b2nb'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'b2gxamp2gt9j785k5abstt1if',
                name: 'history_items',
                schema: 't_staytus_db',
                x: 720,
                y: 540,
                fields: [
                    {
                        id: 'p61xa77uo395h1mu2eu2qj4yb',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '98vm8oinmunmbv6o64d45pobe',
                        name: 'item_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'kmlzuzbbf07ho6tcbi03kuvy0',
                        name: 'item_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8swrvw0jr27gyyv3kidf80a60',
                        name: 'date',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'eu6t0inzhw7wmkro7kewn1kfw',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['p61xa77uo395h1mu2eu2qj4yb'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c0nf3rv6aurgeu4v4sb80alfa',
                name: 'users',
                schema: 't_staytus_db',
                x: 2160,
                y: 760,
                fields: [
                    {
                        id: 'vrzwr7lu2hpqdqpz4hl8ufyex',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8rgf912c5nf9g373gpr70h03x',
                        name: 'email_address',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '94neqxt1fj40bxaay8mc11wdy',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'qcekauvexznfcyasektcvkba9',
                        name: 'password_digest',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'y58p386j1hcs07v6kkc37ym6w',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pyiw4cyyhm4sr6e649f1i460s',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '17iesz4tkufa0x0nx6hv3tvf4',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['vrzwr7lu2hpqdqpz4hl8ufyex'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'czbdab8cspeejqxrkiiuo7qye',
                name: 'issues',
                schema: 't_staytus_db',
                x: 1800,
                y: 920,
                fields: [
                    {
                        id: 'rl329e4vykjc5xv45hmcdvs7x',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8lybdggqtfhsa9us0roz9d4em',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '6s4ekwra17z058qjfydr8j6rv',
                        name: 'state',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'e1r31s3espm10lquo1wu8puwm',
                        name: 'service_status_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2ydcn1fxx4tfy8syts46yb1zh',
                        name: 'all_services',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6exnpipgvs345fzwje5vivogr',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'q0psxlmj7dul4uki56zu8p1zf',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ypy405vin8689dk90t5e8awwc',
                        name: 'user_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '154gt2jpjtzgder8zac9wh5k8',
                        name: 'identifier',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ecmuzclgzy092amsgzn7qjsbj',
                        name: 'notify',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '203w08u24843g41cy9l8cssdz',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['rl329e4vykjc5xv45hmcdvs7x'],
                        createdAt: now,
                    },
                    {
                        id: 'qni9eoeg9rew6m7yga0t1mdsh',
                        name: 'issues_user_id_foreign',
                        unique: false,
                        fieldIds: ['ypy405vin8689dk90t5e8awwc'],
                        createdAt: now,
                    },
                    {
                        id: 'b208tntnuc3ebt2vmoaxtvafr',
                        name: 'issues_service_status_id_foreign',
                        unique: false,
                        fieldIds: ['e1r31s3espm10lquo1wu8puwm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'd5js6gwtocry906qkehcusydy',
                name: 'service_statuses',
                schema: 't_staytus_db',
                x: 1820,
                y: 180,
                fields: [
                    {
                        id: '4ylkkblyu3f3h57rhuslcsf9u',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6z05h0143apzo8poc8csqpy6j',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'hg59mk2peb3sctx4igeledvmv',
                        name: 'permalink',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '89oij5cx7wksixy0u66ar0x0u',
                        name: 'color',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'hqayf9ybw39zpybkectxnlkva',
                        name: 'status_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'xzh3iuwxjhfv1qbk7bn5jb61o',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rc99cbr4kdem191sk47e1dygo',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '6oa5ktaeswz1s8wj7jj4z3uh1',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['4ylkkblyu3f3h57rhuslcsf9u'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'dau33uzp82nosjepxy2in8nqi',
                name: 'subscribers',
                schema: 't_staytus_db',
                x: 980,
                y: 20,
                fields: [
                    {
                        id: 'acq9ot8s555ffu2sk13ey5emo',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'uc6oz8qpi7lq8q84517zp6ze1',
                        name: 'email_address',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'agp2h28omgrerfr36fyytfet4',
                        name: 'verification_token',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'l3naxsa2r5wkd4dwc4ntchpzh',
                        name: 'verified_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lb76qv6tr5tvqv73z6hkz6owv',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xkioyacaw3obogeqedzqjkb2l',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bnya1j4dv5s55fpc7r1d78d3y',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['acq9ot8s555ffu2sk13ey5emo'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'grpts66abujxx6gpro0hiqt1o',
                name: 'services',
                schema: 't_staytus_db',
                x: 1440,
                y: -160,
                fields: [
                    {
                        id: 'n8efkgaj2ik4zbjf8842sun97',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rf3otnxb3b9v8yriyxg6idyj1',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'raqmgxhp0qs08xez87c1couxc',
                        name: 'permalink',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'b3gnntsvvfo8npbnzb412fqg6',
                        name: 'position',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'm0pzlbjrcwv77ny5t8b3vwrh2',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xhzkwd9ze1wzcyhebqmxv98xk',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'h01qaw51hp219ix6sfiw5eyw8',
                        name: 'status_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nn8menylb0k5438v18ebjeauk',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'nvmn090gv9ua3silqubvqdcal',
                        name: 'group_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '115dhang67y0im2p3gzawjauy',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['n8efkgaj2ik4zbjf8842sun97'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'j4hgct19im0ei9rcojyvtth37',
                name: 'maintenance_service_joins',
                schema: 't_staytus_db',
                x: 1840,
                y: -260,
                fields: [
                    {
                        id: 'js12beggk6epunil5q25q03w3',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'm88n5l0ihz96g8g5gccxcrfnd',
                        name: 'maintenance_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i46cg5rpmtxwxt26qy2kmmooz',
                        name: 'service_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4luugl08vxs6jm1tb2nvj4yez',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ofiz3xfa8o2ywe0gxl9znjnvu',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '88zqwpt86x5p3a75r777wjxcy',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['js12beggk6epunil5q25q03w3'],
                        createdAt: now,
                    },
                    {
                        id: 'yvuk1o2tgxcxbm46l62j5gali',
                        name: 'maintenance_service_joins_service_id_foreign',
                        unique: false,
                        fieldIds: ['i46cg5rpmtxwxt26qy2kmmooz'],
                        createdAt: now,
                    },
                    {
                        id: '1ffizfe7z67al3pwlpboh51ct',
                        name: 'maintenance_service_joins_maintenance_id_foreign',
                        unique: false,
                        fieldIds: ['m88n5l0ihz96g8g5gccxcrfnd'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'js833ozrqu0ahqlvdtvub5e1w',
                name: 'nifty_attachments',
                schema: 't_staytus_db',
                x: 980,
                y: 800,
                fields: [
                    {
                        id: '2cpwgtfacjocpwapm3u7lzis5',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wmkvsq6cg807v9hmczpnojx2x',
                        name: 'parent_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lbus7jul4rh5st35kg4simts7',
                        name: 'parent_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '4f9542vo3g1pxtaavbchyhl4i',
                        name: 'token',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '3baa3eustwoepsyncrrders8h',
                        name: 'digest',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '79x2a7n33wucok5z31pbym4jh',
                        name: 'role',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'fxe9k4z6h5zzscvyyy70dijjq',
                        name: 'file_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'rpica94cidday7eyn3cgsxgcr',
                        name: 'file_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'xr88q5g1oboflm3h2tkz4vq2p',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g74osj819y5rd0mhk9zgn8qjm',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'fdnk345oot3i10agtrzystyn6',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['2cpwgtfacjocpwapm3u7lzis5'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'll9l5paivbwcyghae9fmz6rla',
                name: 'maintenance_updates',
                schema: 't_staytus_db',
                x: 2640,
                y: 700,
                fields: [
                    {
                        id: 'z2hrcqiud7svg6nkwek0o4k4e',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sfqgoj2rpzfqg9gx4d4jjwil8',
                        name: 'maintenance_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9d5e1037vumn767pm68cvw8ko',
                        name: 'user_id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2j8igatoudxooz9tpqouw49wk',
                        name: 'text',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'bfaokb7m2um4wxzztlxftgkr7',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'c827zalc08gc3kytkb9x3q5pi',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jwjyb21fxlfyb64g9x2tuyj4c',
                        name: 'identifier',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'cxjn2vieevo50x9zu9mzle4p3',
                        name: 'notify',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'pc5t200dh6kfq6xq3pun5swqc',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['z2hrcqiud7svg6nkwek0o4k4e'],
                        createdAt: now,
                    },
                    {
                        id: '0rw5b6txruvh04sfncxyksoc5',
                        name: 'maintenance_updates_user_id_foreign',
                        unique: false,
                        fieldIds: ['9d5e1037vumn767pm68cvw8ko'],
                        createdAt: now,
                    },
                    {
                        id: 'tbolhha9a7v8tlumk4ayqcrz2',
                        name: 'maintenance_updates_maintenance_id_foreign',
                        unique: false,
                        fieldIds: ['sfqgoj2rpzfqg9gx4d4jjwil8'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'oetpge5zxdnpwukcfvtq557rq',
                name: 'delayed_jobs',
                schema: 't_staytus_db',
                x: 720,
                y: -200,
                fields: [
                    {
                        id: 'tdmbg0fhg8e738oemx9vk4h2a',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '1sky9o7smcqijj93alxz0fhk0',
                        name: 'priority',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd1a07yqmilzaqgsk2342ene57',
                        name: 'attempts',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2ahemgkz8irydabhuinz7cc0o',
                        name: 'handler',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '6ml6qugkiqunc04ye1x1yjss2',
                        name: 'last_error',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'gtfnvpxjg9uf04gtfst9buk12',
                        name: 'run_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nt6znxx9f9e412bk0cmxhtm1m',
                        name: 'locked_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xcewih8h0euvuzee4ookmwv8x',
                        name: 'failed_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0nj1jvwnaa1od4vda38dx9qgy',
                        name: 'locked_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ksuux2ns62lt2w9suv0eaigo3',
                        name: 'queue',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '0kn0m44a6d6orfh7b18qam2a9',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xlscf5cl4rvytac2byh8f30is',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qo5f0mkh1whmflnvqfiluhwpe',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['tdmbg0fhg8e738oemx9vk4h2a'],
                        createdAt: now,
                    },
                    {
                        id: 'arx8egq3hiejrqpa1cc2qg094',
                        name: 'delayed_jobs_priority_run_at_index',
                        unique: false,
                        fieldIds: [
                            '1sky9o7smcqijj93alxz0fhk0',
                            'gtfnvpxjg9uf04gtfst9buk12',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'qj3k989r08fiytsb69actqlve',
                name: 'sites',
                schema: 't_staytus_db',
                x: 720,
                y: 780,
                fields: [
                    {
                        id: '5qmffm48z3ytoys9ryy7rtr5b',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xz1m9h2q9lbbjbdxuoxc8xp89',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'f067ttfu6i7yeui1t8igpfqhq',
                        name: 'description',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'hktz9r8kquur7ooa844s8ywwm',
                        name: 'domain',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '2c2ugfbe9jxv6lmzodqs1m9f2',
                        name: 'support_email',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'hu0plfefx7rb91dczem468l7t',
                        name: 'website_url',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'qlh82vqij4qrbo85w3rgsw57c',
                        name: 'time_zone',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'dvn2as5apajy0lwhcl8ulq7fk',
                        name: 'crawling_permitted',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wnqqnnox26c0iyt8f13axi41c',
                        name: 'email_from_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'g2in3lqgztjueajby9ceozc97',
                        name: 'email_from_address',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'ohs3a489y0qtr5wktct90jjz9',
                        name: 'allow_subscriptions',
                        type: {
                            id: 'tinyint',
                            name: 'tinyint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mj7023r7agkv8bplkqyynl73c',
                        name: 'http_protocol',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'w859tkugs5zm21jzob0ns8ixa',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['5qmffm48z3ytoys9ryy7rtr5b'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'qwvef3qmweu7f30uy1zn3pma9',
                name: 'service_groups',
                schema: 't_staytus_db',
                x: 980,
                y: 580,
                fields: [
                    {
                        id: '5n0rej8wov1cuiu4rojhphjhq',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bs14e7bajtrrol12q0yltxj50',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'qv83ohlaw18czz4gqr6jolifv',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dzr8cp4r5heo8a1hr9c5627ry',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'v4lh3jo0fbqroupfxccndpm2y',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['5n0rej8wov1cuiu4rojhphjhq'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'u33vrcdis4tbjx8ecru7pc4e1',
                name: 'api_tokens',
                schema: 't_staytus_db',
                x: 720,
                y: 260,
                fields: [
                    {
                        id: '2t3nmlmh26z2t6beufqnt32u0',
                        name: 'id',
                        type: {
                            id: 'int',
                            name: 'int',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '20vip2n3ox713p1fxxtqounhw',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'le54gonncqvb4cl58xxs65id5',
                        name: 'token',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: 'h3bnty6pgyxctl9nrvstk2tj4',
                        name: 'secret',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                    {
                        id: '9jijcg1vvvye7loyffhezdbuv',
                        name: 'created_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3fx6m813n5u934ls4d62lw2ai',
                        name: 'updated_at',
                        type: {
                            id: 'datetime',
                            name: 'datetime',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'dqd7pvopeapi7prarsly1mfw8',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['2t3nmlmh26z2t6beufqnt32u0'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vhzp9fmqtb634958p9oiu954t',
                name: 'schema_migrations',
                schema: 't_staytus_db',
                x: 980,
                y: -100,
                fields: [
                    {
                        id: '8tskgia6di4cdzmay2ybj3utz',
                        name: 'version',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        collation: 'utf8mb4_0900_ai_ci',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'zqjuulo8bqegav463p0h8gxs8',
                        name: 'PRIMARY',
                        unique: true,
                        fieldIds: ['8tskgia6di4cdzmay2ybj3utz'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '1ftjqep1uoc19jui5c7bjfi6a',
                name: 'issue_updates_service_status_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: '2dfe92ureapqe4n4hxv54bw5x',
                targetTableId: 'd5js6gwtocry906qkehcusydy',
                sourceFieldId: 'ftvkprxy3bw4lvx94j3wjyc0p',
                targetFieldId: '4ylkkblyu3f3h57rhuslcsf9u',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6uo6fpzcy8l6t2fczkdbzs1t3',
                name: 'maintenance_updates_user_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'll9l5paivbwcyghae9fmz6rla',
                targetTableId: 'c0nf3rv6aurgeu4v4sb80alfa',
                sourceFieldId: '9d5e1037vumn767pm68cvw8ko',
                targetFieldId: 'vrzwr7lu2hpqdqpz4hl8ufyex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '9ez6y26qsei1922e981dnth1l',
                name: 'issues_service_status_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'czbdab8cspeejqxrkiiuo7qye',
                targetTableId: 'd5js6gwtocry906qkehcusydy',
                sourceFieldId: 'e1r31s3espm10lquo1wu8puwm',
                targetFieldId: '4ylkkblyu3f3h57rhuslcsf9u',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'a4cjgzag00tz49lov7hin20n2',
                name: 'issue_service_joins_issue_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'a37clougxq0ts3bxx4xagcdkk',
                targetTableId: 'czbdab8cspeejqxrkiiuo7qye',
                sourceFieldId: 'emb6xna8sr3wd29oovid4b2nb',
                targetFieldId: 'rl329e4vykjc5xv45hmcdvs7x',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'agylss1pgizqt7i15ilqw6m67',
                name: 'maintenances_user_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: '0g6y4lqz8r2s0f1frzdsklep3',
                targetTableId: 'c0nf3rv6aurgeu4v4sb80alfa',
                sourceFieldId: 'i07uatas3r3nsj3x277nfgtgq',
                targetFieldId: 'vrzwr7lu2hpqdqpz4hl8ufyex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'doygqq2xx7vh5hsha6768s3qw',
                name: 'maintenances_service_status_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: '0g6y4lqz8r2s0f1frzdsklep3',
                targetTableId: 'd5js6gwtocry906qkehcusydy',
                sourceFieldId: 'win0hcvv3oxsw4vk7evvddao2',
                targetFieldId: '4ylkkblyu3f3h57rhuslcsf9u',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'f4wq0g29fsadu7bji6kf2iwiw',
                name: 'issue_service_joins_service_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'a37clougxq0ts3bxx4xagcdkk',
                targetTableId: 'grpts66abujxx6gpro0hiqt1o',
                sourceFieldId: '58bvgcijjsdxzgw6ukill1zo2',
                targetFieldId: 'n8efkgaj2ik4zbjf8842sun97',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fg6cxcjo5n75x0mnn9vsrpz6g',
                name: 'issue_updates_issue_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: '2dfe92ureapqe4n4hxv54bw5x',
                targetTableId: 'czbdab8cspeejqxrkiiuo7qye',
                sourceFieldId: '3huo3ep5ftlwm0phkn8d6urbq',
                targetFieldId: 'rl329e4vykjc5xv45hmcdvs7x',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ht2gy8v0pjbl05felmu9ofvvk',
                name: 'maintenance_service_joins_service_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'j4hgct19im0ei9rcojyvtth37',
                targetTableId: 'grpts66abujxx6gpro0hiqt1o',
                sourceFieldId: 'i46cg5rpmtxwxt26qy2kmmooz',
                targetFieldId: 'n8efkgaj2ik4zbjf8842sun97',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'i8r5ezusju31bix7vf5stziqw',
                name: 'maintenance_service_joins_maintenance_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'j4hgct19im0ei9rcojyvtth37',
                targetTableId: '0g6y4lqz8r2s0f1frzdsklep3',
                sourceFieldId: 'm88n5l0ihz96g8g5gccxcrfnd',
                targetFieldId: 'uec8qvmjsjyc3eyt0ob6g1lo4',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ujfj4hph8fxuwb86hik7pytxg',
                name: 'issue_updates_user_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: '2dfe92ureapqe4n4hxv54bw5x',
                targetTableId: 'c0nf3rv6aurgeu4v4sb80alfa',
                sourceFieldId: 'f5149o44pkz5sn61i4m4itn6q',
                targetFieldId: 'vrzwr7lu2hpqdqpz4hl8ufyex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'wqhuhzlk270w95qob8rkx5p58',
                name: 'maintenance_updates_maintenance_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'll9l5paivbwcyghae9fmz6rla',
                targetTableId: '0g6y4lqz8r2s0f1frzdsklep3',
                sourceFieldId: 'sfqgoj2rpzfqg9gx4d4jjwil8',
                targetFieldId: 'uec8qvmjsjyc3eyt0ob6g1lo4',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'yw48nli4sicx73rpprsmlfvnp',
                name: 'issues_user_id_foreign',
                sourceSchema: 't_staytus_db',
                targetSchema: 't_staytus_db',
                sourceTableId: 'czbdab8cspeejqxrkiiuo7qye',
                targetTableId: 'c0nf3rv6aurgeu4v4sb80alfa',
                sourceFieldId: 'ypy405vin8689dk90t5e8awwc',
                targetFieldId: 'vrzwr7lu2hpqdqpz4hl8ufyex',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
