import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/ticketit-db.png';
import imageDark from '@/assets/templates/ticketit-db-dark.png';

const now = Date.now();

export const ticketitDb: Template = {
    slug: 'ticketit-database',
    name: 'Ticketit',
    shortDescription: 'A simple helpdesk tickets system for Laravel',
    description:
        'Which integrates smoothly with Laravel default users and auth system',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://github.com/spatie/ticketit',
    diagram: {
        id: 'ticketit_db',
        name: 'ticketit-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '3j13z4t0omj0m67obfela7uva',
                name: 'ticketit_audits',
                schema: 'public',
                x: 763.5589024326482,
                y: -310.1468134034137,
                fields: [
                    {
                        id: 'k6iv8ifwf2x5copb6v8r6v7iu',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd3mi2mtrr2jc2n95k7nwdt70s',
                        name: 'operation',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'e3fgy0e6csdti4pi3ui9b3fks',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wdsh73xzbbsi54pab7xtad191',
                        name: 'ticket_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'n01hkpxj6fq3zyr3v0x23a8om',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qmlwi5i0753kcajivc502ema8',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'o8vktyolalexvwn8ol1dxxzcy',
                        name: 'idx_audits_ticket_id',
                        unique: false,
                        fieldIds: ['wdsh73xzbbsi54pab7xtad191'],
                        createdAt: now,
                    },
                    {
                        id: 'aouy1pcwynjmzkiijmwxgfwcx',
                        name: 'ticketit_audits_pkey',
                        unique: true,
                        fieldIds: ['k6iv8ifwf2x5copb6v8r6v7iu'],
                        createdAt: now,
                    },
                    {
                        id: 'iytlkj7j9c44qe71eomf263cc',
                        name: 'idx_audits_user_id',
                        unique: false,
                        fieldIds: ['e3fgy0e6csdti4pi3ui9b3fks'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5un8j89oxdps0ebr548leu56w',
                name: 'ticketit_priorities',
                schema: 'public',
                x: -441.64470444215664,
                y: -86.96583963022732,
                fields: [
                    {
                        id: 'te5uirox6vofoa0sh0os7pj7w',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wzde4of9xw0zc8b5s5hrxmn7u',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gl25ihfx8w110dubt7uk9zavd',
                        name: 'color',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'emgey8kgmotqa060nboby919r',
                        name: 'ticketit_priorities_pkey',
                        unique: true,
                        fieldIds: ['te5uirox6vofoa0sh0os7pj7w'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '78j4wvik02wgfbo1fhywgmqup',
                name: 'users',
                schema: 'public',
                x: 557.8286933236934,
                y: 93.61361330148964,
                fields: [
                    {
                        id: 'dj5tenp91tk5hoy9v6ep9b6wf',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '1o5v5fdvf5wbv7sqkw88smr7c',
                        name: 'ticketit_admin',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dikevzslifq2bcg2wdnteub5h',
                        name: 'ticketit_agent',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'uts874utol8x6c6wxup852yfn',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['dj5tenp91tk5hoy9v6ep9b6wf'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '8960j1v0o5biqetave5q78wen',
                name: 'ticketit_categories_users',
                schema: 'public',
                x: 198.46675932052426,
                y: 385.69971265370896,
                fields: [
                    {
                        id: 'gbnvz6152pjkz8onibjiao4x6',
                        name: 'category_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wqryw39tfrm83cmzhl6h8j8fm',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'cq97ggzg1x0l7v438g1adv6p9',
                        name: 'ticketit_categories_users_pkey',
                        unique: true,
                        fieldIds: [
                            'gbnvz6152pjkz8onibjiao4x6',
                            'wqryw39tfrm83cmzhl6h8j8fm',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '6bsr7vxw3qad6xhmrkuj6q3a2',
                        name: 'idx_category_user_category_id',
                        unique: false,
                        fieldIds: ['gbnvz6152pjkz8onibjiao4x6'],
                        createdAt: now,
                    },
                    {
                        id: '9ryb22txfq77u7whriagapcv8',
                        name: 'idx_category_user_user_id',
                        unique: false,
                        fieldIds: ['wqryw39tfrm83cmzhl6h8j8fm'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '99j0hy58vmx1pontrz2vkl03s',
                name: 'ticketit_categories',
                schema: 'public',
                x: -176.09211887404683,
                y: 338.4987188242834,
                fields: [
                    {
                        id: 'vleh1ly31xenjjoz211fe34bn',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7ovg771u4wfvqc9hkpwyca3gl',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd4p2q78a4cdrraotl00056nph',
                        name: 'color',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'wimy3cygg4z0tm46x9b3i2qu6',
                        name: 'ticketit_categories_pkey',
                        unique: true,
                        fieldIds: ['vleh1ly31xenjjoz211fe34bn'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '9w9yqderz2181v35mkasdcrbj',
                name: 'ticketit_settings',
                schema: 'public',
                x: -443.4489253835209,
                y: 114.88308716283586,
                fields: [
                    {
                        id: 'k8gw7x7dxtv51g1vlis0u7x50',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5tk8nu3gzdstxi68txr1q2bo9',
                        name: 'lang',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'irvsej0q4dcq0aziggwfsa95r',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'o75wo7213v3wo05rvkh83rwhh',
                        name: 'value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'szbze5jp6i328qubvhcdfapxd',
                        name: 'default',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g0xxd2jknv366nir4ju4h1ouz',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jiv95mthj5zk2v1pwl5wa6u1y',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qunmnc7gg271bkxqq4m67bybd',
                        name: 'ticketit_settings_slug_key',
                        unique: true,
                        fieldIds: ['irvsej0q4dcq0aziggwfsa95r'],
                        createdAt: now,
                    },
                    {
                        id: 'pa4q5imgwcko0b4mc9hvs299z',
                        name: 'ticketit_settings_pkey',
                        unique: true,
                        fieldIds: ['k8gw7x7dxtv51g1vlis0u7x50'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'kwgr7cd982jkc0tedwthl2jtw',
                name: 'ticketit',
                schema: 'public',
                x: 72.06132962717925,
                y: -261.2829233988243,
                fields: [
                    {
                        id: 'iidzujagfol5hdkmunkzm0tdr',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wkjdtpkj99z40yjcdbt5om8dm',
                        name: 'subject',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8dqvvm3cxx6cgd5qgxibmtkkl',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nmcsf6bwla347c6cbln44xkn4',
                        name: 'html',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'czwwgho0ohzmabq6br2upb89m',
                        name: 'status_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'f0s75wjpcfp6tz8uddxdjolbq',
                        name: 'priority_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cj0v1qyoxkhowpvkr2rkpd4t9',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '854yp8e8x13v1yzoanpn4takh',
                        name: 'agent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gzwfz4656zvpzxezqjv4pzc9y',
                        name: 'category_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ujb9zbi9hmtwxyos5a04xmyp9',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mzdtu9lp5vum568aezjwpgyvm',
                        name: 'updated_at',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'o7ataxliaqchc4icwiakd80mb',
                        name: 'completed_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'mx3g7n6agvry6vq8hj8ggsuae',
                        name: 'idx_ticketit_category_id',
                        unique: false,
                        fieldIds: ['gzwfz4656zvpzxezqjv4pzc9y'],
                        createdAt: now,
                    },
                    {
                        id: '1iv89uankqx5ip7nj0potqyhv',
                        name: 'ticketit_pkey',
                        unique: true,
                        fieldIds: ['iidzujagfol5hdkmunkzm0tdr'],
                        createdAt: now,
                    },
                    {
                        id: 'lw4w383csto8q5h023fhzloro',
                        name: 'idx_ticketit_status_id',
                        unique: false,
                        fieldIds: ['czwwgho0ohzmabq6br2upb89m'],
                        createdAt: now,
                    },
                    {
                        id: 'vttkmp14b0mivsl657tbp7cqn',
                        name: 'idx_ticketit_agent_id',
                        unique: false,
                        fieldIds: ['854yp8e8x13v1yzoanpn4takh'],
                        createdAt: now,
                    },
                    {
                        id: 'bs4vr3arjn4nfbpuwd4easpyn',
                        name: 'idx_ticketit_user_id',
                        unique: false,
                        fieldIds: ['cj0v1qyoxkhowpvkr2rkpd4t9'],
                        createdAt: now,
                    },
                    {
                        id: 'ekh8xcx11tkbrm87mc1b7wdg0',
                        name: 'idx_ticketit_priority_id',
                        unique: false,
                        fieldIds: ['f0s75wjpcfp6tz8uddxdjolbq'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'thzy8ttwg16hac00om8t8ap50',
                name: 'ticketit_statuses',
                schema: 'public',
                x: -439.75527617670537,
                y: -273.3622313458803,
                fields: [
                    {
                        id: 'hudebn1pmnvhfxi985ip4y35n',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '65o2wmaptzm5nttx8ienn1fre',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'iwrnauzmac1bv5hic09fra1tf',
                        name: 'color',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '1abux79utc1s8xr8zr54tix1m',
                        name: 'ticketit_statuses_pkey',
                        unique: true,
                        fieldIds: ['hudebn1pmnvhfxi985ip4y35n'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'tk4jypnatvj407xp4low182gm',
                name: 'ticketit_comments',
                schema: 'public',
                x: 348.5519666446112,
                y: -629.765788528322,
                fields: [
                    {
                        id: '12atn0726m9zj4lvtxwno8l3t',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'prues5pt55l57mzowte9h683q',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zmzss3b27188540sykvo1q0li',
                        name: 'user_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kmnt802a8ih7i0epe1ae1es0u',
                        name: 'ticket_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xw3o5bheynyk9ji06yylto4jq',
                        name: 'created_at',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ijojcws4nt74zz3eittmwv44s',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'txvaoxxxlwvmgjnzrv2egvzol',
                        name: 'html',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'wd3jmex9o3ekhwnzi70h82quo',
                        name: 'idx_comments_user_id',
                        unique: false,
                        fieldIds: ['zmzss3b27188540sykvo1q0li'],
                        createdAt: now,
                    },
                    {
                        id: 'q3vownf8y3w3d2txrlbdb7hlg',
                        name: 'idx_comments_ticket_id',
                        unique: false,
                        fieldIds: ['kmnt802a8ih7i0epe1ae1es0u'],
                        createdAt: now,
                    },
                    {
                        id: '5tgk184b3a5h93iyqpuolsdpu',
                        name: 'ticketit_comments_pkey',
                        unique: true,
                        fieldIds: ['12atn0726m9zj4lvtxwno8l3t'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '1ardagykt69o4vl2w2s7njhlr',
                name: 'ticketit_audits_ticket_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3j13z4t0omj0m67obfela7uva',
                targetTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                sourceFieldId: 'wdsh73xzbbsi54pab7xtad191',
                targetFieldId: 'iidzujagfol5hdkmunkzm0tdr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '1tv2sebrsag1zad95fbkjmkf1',
                name: 'ticketit_comments_user_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tk4jypnatvj407xp4low182gm',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'zmzss3b27188540sykvo1q0li',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '91agbnk35l3v0ncju9ltcordl',
                name: 'ticketit_status_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: 'thzy8ttwg16hac00om8t8ap50',
                sourceFieldId: 'czwwgho0ohzmabq6br2upb89m',
                targetFieldId: 'hudebn1pmnvhfxi985ip4y35n',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'd2ecw1m439dwtlpciliis2g82',
                name: 'ticketit_categories_users_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8960j1v0o5biqetave5q78wen',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'wqryw39tfrm83cmzhl6h8j8fm',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'dwdxu3m1q56lpf2j55uk4me9g',
                name: 'ticketit_agent_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: '854yp8e8x13v1yzoanpn4takh',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fe1sw7t5dbcuy66jwzw5dipsj',
                name: 'ticketit_audits_user_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3j13z4t0omj0m67obfela7uva',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'e3fgy0e6csdti4pi3ui9b3fks',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'h2b7oip9v7rfnb5nkeejsnqzv',
                name: 'ticketit_user_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'cj0v1qyoxkhowpvkr2rkpd4t9',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'jbvrua3879cmjt9r44bjqi5vf',
                name: 'ticketit_comments_ticket_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tk4jypnatvj407xp4low182gm',
                targetTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                sourceFieldId: 'kmnt802a8ih7i0epe1ae1es0u',
                targetFieldId: 'iidzujagfol5hdkmunkzm0tdr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'jpkr91h4waoej055pk1mw9dno',
                name: 'ticketit_audits_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3j13z4t0omj0m67obfela7uva',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'e3fgy0e6csdti4pi3ui9b3fks',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'nkcqu2n9gu0v6yo58ehrymhh0',
                name: 'ticketit_comments_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tk4jypnatvj407xp4low182gm',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'zmzss3b27188540sykvo1q0li',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'o9axvh1pktujlzc75uaxa795q',
                name: 'ticketit_status_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: 'thzy8ttwg16hac00om8t8ap50',
                sourceFieldId: 'czwwgho0ohzmabq6br2upb89m',
                targetFieldId: 'hudebn1pmnvhfxi985ip4y35n',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'pm2zyhrdqt5gtf7e8snraau65',
                name: 'ticketit_comments_ticket_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tk4jypnatvj407xp4low182gm',
                targetTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                sourceFieldId: 'kmnt802a8ih7i0epe1ae1es0u',
                targetFieldId: 'iidzujagfol5hdkmunkzm0tdr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tyuwqfxp1c66horkabun3hrow',
                name: 'ticketit_priority_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '5un8j89oxdps0ebr548leu56w',
                sourceFieldId: 'f0s75wjpcfp6tz8uddxdjolbq',
                targetFieldId: 'te5uirox6vofoa0sh0os7pj7w',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'uez4yimmi8tcrdxid8tf08nn0',
                name: 'ticketit_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: 'cj0v1qyoxkhowpvkr2rkpd4t9',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'v0eryjqywayuwkm45chtr8n7m',
                name: 'ticketit_priority_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '5un8j89oxdps0ebr548leu56w',
                sourceFieldId: 'f0s75wjpcfp6tz8uddxdjolbq',
                targetFieldId: 'te5uirox6vofoa0sh0os7pj7w',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'x4qqjhejn6odbz6om3l13zcxt',
                name: 'ticketit_category_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '99j0hy58vmx1pontrz2vkl03s',
                sourceFieldId: 'gzwfz4656zvpzxezqjv4pzc9y',
                targetFieldId: 'vleh1ly31xenjjoz211fe34bn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'xk0yufiya5tjf6x3vg2ayp9l1',
                name: 'ticketit_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '78j4wvik02wgfbo1fhywgmqup',
                sourceFieldId: '854yp8e8x13v1yzoanpn4takh',
                targetFieldId: 'dj5tenp91tk5hoy9v6ep9b6wf',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'xphc1c9sjd8bhbiu0pt13sw59',
                name: 'ticketit_audits_ticket_id_fkey1',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3j13z4t0omj0m67obfela7uva',
                targetTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                sourceFieldId: 'wdsh73xzbbsi54pab7xtad191',
                targetFieldId: 'iidzujagfol5hdkmunkzm0tdr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'yo75ynn0lezwwle67cy6fws7i',
                name: 'ticketit_category_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kwgr7cd982jkc0tedwthl2jtw',
                targetTableId: '99j0hy58vmx1pontrz2vkl03s',
                sourceFieldId: 'gzwfz4656zvpzxezqjv4pzc9y',
                targetFieldId: 'vleh1ly31xenjjoz211fe34bn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'z0pc9ufxugj8fuev0vkiin9qs',
                name: 'ticketit_categories_users_category_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8960j1v0o5biqetave5q78wen',
                targetTableId: '99j0hy58vmx1pontrz2vkl03s',
                sourceFieldId: 'gbnvz6152pjkz8onibjiao4x6',
                targetFieldId: 'vleh1ly31xenjjoz211fe34bn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
