import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/twitter-db.png';
import imageDark from '@/assets/templates/twitter-db-dark.png';

const now = Date.now();

export const twitterDb: Template = {
    slug: 'twitter-database',
    name: 'Twitter Database',
    shortDescription: 'Social media platform clone application',
    description:
        'Built with React - Example database schema diagram for twitter',
    image,
    imageDark,
    tags: ['Postgres', 'Example Apps'],
    url: 'https://github.com/SukhjinderArora/twitter-clone',
    featured: true,
    diagram: {
        id: 'twitter_db',
        name: 'twitter-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '8r838c9y1hc4fkcvma0cecb05',
                name: 'Like',
                schema: 'public',
                x: 215.4643003004653,
                y: -274.2299630066947,
                fields: [
                    {
                        id: 'jae5crhu5xja3mar6czqqicuy',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Like_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'fipxudoexhscqb14l0n4tcyjx',
                        name: 'postid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'twhv3410zdar1ng7i99u3kott',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'juj94hakf20jxwgvi2oe8drz6',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '00w7f7rnuvi789romrqkisoeb',
                        name: 'Like_postid_userid_key',
                        unique: true,
                        fieldIds: [
                            'fipxudoexhscqb14l0n4tcyjx',
                            'twhv3410zdar1ng7i99u3kott',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'tiblzdur5a8kssck3d5m1bluk',
                        name: 'Like_pkey',
                        unique: true,
                        fieldIds: ['jae5crhu5xja3mar6czqqicuy'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'f3ir61irh5ojw78vndtw8b79f',
                name: 'User',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'edv3mqdnxmd73dzslj88juqi6',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''User_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '5wc2nf9pfmixd7zkk8kgrt2n2',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd7ubhcy7q1fg9mx35ja6n8i9l',
                        name: 'username',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'any0s2bb0jxtq637egmpwkncb',
                        name: 'newuser',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'ccr07obnqemhszf617ophazna',
                        name: 'hashedpassword',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'taij0zfubjtv5tzs5o2bi1udh',
                        name: 'googleid',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ts5d0e1opaozhxxwuwz1jh0lv',
                        name: 'provider',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3xbeiu1hpxmjjmsqgea4k0hzw',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'e57f1ahtuld35uox92np1cqj7',
                        name: 'User_username_key',
                        unique: true,
                        fieldIds: ['d7ubhcy7q1fg9mx35ja6n8i9l'],
                        createdAt: now,
                    },
                    {
                        id: 'x5iiiavaxvwgldn798xijaqkk',
                        name: 'User_pkey',
                        unique: true,
                        fieldIds: ['edv3mqdnxmd73dzslj88juqi6'],
                        createdAt: now,
                    },
                    {
                        id: '789z9r8rpjg814szoc9lg72o0',
                        name: 'User_googleid_key',
                        unique: true,
                        fieldIds: ['taij0zfubjtv5tzs5o2bi1udh'],
                        createdAt: now,
                    },
                    {
                        id: 'onlbml2lw4z0ra9ygnxq3u4zw',
                        name: 'User_email_key',
                        unique: true,
                        fieldIds: ['5wc2nf9pfmixd7zkk8kgrt2n2'],
                        createdAt: now,
                    },
                    {
                        id: 'ren1qgnsgmm6rep3tc6j7toi6',
                        name: 'idx_user_email',
                        unique: false,
                        fieldIds: ['5wc2nf9pfmixd7zkk8kgrt2n2'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'hjer8y7ptfrnewg00996fyfhn',
                name: 'Repost',
                schema: 'public',
                x: 931.3525851499921,
                y: 112.1582284657909,
                fields: [
                    {
                        id: '98v7voi7al9v51073025d9nvo',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Repost_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'hex9fbibsfr3ow0tcfbk7betm',
                        name: 'postid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5zijm9q8aiws5hh3m5batuxe7',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hkgrjousxikrk9axcg9r9misq',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'psrmldly681302c2gomswq46z',
                        name: 'Repost_postid_userid_key',
                        unique: true,
                        fieldIds: [
                            'hex9fbibsfr3ow0tcfbk7betm',
                            '5zijm9q8aiws5hh3m5batuxe7',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'c6wv89j1un8jelf2ryt40cxba',
                        name: 'Repost_pkey',
                        unique: true,
                        fieldIds: ['98v7voi7al9v51073025d9nvo'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'iirurhm7fyd17x560haevq3z7',
                name: 'Message',
                schema: 'public',
                x: 143.17436008224922,
                y: 574.004438816938,
                fields: [
                    {
                        id: 'jt9diiumnav14qm6tttqhsatu',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Message_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'eb73ebfdgo1zgb0qo3rbvv2cv',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ddtfddxbxm5de8ossyvjay2wj',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3k6et6h3p77o8xurfxexonn4g',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'cx91z6ddp3q8c68trs6xr46ix',
                        name: 'read',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'false',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'u4alcd8pela93bn9e5su51egq',
                        name: 'idx_message_userid',
                        unique: false,
                        fieldIds: ['eb73ebfdgo1zgb0qo3rbvv2cv'],
                        createdAt: now,
                    },
                    {
                        id: 'obqzdiu0dent56boie9pver77',
                        name: 'Message_pkey',
                        unique: true,
                        fieldIds: ['jt9diiumnav14qm6tttqhsatu'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'kdulwzc8u47und8xiq72uazoy',
                name: 'Profile',
                schema: 'public',
                x: -492.3396916273415,
                y: 146.5446167956863,
                fields: [
                    {
                        id: 'la09618z5lkc8xebbzhanaqs1',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Profile_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '8b108h5gp8rnvfsj0rq4bg8t0',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5nr0a9vmwwbszd1amx3beokqj',
                        name: 'bio',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xd0b5duywzzi9gikirfa1sbmi',
                        name: 'img',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7tn9xp7mt7yj1ucp2mysrzwcm',
                        name: 'website',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ixlimpuctzxxbyjbuxvqpvhw0',
                        name: 'dob',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 're7rw32e2je7o56flj57ok4mg',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'kw45i9vtnba3x0o8nat5ih8uz',
                        name: 'Profile_pkey',
                        unique: true,
                        fieldIds: ['la09618z5lkc8xebbzhanaqs1'],
                        createdAt: now,
                    },
                    {
                        id: 'tm1kytur62t64sb8vcrqwt8kb',
                        name: 'Profile_userid_key',
                        unique: true,
                        fieldIds: ['re7rw32e2je7o56flj57ok4mg'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rbt6dtrelt775wjvfc0a59rg4',
                name: 'Post',
                schema: 'public',
                x: 699.5760154509387,
                y: -205.88919444693533,
                fields: [
                    {
                        id: 'an2tmb382pjncp4wubxbij9wm',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Post_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'lklsot6i7yc9tll98zddcs97c',
                        name: 'content',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'poma7xnfr1dmmyrsies1a23rw',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2cv1vo8g4hn00swgr4t6pm9ub',
                        name: 'parentpostid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rknox7nc3jc0ccnbdquv6nxj5',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ji1erflh8l0rc36z8jful1z5t',
                        name: 'idx_post_userid',
                        unique: false,
                        fieldIds: ['poma7xnfr1dmmyrsies1a23rw'],
                        createdAt: now,
                    },
                    {
                        id: 'a76d9komiftihg91rqhljumwh',
                        name: 'Post_pkey',
                        unique: true,
                        fieldIds: ['an2tmb382pjncp4wubxbij9wm'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ufdx9uy8byh4xxl3chqjqkyua',
                name: 'Chat',
                schema: 'public',
                x: 539.4273664767843,
                y: 402.2764763220126,
                fields: [
                    {
                        id: 'bbhp35md0uebcvcrtmlg2dzfi',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Chat_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '3wv67cinqb5x6j4ktvkdewdwq',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5groprr6mhc4vj37i9039b9mr',
                        name: 'participantid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'vt82kcj0ad51slnkomxewmm44',
                        name: 'Chat_userid_participantid_key',
                        unique: true,
                        fieldIds: [
                            '3wv67cinqb5x6j4ktvkdewdwq',
                            '5groprr6mhc4vj37i9039b9mr',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'xoe36361m8dg0o2z4ljvvjy7i',
                        name: 'Chat_pkey',
                        unique: true,
                        fieldIds: ['bbhp35md0uebcvcrtmlg2dzfi'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vunmmeczg0dkk5ix251ynnfbb',
                name: 'Notification',
                schema: 'public',
                x: -374.2894474789282,
                y: 502.3971819506827,
                fields: [
                    {
                        id: '77zuv2mcpq421it13s7cyuwgq',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Notification_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: 'o9j9tr8xaax2tuqz4vycjlnv2',
                        name: 'senderid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'd3e7y7tqb4fbgll7zda49mx32',
                        name: 'recipientid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hw6mbi69435z9ezsv2r4p0h80',
                        name: 'type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '51x9olwd6jkuiv8nmtcntr5f8',
                        name: 'objecttype',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hpvbn8zn19ns3u9zz2k2y5uj8',
                        name: 'objecturi',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'h97w8n5biact9xxw2fldu0nse',
                        name: 'read',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'ce26sjaridgdl3xztfqd9ln7m',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tjm89iw1xm5v0qacmbaftlhzz',
                        name: 'idx_notification_recipientid',
                        unique: false,
                        fieldIds: ['d3e7y7tqb4fbgll7zda49mx32'],
                        createdAt: now,
                    },
                    {
                        id: '9dg1huvld3kwkdvgp5urvys3s',
                        name: 'Notification_pkey',
                        unique: true,
                        fieldIds: ['77zuv2mcpq421it13s7cyuwgq'],
                        createdAt: now,
                    },
                    {
                        id: '4e00qrcr85hzo2uzeqqccxp8d',
                        name: 'idx_notification_senderid',
                        unique: false,
                        fieldIds: ['o9j9tr8xaax2tuqz4vycjlnv2'],
                        createdAt: now,
                    },
                ],
                color: '#42e0c0',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wuzpuxvp14j26nr849oreti3b',
                name: 'Session',
                schema: 'public',
                x: -488.00908267032764,
                y: -283.1421060187986,
                fields: [
                    {
                        id: '2f1h9duzadbj7jj6cmw0g7ibd',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: "nextval(''Session_id_seq''::regclass)",
                        createdAt: now,
                    },
                    {
                        id: '0e1ixz9dgeb3n5d4vm88fpzvh',
                        name: 'refreshtoken',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0zmpz1kbu81r5m59ny4kmz9tc',
                        name: 'expirationtime',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kx8jya4j7dfbm2b3vyfkq2a1h',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'amfhr25hoxtjac07v8tizbgy7',
                        name: 'createdat',
                        type: {
                            id: 'timestamp_with_time_zone',
                            name: 'timestamp with time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4rmxi71tbl7yrili92ea7dzqe',
                        name: 'Session_refreshtoken_key',
                        unique: true,
                        fieldIds: ['0e1ixz9dgeb3n5d4vm88fpzvh'],
                        createdAt: now,
                    },
                    {
                        id: 'ams0bc0y9s1qid7bxb3m3bfgi',
                        name: 'Session_pkey',
                        unique: true,
                        fieldIds: ['2f1h9duzadbj7jj6cmw0g7ibd'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zrdsnpx9zk8d50xx8k39dnra9',
                name: 'UserFollows',
                schema: 'public',
                x: -121.02792878761841,
                y: -335.64119299067147,
                fields: [
                    {
                        id: 'f7ev9zvz0jbjq37uw70zt4bsh',
                        name: 'userid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kf50n5zzvcwu5z8y1ftdqovzg',
                        name: 'followerid',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '3ebw0y7u3t0912otkmf30t7es',
                        name: 'UserFollows_pkey',
                        unique: true,
                        fieldIds: [
                            'f7ev9zvz0jbjq37uw70zt4bsh',
                            'kf50n5zzvcwu5z8y1ftdqovzg',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '2mfs9cyhxcvw48qgopecwyrkg',
                name: 'Post_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'poma7xnfr1dmmyrsies1a23rw',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2uy6uqg3jui570v503xfi3inq',
                name: 'Chat_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ufdx9uy8byh4xxl3chqjqkyua',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: '3wv67cinqb5x6j4ktvkdewdwq',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '4y64qyi7m40x1kz8ywgfz108r',
                name: 'Profile_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'kdulwzc8u47und8xiq72uazoy',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 're7rw32e2je7o56flj57ok4mg',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'one',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5b61u8wm2ullvbk49g8s04rvb',
                name: 'Like_postid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8r838c9y1hc4fkcvma0cecb05',
                targetTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                sourceFieldId: 'fipxudoexhscqb14l0n4tcyjx',
                targetFieldId: 'an2tmb382pjncp4wubxbij9wm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'al8mk741va3hgqbfl6uie53si',
                name: 'Post_parentpostid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                targetTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                sourceFieldId: '2cv1vo8g4hn00swgr4t6pm9ub',
                targetFieldId: 'an2tmb382pjncp4wubxbij9wm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'aldfes1y0abu386exvjdj4z4d',
                name: 'fk_post_replies',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                targetTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                sourceFieldId: '2cv1vo8g4hn00swgr4t6pm9ub',
                targetFieldId: 'an2tmb382pjncp4wubxbij9wm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'b030u5ok6ig22s3g2qdvabngv',
                name: 'Notification_senderid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vunmmeczg0dkk5ix251ynnfbb',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'o9j9tr8xaax2tuqz4vycjlnv2',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'gry1byfovn8jxd98ljzk8v3km',
                name: 'Like_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8r838c9y1hc4fkcvma0cecb05',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'twhv3410zdar1ng7i99u3kott',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'i58mq8fba46gzcb3fj5hr2k3k',
                name: 'Session_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'wuzpuxvp14j26nr849oreti3b',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'kx8jya4j7dfbm2b3vyfkq2a1h',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'j7t2pgkerxk7nula18sb824rm',
                name: 'Notification_recipientid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vunmmeczg0dkk5ix251ynnfbb',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'd3e7y7tqb4fbgll7zda49mx32',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ka5jwq5bkhzrqni93q14idgh7',
                name: 'Repost_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hjer8y7ptfrnewg00996fyfhn',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: '5zijm9q8aiws5hh3m5batuxe7',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'kxlw0u5a1um3kfknyucw3osp8',
                name: 'Message_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'iirurhm7fyd17x560haevq3z7',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'eb73ebfdgo1zgb0qo3rbvv2cv',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'lj54y21e3vb874g91sy09ih1v',
                name: 'Chat_participantid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ufdx9uy8byh4xxl3chqjqkyua',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: '5groprr6mhc4vj37i9039b9mr',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tocur798csmml6on4usc9fs3c',
                name: 'Repost_postid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'hjer8y7ptfrnewg00996fyfhn',
                targetTableId: 'rbt6dtrelt775wjvfc0a59rg4',
                sourceFieldId: 'hex9fbibsfr3ow0tcfbk7betm',
                targetFieldId: 'an2tmb382pjncp4wubxbij9wm',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tr3le7ar9ui0zfba6ptrdx3r7',
                name: 'UserFollows_userid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'zrdsnpx9zk8d50xx8k39dnra9',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'f7ev9zvz0jbjq37uw70zt4bsh',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'xmoimjsyg58livkhol8v17vyz',
                name: 'UserFollows_followerid_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'zrdsnpx9zk8d50xx8k39dnra9',
                targetTableId: 'f3ir61irh5ojw78vndtw8b79f',
                sourceFieldId: 'kf50n5zzvcwu5z8y1ftdqovzg',
                targetFieldId: 'edv3mqdnxmd73dzslj88juqi6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
