import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/voyager-db.png';
import imageDark from '@/assets/templates/voyager-db-dark.png';

const now = Date.now();

export const voyagerDb: Template = {
    slug: 'voyager-database',
    name: 'Voyager',
    shortDescription: 'The Missing Admin for Laravel',
    description:
        'Package with Media Manager, Menu Builder, Database Manager, and CRUD tools.',
    image,
    imageDark,
    tags: ['Postgres', 'Open Source', 'Laravel', 'PHP'],
    featured: false,
    url: 'https://voyager.devdojo.com',
    diagram: {
        id: 'voyager_db',
        name: 'voyager-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '1jirb68g3aetzfsc1tftibg0x',
                name: 'permission_role',
                schema: 'public',
                x: 372.6284949966332,
                y: 320.29759509217644,
                fields: [
                    {
                        id: 'tlq836h9hxivb3yq5i77j69ef',
                        name: 'permission_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gp7pd9oxz8h28u5w79w08t7n6',
                        name: 'role_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'nt0gr8kyoq8aohuopvah60nrf',
                        name: 'idx_permission_role_permission_id_role_id',
                        unique: false,
                        fieldIds: [
                            'tlq836h9hxivb3yq5i77j69ef',
                            'gp7pd9oxz8h28u5w79w08t7n6',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'iqlz39u8dwkvohbi5u1eerx0c',
                        name: 'permission_role_pkey',
                        unique: true,
                        fieldIds: [
                            'tlq836h9hxivb3yq5i77j69ef',
                            'gp7pd9oxz8h28u5w79w08t7n6',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '2sif2077lvh8lr2uo77yzyeii',
                name: 'user_roles',
                schema: 'public',
                x: -196.45238933968017,
                y: -25.565099801681185,
                fields: [
                    {
                        id: 'thwx0iva7h3hgem71p6vtqyn6',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '866cjoij6khkeii69jirrj2sr',
                        name: 'role_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xzugsu33k6ww08qc9j5xo8yyf',
                        name: 'user_roles_pkey',
                        unique: true,
                        fieldIds: [
                            'thwx0iva7h3hgem71p6vtqyn6',
                            '866cjoij6khkeii69jirrj2sr',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'ittdv0rieqz7k1rrf3twv9ldr',
                        name: 'idx_user_roles_user_id_role_id',
                        unique: false,
                        fieldIds: [
                            'thwx0iva7h3hgem71p6vtqyn6',
                            '866cjoij6khkeii69jirrj2sr',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '3pw4sdxkql90vi5u7mvdoktob',
                name: 'menus',
                schema: 'public',
                x: 784.4277578291758,
                y: -79.80900828848576,
                fields: [
                    {
                        id: 'c0bczfmzqu9k4cpzgov0lng6f',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '224bjovak9514xxq5pbrbprzk',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ozex0ne1zzrlbawqfh21c8hvw',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wu5zwyquywdd67kc7r6flj32s',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '0w2gngeuqwswy925hqj3p2yt4',
                        name: 'menus_pkey',
                        unique: true,
                        fieldIds: ['c0bczfmzqu9k4cpzgov0lng6f'],
                        createdAt: now,
                    },
                    {
                        id: 'zm97cevce5l5rwxgwnmeicsry',
                        name: 'idx_menus_name',
                        unique: true,
                        fieldIds: ['224bjovak9514xxq5pbrbprzk'],
                        createdAt: now,
                    },
                    {
                        id: 'p3dvnqarvjfylo8nq2qiqm0zh',
                        name: 'menus_name_key',
                        unique: true,
                        fieldIds: ['224bjovak9514xxq5pbrbprzk'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '9xny68y3a4omranwgmxtjvgwa',
                name: 'settings',
                schema: 'public',
                x: 785.0437394633484,
                y: 174.4041932907814,
                fields: [
                    {
                        id: 'xuwdfm8rye2fbzvoqqtc5icd2',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'n4o1y6fpnwd61oig4ixth9p93',
                        name: 'key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yth3oftq6c6uqias880kvr496',
                        name: 'display_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'a7e1cdjgp9bmhuig2pgg6wrpi',
                        name: 'value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'eessnq8jusbhibk5odbgzbtqx',
                        name: 'details',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '46uwt65a5w0gqvln2keeb7kot',
                        name: 'type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xm8189qeooq2zz4df73919p4s',
                        name: 'order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ontam4xkza1l1yyqiz294igi8',
                        name: 'group',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'kmc6tjfe7lyuksqtkyx3076ge',
                        name: 'settings_key_key',
                        unique: true,
                        fieldIds: ['n4o1y6fpnwd61oig4ixth9p93'],
                        createdAt: now,
                    },
                    {
                        id: 'ev2om5dzgux2sypq8xsmb30yo',
                        name: 'idx_settings_key',
                        unique: true,
                        fieldIds: ['n4o1y6fpnwd61oig4ixth9p93'],
                        createdAt: now,
                    },
                    {
                        id: 'p1tbuvqjvm2xw8vmn8sxmbqaj',
                        name: 'settings_pkey',
                        unique: true,
                        fieldIds: ['xuwdfm8rye2fbzvoqqtc5icd2'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'bq1341mwagcb890tf14p7wino',
                name: 'permissions',
                schema: 'public',
                x: 713.6945379646128,
                y: 518.8173010797083,
                fields: [
                    {
                        id: 'l3l81z01opxlx1vrbw66n3ukr',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sh3cmr6v9jaz2pm7ukpcx4iak',
                        name: 'key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '27aojfkpy6wd9pllbea7ewwzh',
                        name: 'table_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'shelnoaw576hdtn861tq1nqv7',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5aecap6tom0131r1szyzmv9hn',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '57gf31lave2vorj073ipn7yit',
                        name: 'permissions_pkey',
                        unique: true,
                        fieldIds: ['l3l81z01opxlx1vrbw66n3ukr'],
                        createdAt: now,
                    },
                    {
                        id: '93wmh6h1aopfjocf2s8kkl9iq',
                        name: 'idx_permissions_key',
                        unique: false,
                        fieldIds: ['sh3cmr6v9jaz2pm7ukpcx4iak'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c62p7n83ompn9ymxdh0ut37mi',
                name: 'menu_items',
                schema: 'public',
                x: 497.69541925038357,
                y: -235.9702338899092,
                fields: [
                    {
                        id: 'x1gzyzjvmrlw2gmh558h6hxhm',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gsglpwpcyevzl3vcnvmcho8jc',
                        name: 'menu_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lb4uh4418dlcpd3on7dmbj3zj',
                        name: 'title',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lzc548ndcxf7n3act5pah4jon',
                        name: 'url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g7yzle7d88x8kqgi5f2nivx22',
                        name: 'target',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'p7i8qw0spw5ggpymcxb3etwt3',
                        name: 'icon_class',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'iw1kjqplhig3th5dv72qmorq7',
                        name: 'color',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'luyjxkkpfj1eb8nrc5ieo50x9',
                        name: 'parent_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'eavsijaizz5hm2akhzsy4xoh9',
                        name: 'order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's4p8359a244olmbv8dmqrn9xr',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kvot7ci3cqgo7qwz3g859l5ji',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pvz42trdbrei5537gd27z6psu',
                        name: 'route',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cbss6t90171xuo2xfh49ddvm9',
                        name: 'parameters',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'cln5s3hlbfze2hrm1fwi6y6xb',
                        name: 'idx_menu_items_menu_id',
                        unique: false,
                        fieldIds: ['gsglpwpcyevzl3vcnvmcho8jc'],
                        createdAt: now,
                    },
                    {
                        id: 'ae7emzghpk7whst5w3jktff1j',
                        name: 'menu_items_pkey',
                        unique: true,
                        fieldIds: ['x1gzyzjvmrlw2gmh558h6hxhm'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'exu5d731v8jmor74nasx6dpni',
                name: 'data_types',
                schema: 'public',
                x: 90.2956251067003,
                y: 419.5156182409287,
                fields: [
                    {
                        id: 'zr3susjaamb56ay6low3eka93',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'by4c86d10zgqguez74gzo7sw3',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '675we344y0vxmhpyomzndcox7',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0w91b60zwg1kk9kj5mjgvwagi',
                        name: 'display_name_singular',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '15soydn7izssn6ho1v5hkip4z',
                        name: 'display_name_plural',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0y0or7u890xjylqug0tb9m1nh',
                        name: 'icon',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6eo7rpaen63me6mezohfqvvxn',
                        name: 'model_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uhou516pdoed62obfxsdhg3bv',
                        name: 'policy_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ne3gx0mfm00rk48e3629ek3yc',
                        name: 'controller',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i99cywl60whlvo0zsac2dczbk',
                        name: 'description',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7nwqa6hh2rq29c6h7zvh2ul88',
                        name: 'generate_permission',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'bcmcus1ljz3grp4jnro9ffh59',
                        name: 'server_side',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'toamksw0ekr1wl4vd1cmgcjet',
                        name: 'details',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qaz8jxcd5t5n9otfal6a48328',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ruj36cnwovme0eojyb6m05xkc',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rpt5p1taoqfxxn4000p63lpj8',
                        name: 'data_types_slug_key',
                        unique: true,
                        fieldIds: ['675we344y0vxmhpyomzndcox7'],
                        createdAt: now,
                    },
                    {
                        id: '04s4lxz2n2y2np8w6stafylja',
                        name: 'idx_data_types_name',
                        unique: true,
                        fieldIds: ['by4c86d10zgqguez74gzo7sw3'],
                        createdAt: now,
                    },
                    {
                        id: '2y0i81gkfwbneouaxp48c57iv',
                        name: 'data_types_name_key',
                        unique: true,
                        fieldIds: ['by4c86d10zgqguez74gzo7sw3'],
                        createdAt: now,
                    },
                    {
                        id: 's5p0ftwy3g3dvxnq6w18p8l22',
                        name: 'idx_data_types_slug',
                        unique: true,
                        fieldIds: ['675we344y0vxmhpyomzndcox7'],
                        createdAt: now,
                    },
                    {
                        id: 'a0a4b5gyqdop9c3cuyi1eplot',
                        name: 'data_types_pkey',
                        unique: true,
                        fieldIds: ['zr3susjaamb56ay6low3eka93'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'fbbao0vu5gn930dgjq5ebiz41',
                name: 'users',
                schema: 'public',
                x: 182.55909943131076,
                y: -142.16126390324226,
                fields: [
                    {
                        id: 'ly4plfmzl9fwrjo252de2uc7k',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'l061cbgzdgi0iavknokc2uann',
                        name: 'avatar',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mnhar9293jk7irk8x8xsdh7ly',
                        name: 'role_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'h0q07lo2qychbcnn5c046v6ni',
                        name: 'settings',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rh4sgk03nq5aq59ivetp7f8eh',
                        name: 'idx_users_role_id',
                        unique: false,
                        fieldIds: ['mnhar9293jk7irk8x8xsdh7ly'],
                        createdAt: now,
                    },
                    {
                        id: 'l902fmigs8760r4rydgzroevt',
                        name: 'users_pkey',
                        unique: true,
                        fieldIds: ['ly4plfmzl9fwrjo252de2uc7k'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'nxflaeej0mdn9tze4pl8iy8ko',
                name: 'data_rows',
                schema: 'public',
                x: -247.86521714388346,
                y: 230.91957887470818,
                fields: [
                    {
                        id: 'kj9r7d07e1ze1f8dlqmjdnfv6',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kapwgrqerutf97j15kvjaxl8v',
                        name: 'data_type_id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '72t3tligr6g6mwl8zajuzqn3p',
                        name: 'field',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qqrnhig6qaepbfgd90pgm6vcy',
                        name: 'type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9p5r337v6p7bgf89g8pep807h',
                        name: 'display_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's92sgoxbr45t6mjmko05lwjh6',
                        name: 'required',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j5s2fbduf0x9p65gncbkcocop',
                        name: 'browse',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 't1cjqs9dgahgbqjzftgeoot89',
                        name: 'read',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5eipgftbxz4bbau60u1pt9n06',
                        name: 'edit',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xr4k425k4jh8cto6as1qnkfks',
                        name: 'add',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'uewbtb15t3yuy0lbp3umm1lym',
                        name: 'delete',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qru8xx86q7b26nchrka4rvg0u',
                        name: 'details',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'e6g49vjqwagbitpf0by0pdbel',
                        name: 'order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'd10yi680bhq2uk3961b916q41',
                        name: 'idx_data_rows_data_type_id',
                        unique: false,
                        fieldIds: ['kapwgrqerutf97j15kvjaxl8v'],
                        createdAt: now,
                    },
                    {
                        id: 'wgkld0i1vjfdl2rh3399epjww',
                        name: 'data_rows_pkey',
                        unique: true,
                        fieldIds: ['kj9r7d07e1ze1f8dlqmjdnfv6'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vazin4dvcl07gkgurawm4xnc5',
                name: 'roles',
                schema: 'public',
                x: 65.52545516961561,
                y: 160.83743205361958,
                fields: [
                    {
                        id: 'xku5gyx3lkv1u9vlbd3ci7u67',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wt7kxvcosdruydjnj16r8628p',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'iqghlf4c3prpxxf8tpw64xxfe',
                        name: 'display_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0awmbio5zo3ud4lxvyrqld11m',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'r64ukxh7bq47lm9ob5m6aslr5',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qy6mrnixtjxcr107de53m23f6',
                        name: 'roles_pkey',
                        unique: true,
                        fieldIds: ['xku5gyx3lkv1u9vlbd3ci7u67'],
                        createdAt: now,
                    },
                ],
                color: '#8a61f5',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vwu5ku8a490dysv9v1vsy12cy',
                name: 'translations',
                schema: 'public',
                x: 1046.6697805455976,
                y: 172.46066130794293,
                fields: [
                    {
                        id: 'o0zxq6p741sgcpdrzws5c35vy',
                        name: 'id',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ilxltnf8rq7ro3iw4j19u4bso',
                        name: 'table_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bjl0pqfhofuwejs156yy462xw',
                        name: 'column_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ey68xrpdm408ov3jpidygwl4q',
                        name: 'foreign_key',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hkr9wdk18qvjbvvqe1h57u7el',
                        name: 'locale',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lma9ku3pafx70jtrc440glifv',
                        name: 'value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's3g8tia1iphxrp2iocunkwyy5',
                        name: 'created_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5gahw9ck5hdcn5wq0jx49fu8a',
                        name: 'updated_at',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'c6l5p05rwgtryfzrd6t46a1sj',
                        name: 'idx_translations_table_name_column_name',
                        unique: false,
                        fieldIds: [
                            'ilxltnf8rq7ro3iw4j19u4bso',
                            'bjl0pqfhofuwejs156yy462xw',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '6sq9dyw9cglkkseh0a1ksfnu2',
                        name: 'translations_pkey',
                        unique: true,
                        fieldIds: ['o0zxq6p741sgcpdrzws5c35vy'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '4ur68w80c0dmttu4x8mr71l5b',
                name: 'user_roles_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '2sif2077lvh8lr2uo77yzyeii',
                targetTableId: 'fbbao0vu5gn930dgjq5ebiz41',
                sourceFieldId: 'thwx0iva7h3hgem71p6vtqyn6',
                targetFieldId: 'ly4plfmzl9fwrjo252de2uc7k',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'lk6nm0cwsslxjrebylfor6auk',
                name: 'permission_role_permission_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '1jirb68g3aetzfsc1tftibg0x',
                targetTableId: 'bq1341mwagcb890tf14p7wino',
                sourceFieldId: 'tlq836h9hxivb3yq5i77j69ef',
                targetFieldId: 'l3l81z01opxlx1vrbw66n3ukr',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ml4s6i1ogu6ntqu3midcvk9ms',
                name: 'permission_role_role_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '1jirb68g3aetzfsc1tftibg0x',
                targetTableId: 'vazin4dvcl07gkgurawm4xnc5',
                sourceFieldId: 'gp7pd9oxz8h28u5w79w08t7n6',
                targetFieldId: 'xku5gyx3lkv1u9vlbd3ci7u67',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tnyqlok1z1cyi1mqun1pt4frg',
                name: 'data_rows_data_type_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'nxflaeej0mdn9tze4pl8iy8ko',
                targetTableId: 'exu5d731v8jmor74nasx6dpni',
                sourceFieldId: 'kapwgrqerutf97j15kvjaxl8v',
                targetFieldId: 'zr3susjaamb56ay6low3eka93',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vzh8yhr8hkgcox0be4f62rkeu',
                name: 'menu_items_menu_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c62p7n83ompn9ymxdh0ut37mi',
                targetTableId: '3pw4sdxkql90vi5u7mvdoktob',
                sourceFieldId: 'gsglpwpcyevzl3vcnvmcho8jc',
                targetFieldId: 'c0bczfmzqu9k4cpzgov0lng6f',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'wlyxfd9i22aff0h5kl70ghubk',
                name: 'user_roles_role_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '2sif2077lvh8lr2uo77yzyeii',
                targetTableId: 'vazin4dvcl07gkgurawm4xnc5',
                sourceFieldId: '866cjoij6khkeii69jirrj2sr',
                targetFieldId: 'xku5gyx3lkv1u9vlbd3ci7u67',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'xfnihczkwlr73a4xli7q14w7h',
                name: 'menu_items_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'c62p7n83ompn9ymxdh0ut37mi',
                targetSchema: 'public',
                targetTableId: 'c62p7n83ompn9ymxdh0ut37mi',
                sourceFieldId: 'x1gzyzjvmrlw2gmh558h6hxhm',
                targetFieldId: 'luyjxkkpfj1eb8nrc5ieo50x9',
                sourceCardinality: 'one',
                targetCardinality: 'many',
                createdAt: now,
            },
            {
                id: 'ytlc8os0kpjttaqo6wciiax4f',
                name: 'users_role_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'fbbao0vu5gn930dgjq5ebiz41',
                targetTableId: 'vazin4dvcl07gkgurawm4xnc5',
                sourceFieldId: 'mnhar9293jk7irk8x8xsdh7ly',
                targetFieldId: 'xku5gyx3lkv1u9vlbd3ci7u67',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
