import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/wordpress-db.png';
import imageDark from '@/assets/templates/wordpress-db-dark.png';

const now = Date.now();

export const wordpressDb: Template = {
    slug: 'wordpress-database',
    name: 'WordPress',
    shortDescription: 'An open-source PHP Content Management System',
    description:
        '(CMS) ideal for building websites, blogs, or apps. Flexible, customizable, and designed for developers to expand',
    image,
    imageDark,
    tags: ['MySQL', 'Open Source', 'WordPress', 'PHP'],
    featured: true,
    url: 'https://wordpress.org',
    diagram: {
        id: 'wordpress_db',
        name: 'wordpress-database',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.MYSQL,
        tables: [
            {
                id: '0ovpgck8or3x6m2xn2hmbp0c4',
                name: 'wp_links',
                schema: 'public',
                x: 794.1938021123153,
                y: 269.19595734494305,
                fields: [
                    {
                        id: '0agxjmlgdfxs2d5mqg6e4xzhk',
                        name: 'link_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9gcbrwsozyfns0idfgd6ub3yp',
                        name: 'link_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zu0irjx9matzcomj45840skd3',
                        name: 'link_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8m4t1f1mqj5p435lm55jhcp72',
                        name: 'link_image',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '90yjj43pyrf4oknjhdpmcede6',
                        name: 'link_target',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9wv0n7zwu10gad2ugrstl8eaz',
                        name: 'link_description',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3g0ijqdycpq4nc75exb71qiiw',
                        name: 'link_visible',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vdmz1ajoyc2xwznmgfoz0gx5s',
                        name: 'link_owner',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3xxffrdsv3hylkj7bp0uq2qcb',
                        name: 'link_rating',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '10gs93wwzyzy9gkkrsulw4c97',
                        name: 'link_updated',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'skavp5904rjm2mw54pz3vdwof',
                        name: 'link_rel',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'badup0ted1jq1d9rbd1pwvx1o',
                        name: 'link_notes',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5lyput0k6dh67uz5kiyfmq6nr',
                        name: 'link_rss',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'p5eqqjsiemjs0uqtq42cb97ga',
                        name: 'wp_links_pkey',
                        unique: true,
                        fieldIds: ['0agxjmlgdfxs2d5mqg6e4xzhk'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '1uahxx5482z55o3qwak1h5a44',
                name: 'wp_options',
                schema: 'public',
                x: 331.312899812928,
                y: 492.1645462827462,
                fields: [
                    {
                        id: '70ynpgmk5xjp5iguilhhjj6g1',
                        name: 'option_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'lt4q60oj4rnf3h8eururikgn4',
                        name: 'option_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6y1gm20l4nf0see3koo63lier',
                        name: 'option_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qhf8zc4y071l3ykayin4hhem0',
                        name: 'autoload',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '8kc7km5uqsvhaycknytot3xzv',
                        name: 'wp_options_pkey',
                        unique: true,
                        fieldIds: ['70ynpgmk5xjp5iguilhhjj6g1'],
                        createdAt: now,
                    },
                    {
                        id: '800weq9gculw8afj0uu0cyxx2',
                        name: 'wp_options_option_name_key',
                        unique: true,
                        fieldIds: ['lt4q60oj4rnf3h8eururikgn4'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5719hh2vceoxft07yyuw412nf',
                name: 'wp_comments',
                schema: 'public',
                x: 800.6792689151703,
                y: -465.3544133775536,
                fields: [
                    {
                        id: 'bu3m7h9vakhkun8k6nrrs18ld',
                        name: 'comment_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6opwy4tby70gcyv07zfdlwy5z',
                        name: 'comment_post_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7bgk2oy3ykao02uvbbnu74mlf',
                        name: 'comment_author',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'h0xoiiuu7ihaiz9mkfmmf0wu2',
                        name: 'comment_author_email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tmsopgd72sfhe1dy32fv2r7q3',
                        name: 'comment_author_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3qu1qj91vrd1vimyz2rursrnd',
                        name: 'comment_author_ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oazkocnck8wkhspbpsdqeyvqi',
                        name: 'comment_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pig65jbco2l2y8zwmf6otby7v',
                        name: 'comment_date_gmt',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '618xiwel3scylyeoi7opio2dj',
                        name: 'comment_content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0h5yv2ub4rhznqojxc4sauweb',
                        name: 'comment_karma',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8i3pv4bug291cqgsd3n2l9xdi',
                        name: 'comment_approved',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9qwgn1bxb2c02byxrcrol89ub',
                        name: 'comment_agent',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hdtjrcdk2v9s99v8sfirjsd6f',
                        name: 'comment_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wsx4qk1cyr62z4ed6adgxhj77',
                        name: 'comment_parent',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'bzfamxzjmb99922r0msiht80n',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qs5e3rmqwlpkk9hvj730oeody',
                        name: 'idx_wp_comments_user_id',
                        unique: false,
                        fieldIds: ['bzfamxzjmb99922r0msiht80n'],
                        createdAt: now,
                    },
                    {
                        id: 'x6kbgq3n1etid29q4r7q7llmv',
                        name: 'wp_comments_pkey',
                        unique: true,
                        fieldIds: ['bu3m7h9vakhkun8k6nrrs18ld'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '5o1x7miqtyc34fu92j2l1mre4',
                name: 'wp_site',
                schema: 'public',
                x: 1420.9850759512265,
                y: 560.9425619695904,
                fields: [
                    {
                        id: 'yob6do17uh4cr0ypj2i0fie0o',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yypk0zyhffe78lz0vgqh5g1zr',
                        name: 'domain',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'w3b8raw9fx6gubup56qzbf8iq',
                        name: 'path',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tumhmnlafppmk1qbykxsswqpu',
                        name: 'wp_site_pkey',
                        unique: true,
                        fieldIds: ['yob6do17uh4cr0ypj2i0fie0o'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6xlz7vv2yf4k4likkwbpt9n7c',
                name: 'wp_users',
                schema: 'public',
                x: 1177.3735937252402,
                y: 107.77611085766046,
                fields: [
                    {
                        id: 'hxm27ltfcn5nmpe916rghd74y',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0t4c7nsthdqvl95v50v558w3e',
                        name: 'user_login',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vp668iig5lshcqr1uanec0jcj',
                        name: 'user_pass',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'p3jdzyyjn6cwndz3353ycruyv',
                        name: 'user_nicename',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'den9kni94m7m1z8lrszj7pyx4',
                        name: 'user_email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gcde1c5kzrgzx4d8nkm7qhznf',
                        name: 'user_url',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '00em3r6d25yjb992vsg4wfftq',
                        name: 'user_registered',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6lyarfyrof6n8vmjw1jnms2ge',
                        name: 'user_activation_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2dfgxrt0oys3tgy10migbazmj',
                        name: 'user_status',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'y4zts7xz61p7eynp7rrnp0z2t',
                        name: 'display_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '83td5d6cwjq44vsioaefcr2vq',
                        name: 'wp_users_pkey',
                        unique: true,
                        fieldIds: ['hxm27ltfcn5nmpe916rghd74y'],
                        createdAt: now,
                    },
                    {
                        id: '7270l49u9x2dshb88swnhjdo5',
                        name: 'idx_wp_users_user_login',
                        unique: true,
                        fieldIds: ['0t4c7nsthdqvl95v50v558w3e'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '7ce2o0mij9li0k4g83swbhi5x',
                name: 'wp_terms',
                schema: 'public',
                x: 1933.4763464504913,
                y: 183.01699164087987,
                fields: [
                    {
                        id: 'fc9nfbmnaj04jkd8v2iv42wqk',
                        name: 'term_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '40t7da14vj9s1haz7l8kke0ed',
                        name: 'name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'summxvmemrgxmwg0svx1tdjsc',
                        name: 'slug',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hinm4tfni2cj9fritsg9t5pf2',
                        name: 'term_group',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '7uo6hxyzw6k8trv7e9moc9aah',
                        name: 'wp_terms_pkey',
                        unique: true,
                        fieldIds: ['fc9nfbmnaj04jkd8v2iv42wqk'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ew6aq96etubkyb6z3zytzf11s',
                name: 'wp_term_taxonomy',
                schema: 'public',
                x: 1854.5073791801601,
                y: -105.37976436898538,
                fields: [
                    {
                        id: '09qxmhzgvtmmjaorme35vy3u1',
                        name: 'term_taxonomy_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '21hja8tuvhtx7a4en2cdw7f9j',
                        name: 'term_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i20cjuc58u7f2e07bdmf38tgl',
                        name: 'taxonomy',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'da0w5tjgi47xh633g4jz5xwxn',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1cstdt4eevv85o10ccros1wna',
                        name: 'parent',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '851lt85ljpm51po81gh1par1u',
                        name: 'count',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ss3xvgv8d4he00qljx6lepvg0',
                        name: 'wp_term_taxonomy_pkey',
                        unique: true,
                        fieldIds: ['09qxmhzgvtmmjaorme35vy3u1'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'f4i287zfm1wa9bic8m4yxoql4',
                name: 'wp_registration_log',
                schema: 'public',
                x: 336.70664580935386,
                y: -200.13535305955423,
                fields: [
                    {
                        id: '071hdw9pi8k45lyk1diymh2me',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wu2nu9g8om1yx8w7jgepo10z1',
                        name: 'email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'j5svtjr4n8rlguslajiod57l2',
                        name: 'ip',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 't3giqzegtkxjvqev8h2jhuxhl',
                        name: 'blog_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gfnnysvndpw0cmu9nlid6m0eq',
                        name: 'date_registered',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rlf75dvljr0mjlrka4ipwb8i0',
                        name: 'wp_registration_log_pkey',
                        unique: true,
                        fieldIds: ['071hdw9pi8k45lyk1diymh2me'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jctta9mhqs7w2j538wury1c1w',
                name: 'wp_sitemeta',
                schema: 'public',
                x: 1752.3427634050681,
                y: 499.5922695739325,
                fields: [
                    {
                        id: 'zl8twki9u4t486f0p21m31eiw',
                        name: 'meta_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'rnwokdmkf593zs2l752sqqzv6',
                        name: 'site_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gnlcycyrp7f1q7bkxbdrh03xb',
                        name: 'meta_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ukhfp21h84idda7auuei8uyus',
                        name: 'meta_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ir4tc926rcun9smlqc9khpnch',
                        name: 'idx_wp_sitemeta_meta_key',
                        unique: false,
                        fieldIds: ['gnlcycyrp7f1q7bkxbdrh03xb'],
                        createdAt: now,
                    },
                    {
                        id: 'xlrirwu5g04wcysbdtdfaqip5',
                        name: 'wp_sitemeta_pkey',
                        unique: true,
                        fieldIds: ['zl8twki9u4t486f0p21m31eiw'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'jnxcbry0h8skqzb9hcycb3yyo',
                name: 'wp_usermeta',
                schema: 'public',
                x: 709.4072716381884,
                y: 18.800685166975825,
                fields: [
                    {
                        id: 'jqfsj7temp0fsbzlryvvkyo6g',
                        name: 'umeta_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '8lhehz3ccq3uk6pj9ljs1n8ps',
                        name: 'user_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6ot5byk6w7lgsnph1lu26snjq',
                        name: 'meta_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ob8e6h2awjhgpynq2fr8qti93',
                        name: 'meta_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qcl8hfp0hd04ab1rnpfylik18',
                        name: 'idx_wp_usermeta_meta_key',
                        unique: false,
                        fieldIds: ['6ot5byk6w7lgsnph1lu26snjq'],
                        createdAt: now,
                    },
                    {
                        id: 'ts3ynssl3wyk7to1c5mvsg9ig',
                        name: 'idx_wp_usermeta_user_id',
                        unique: false,
                        fieldIds: ['8lhehz3ccq3uk6pj9ljs1n8ps'],
                        createdAt: now,
                    },
                    {
                        id: '6rtblmvm4pgeuqts9t28av0nm',
                        name: 'wp_usermeta_pkey',
                        unique: true,
                        fieldIds: ['jqfsj7temp0fsbzlryvvkyo6g'],
                        createdAt: now,
                    },
                ],
                color: '#ff6363',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'm2pgq2gj9kmakbqiuhhm0ymko',
                name: 'wp_commentmeta',
                schema: 'public',
                x: 442.1179369051895,
                y: -471.9477386188898,
                fields: [
                    {
                        id: '6cze2mduwrww0iur1f1c3s2p7',
                        name: 'meta_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'irhkiwlxmpkt03b9t9movacxf',
                        name: 'comment_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yk1zwabnq4d9yiuz7x4jlvkax',
                        name: 'meta_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8jiskj9rqrg5zz3j7pifsj4z2',
                        name: 'meta_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'pcz5y9sfbdydgmj9m1llpdd56',
                        name: 'wp_commentmeta_pkey',
                        unique: true,
                        fieldIds: ['6cze2mduwrww0iur1f1c3s2p7'],
                        createdAt: now,
                    },
                    {
                        id: 'z1xl2x7tdla1zgrhhfe3wcibz',
                        name: 'idx_wp_commentmeta_meta_key',
                        unique: false,
                        fieldIds: ['yk1zwabnq4d9yiuz7x4jlvkax'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'nfun7jg6et5f144k96bq7eu2c',
                name: 'wp_term_relationships',
                schema: 'public',
                x: 1538.3618565667916,
                y: -53.34858704815218,
                fields: [
                    {
                        id: 'cmjlk9apmb8hz592dkvjl1xv7',
                        name: 'object_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'oyvu5e3do75r1ak7fmtco10a6',
                        name: 'term_taxonomy_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wu2tjxmt00xdb8k4f6hhtx8nk',
                        name: 'term_order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'qwrbjsuu622zbu3rtz5nqreer',
                        name: 'wp_term_relationships_pkey',
                        unique: true,
                        fieldIds: [
                            'cmjlk9apmb8hz592dkvjl1xv7',
                            'oyvu5e3do75r1ak7fmtco10a6',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'o9wjk1il4nid4wtm7pf2c0gl3',
                name: 'wp_posts',
                schema: 'public',
                x: 1206.3931525008106,
                y: -475.19184039348437,
                fields: [
                    {
                        id: 'ohqdzo2yw6xrfvgazfk83qibs',
                        name: 'id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bkg7pyku9dmaxsw8v1ppewqyy',
                        name: 'post_author',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '34seq71wmki6hepb80m1tba8q',
                        name: 'post_date',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'zf0rlrrv1xly7zkcod23cfhw3',
                        name: 'post_date_gmt',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i343vq5wnfdk8b884m7aoyw8j',
                        name: 'post_content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7uzxip5edic2mjmh84p673ywo',
                        name: 'post_title',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'h9f0qmodolqu6mfm823w7oubo',
                        name: 'post_excerpt',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'g5h3d3cvr7tv07xe9braw9its',
                        name: 'post_status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '48cvgw9xvake61539g6xihg65',
                        name: 'comment_status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0b494kintpbzk4e9z61tzym8e',
                        name: 'ping_status',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4urj19xliob1s0d8udyojyqp4',
                        name: 'post_password',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nj2xm6ik42ishwlgkqq9d96pj',
                        name: 'post_name',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0rxwj5teawq06zsjz1o42ogp9',
                        name: 'to_ping',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '20be8sgu7moxo4q37r2xe4qcf',
                        name: 'pinged',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rf7i6j7514u8f1gi6baxsdbdr',
                        name: 'post_modified',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dzbr49f08buq2p7v96wxdj5fb',
                        name: 'post_modified_gmt',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'y83q018xhzmaghohl3yf6t5lq',
                        name: 'post_content_filtered',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kr9xstgjcs28w0p9xl7ou99sx',
                        name: 'post_parent',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5uv7pk14zonon7o2wu23jh28j',
                        name: 'guid',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dvbur4nldxoaau4r52n5yd17x',
                        name: 'menu_order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '822fs67u0lsbr09urmd57fp0v',
                        name: 'post_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'wh1hlt26f6c4zew0d6e4npqzt',
                        name: 'post_mime_type',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lorg0ztm3l10izxwfn8bhjp5k',
                        name: 'comment_count',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'r2m232610v7ug6lbam85qlmuy',
                        name: 'idx_wp_posts_post_author',
                        unique: false,
                        fieldIds: ['bkg7pyku9dmaxsw8v1ppewqyy'],
                        createdAt: now,
                    },
                    {
                        id: 'fl4rkl6pnivpsl2hqep6m5xp0',
                        name: 'wp_posts_pkey',
                        unique: true,
                        fieldIds: ['ohqdzo2yw6xrfvgazfk83qibs'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rs34x80mnoaxv269n3k7cc0yc',
                name: 'wp_signups',
                schema: 'public',
                x: 335.71179577700696,
                y: 44.51791435088094,
                fields: [
                    {
                        id: 'ikroslhrzcvu6qu454toiw0gm',
                        name: 'signup_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 't6c5iykqfbud8mikvtt8du77k',
                        name: 'domain',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lqeojhpm1ecoslt7ch85mngav',
                        name: 'path',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lffog8fqfh2nguak3k0tl0x8m',
                        name: 'title',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'diasmqvuuw46fhu7m9lyyd5hc',
                        name: 'user_login',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ca7q66r0fxwxot45n1rtyyaqm',
                        name: 'user_email',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '07zl3e49zyd4wthaz7yh7f39s',
                        name: 'registered',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i013ak1jy912dlt3jihijybpb',
                        name: 'activated',
                        type: {
                            id: 'timestamp_without_time_zone',
                            name: 'timestamp without time zone',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '99j846njnrleej2dots1eb7u3',
                        name: 'active',
                        type: {
                            id: 'smallint',
                            name: 'smallint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '6dq939xrodri1jtac4omgfdsg',
                        name: 'activation_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vrh2qb8tnce02anrm7co3y4mh',
                        name: 'meta',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'noerd3lu5cw81yhrdnn2vgl0u',
                        name: 'wp_signups_pkey',
                        unique: true,
                        fieldIds: ['ikroslhrzcvu6qu454toiw0gm'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'wqlqwd8ae4ejnblmh220lkqfp',
                name: 'wp_termmeta',
                schema: 'public',
                x: 1551.421073393647,
                y: 246.169076258073,
                fields: [
                    {
                        id: '1jcuakfvukr5ad57hvumcqw05',
                        name: 'meta_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'qxigvqtet9arcsufkto8t2lei',
                        name: 'term_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ypbzmo8ujg13j4hapsumsbkrl',
                        name: 'meta_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3a8x9a5a2uey3q652red9kh2d',
                        name: 'meta_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'rllpxppdpx1gub7fgqbjrq7xg',
                        name: 'idx_wp_termmeta_meta_key',
                        unique: false,
                        fieldIds: ['ypbzmo8ujg13j4hapsumsbkrl'],
                        createdAt: now,
                    },
                    {
                        id: 'cj3ani53e1qq3py2ltiy6w0kq',
                        name: 'wp_termmeta_pkey',
                        unique: true,
                        fieldIds: ['1jcuakfvukr5ad57hvumcqw05'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ygw2bw4n5eduybebung4kr0a0',
                name: 'wp_postmeta',
                schema: 'public',
                x: 1603.621225253945,
                y: -524.5323780790153,
                fields: [
                    {
                        id: 'x51latdrxck97z1jvwrznv3gq',
                        name: 'meta_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '15jh2sepwhc688w3aurbw0h8y',
                        name: 'post_id',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '2k8xrzsnzr4l2lyvag54j1wd6',
                        name: 'meta_key',
                        type: {
                            id: 'character_varying',
                            name: 'character varying',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7u8y6qis3ukz7m00cynbzyoez',
                        name: 'meta_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '191b66rphjkpjj9sdwe4t5on3',
                        name: 'idx_wp_postmeta_post_id',
                        unique: false,
                        fieldIds: ['15jh2sepwhc688w3aurbw0h8y'],
                        createdAt: now,
                    },
                    {
                        id: '6s5df7dgo3czgr50qohgd5cd7',
                        name: 'idx_wp_postmeta_meta_key',
                        unique: false,
                        fieldIds: ['2k8xrzsnzr4l2lyvag54j1wd6'],
                        createdAt: now,
                    },
                    {
                        id: '1c36k6xpsqrn41bsxbjox6pyf',
                        name: 'wp_postmeta_pkey',
                        unique: true,
                        fieldIds: ['x51latdrxck97z1jvwrznv3gq'],
                        createdAt: now,
                    },
                ],
                color: '#ffe374',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '0ns8qeop7ajstaeon129h6m9r',
                name: 'wp_usermeta_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'jnxcbry0h8skqzb9hcycb3yyo',
                targetTableId: '6xlz7vv2yf4k4likkwbpt9n7c',
                sourceFieldId: '8lhehz3ccq3uk6pj9ljs1n8ps',
                targetFieldId: 'hxm27ltfcn5nmpe916rghd74y',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '7igklsiesi7t0i80knwn7yrw5',
                name: 'wp_sitemeta_site_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'jctta9mhqs7w2j538wury1c1w',
                targetTableId: '5o1x7miqtyc34fu92j2l1mre4',
                sourceFieldId: 'rnwokdmkf593zs2l752sqqzv6',
                targetFieldId: 'yob6do17uh4cr0ypj2i0fie0o',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '89y687cq1w5o844t9z819rn49',
                name: 'wp_term_relationships_term_taxonomy_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'nfun7jg6et5f144k96bq7eu2c',
                targetTableId: 'ew6aq96etubkyb6z3zytzf11s',
                sourceFieldId: 'oyvu5e3do75r1ak7fmtco10a6',
                targetFieldId: '09qxmhzgvtmmjaorme35vy3u1',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'a86cjc98872nta2h9svn0zh5m',
                name: 'wp_posts_post_author_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'o9wjk1il4nid4wtm7pf2c0gl3',
                targetTableId: '6xlz7vv2yf4k4likkwbpt9n7c',
                sourceFieldId: 'bkg7pyku9dmaxsw8v1ppewqyy',
                targetFieldId: 'hxm27ltfcn5nmpe916rghd74y',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'b2pol2cl7cvwia9ijndykugry',
                name: 'wp_termmeta_term_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'wqlqwd8ae4ejnblmh220lkqfp',
                targetTableId: '7ce2o0mij9li0k4g83swbhi5x',
                sourceFieldId: 'qxigvqtet9arcsufkto8t2lei',
                targetFieldId: 'fc9nfbmnaj04jkd8v2iv42wqk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'b3yv64bbnp2ba5zz15gjjitfo',
                name: 'wp_term_taxonomy_term_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ew6aq96etubkyb6z3zytzf11s',
                targetTableId: '7ce2o0mij9li0k4g83swbhi5x',
                sourceFieldId: '21hja8tuvhtx7a4en2cdw7f9j',
                targetFieldId: 'fc9nfbmnaj04jkd8v2iv42wqk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'f219so73ppnc8ekaf85ginq6n',
                name: 'wp_term_relationships_object_id_fk',
                sourceSchema: 'public',
                sourceTableId: 'nfun7jg6et5f144k96bq7eu2c',
                targetSchema: 'public',
                targetTableId: 'o9wjk1il4nid4wtm7pf2c0gl3',
                sourceFieldId: 'cmjlk9apmb8hz592dkvjl1xv7',
                targetFieldId: 'ohqdzo2yw6xrfvgazfk83qibs',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fc7cpnphzy7vwgu5ufsv5gyhm',
                name: 'wp_comments_comment_post_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '5719hh2vceoxft07yyuw412nf',
                targetTableId: 'o9wjk1il4nid4wtm7pf2c0gl3',
                sourceFieldId: '6opwy4tby70gcyv07zfdlwy5z',
                targetFieldId: 'ohqdzo2yw6xrfvgazfk83qibs',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'kupr53r1vouh0z2ltruwa6dns',
                name: 'wp_postmeta_post_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ygw2bw4n5eduybebung4kr0a0',
                targetTableId: 'o9wjk1il4nid4wtm7pf2c0gl3',
                sourceFieldId: '15jh2sepwhc688w3aurbw0h8y',
                targetFieldId: 'ohqdzo2yw6xrfvgazfk83qibs',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'qxotox85i9w98igh93fles0dt',
                name: 'wp_links_link_owner_fk',
                sourceSchema: 'public',
                sourceTableId: '0ovpgck8or3x6m2xn2hmbp0c4',
                targetSchema: 'public',
                targetTableId: '6xlz7vv2yf4k4likkwbpt9n7c',
                sourceFieldId: 'vdmz1ajoyc2xwznmgfoz0gx5s',
                targetFieldId: 'hxm27ltfcn5nmpe916rghd74y',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 's417vqou6082w7vjq5gi69ta0',
                name: 'wp_comments_user_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '5719hh2vceoxft07yyuw412nf',
                targetTableId: '6xlz7vv2yf4k4likkwbpt9n7c',
                sourceFieldId: 'bzfamxzjmb99922r0msiht80n',
                targetFieldId: 'hxm27ltfcn5nmpe916rghd74y',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'svol4nyb1j4x1xhqr90ztudut',
                name: 'wp_commentmeta_comment_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'm2pgq2gj9kmakbqiuhhm0ymko',
                targetTableId: '5719hh2vceoxft07yyuw412nf',
                sourceFieldId: 'irhkiwlxmpkt03b9t9movacxf',
                targetFieldId: 'bu3m7h9vakhkun8k6nrrs18ld',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
